#!/usr/bin/env python3
"""STATECOMPAT old-binary-reopen lab driver (ARC v0.8.11 release lab).

THROWAWAY BRANCH ONLY (statecompat-v0811-lab, never merged). Python standard
library only (3.8+). It runs on a GitHub-hosted Linux runner against LAB
fixture data: validator keys, checkpoints and genesis are generated by the Rust
harness (crates/arc-node/tests/old_binary_reopen_lab.rs) for this run. It never
touches production state, hosts, addresses or keys, and it never prints key
material.

What it does, per tier (prod = production-feature binaries and flag set;
native = native-runtime lifecycle with the deterministic test executor):

  S00 binaries   digests and versions of the OLD (v0.8.10) and NEW (v0.8.11) binaries
  S01 fixture    the six-validator recovered-v3 fixture (harness step)
  S02 old_run    v0.8.10 produces recovered state, stopped cleanly (harness step)
  S03 copy_pre   byte copy + manifest of digests (pre-candidate copy)
  S04 candidate  v0.8.11 runs on a copy until it committed blocks (harness step)
  S05 copy_post  stopped cleanly, byte copy + manifest (post-candidate copy) + delta
  S06 reopen     v0.8.10 reopens the post-candidate copy, one process per node,
                 each in its own empty network namespace (loopback only, no peers),
                 observer mode (--stake 0, no key: no consensus engine, no signing);
                 judged on height, block hashes, state roots, exit status, logs
  S07 control    the same reopen on the PRE-candidate copy (isolates what is due
                 to the candidate; must fail the freshness checks, pass the format ones)
  S08 validator  the same reopen with the production validator argument vector
                 (isolated, no peers): the principal "node starts on this state" proof
  S09 inspectors the offline recovery inspectors, only where the layout fits
  S10 resume     all six v0.8.10 nodes on a copy of the post-candidate state, loopback
                 mesh, signing on: reconnect, resume, commit new work (harness step)
  S11 negatives  damage controls: the harness is not vacuous only if damage is detected

Every step records digests; nothing here edits a workflow or reads a secret.
"""
import argparse
import datetime
import fcntl
import hashlib
import json
import os
import re
import shutil
import signal
import socket
import stat
import struct
import subprocess
import sys
import tarfile
import time
import unittest
import urllib.error
import urllib.request
import zipfile
from pathlib import Path

SCHEMA_TIER = "arc.statecompat-lab.tier-result.v1"
SCHEMA_REOPEN = "arc.statecompat-lab.reopen-evidence.v1"
SCHEMA_SUMMARY = "arc.statecompat-lab.summary.v1"
SCHEMA_MANIFEST = "arc.statecompat-lab.manifest.v1"

REPOSITORY = "FerrumVir/arc-chain"
SOURCE_SHA = "cd2344138b32a46eea9192cf0fa7344db6481420"
SOURCE_TREE = "f002ed5d9c5e645a83820e31f944d509c1899eb5"
BASELINE_SHA = "fd4e8cd2f76b97d08221a622397f513ad04000ad"
OLD_VERSION = "0.8.10"
NEW_VERSION = "0.8.11"

NODES = 6
BASE_RPC = 9980
BASE_P2P = 9180
STAKES = [6666667, 6666667, 6666667, 6666667, 6666666, 6666666]

HEX64 = re.compile(r"^[0-9a-f]{64}$")


class LabError(Exception):
    pass


def need(condition, message):
    if not condition:
        raise LabError(message)


def now():
    return datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def log(message):
    print("[lab %s] %s" % (now(), message), flush=True)


def sha256_bytes(data):
    return hashlib.sha256(data).hexdigest()


def sha256_file(path):
    digest = hashlib.sha256()
    with open(str(path), "rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def canonical(obj):
    return json.dumps(obj, sort_keys=True, separators=(",", ":"), ensure_ascii=True).encode("utf-8")


def write_json(path, obj):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def read_json(path):
    return json.loads(Path(path).read_text(encoding="utf-8"))


def norm_hex(value):
    """Block JSON carries plain hex; /network/info and /sync/snapshot/info print 0x-prefixed Display."""
    if not isinstance(value, str):
        return None
    value = value.strip().lower()
    return value[2:] if value.startswith("0x") else value


# ----------------------------------------------------------------- manifests --

def classify(rel):
    base = os.path.basename(rel)
    if base == "node.log":
        return "log"
    if base == ".arc-node.lock":
        return "lock"
    return "state"


def build_manifest(root, label):
    """Per-path record of a data directory: type, size, mode, sha256 (mtimes are deliberately excluded)."""
    root = str(root)
    rows = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames.sort()
        filenames.sort()
        rel_dir = os.path.relpath(dirpath, root)
        for name in list(dirnames) + list(filenames):
            full = os.path.join(dirpath, name)
            rel = name if rel_dir == "." else os.path.join(rel_dir, name)
            info = os.lstat(full)
            mode = "%04o" % (info.st_mode & 0o7777)
            if stat.S_ISLNK(info.st_mode):
                row = {"path": rel, "type": "symlink", "target": os.readlink(full), "mode": mode}
            elif stat.S_ISDIR(info.st_mode):
                row = {"path": rel, "type": "dir", "mode": mode}
            elif stat.S_ISREG(info.st_mode):
                row = {"path": rel, "type": "file", "size": info.st_size, "mode": mode, "sha256": sha256_file(full)}
            else:
                row = {"path": rel, "type": "other", "mode": mode}
            row["class"] = classify(rel)
            rows.append(row)
    rows.sort(key=lambda r: r["path"])
    state_rows = [r for r in rows if r["class"] == "state"]
    return {
        "schema": SCHEMA_MANIFEST,
        "label": label,
        "file_count": sum(1 for r in rows if r["type"] == "file"),
        "total_bytes": sum(r.get("size", 0) for r in rows),
        "tree_sha256": sha256_bytes(canonical(rows)),
        "state_tree_sha256": sha256_bytes(canonical(state_rows)),
        "rows": rows,
    }


def manifests_equal(a, b):
    return a["rows"] == b["rows"]


def kind_of(path):
    """A file 'kind': the path with node index, hex names and counters abstracted away."""
    p = re.sub(r"^node-\d+/", "node-N/", path)
    p = re.sub(r"[0-9a-fA-F]{16,}", "<hex>", p)
    p = re.sub(r"\d+", "<n>", p)
    return p


def manifest_delta(before, after):
    b = {r["path"]: r for r in before["rows"]}
    a = {r["path"]: r for r in after["rows"]}
    added = sorted(set(a) - set(b))
    removed = sorted(set(b) - set(a))
    modified = []
    unchanged = 0
    for path in sorted(set(a) & set(b)):
        ra, rb = a[path], b[path]
        same = (ra.get("sha256") == rb.get("sha256") and ra.get("target") == rb.get("target")
                and ra["mode"] == rb["mode"] and ra["type"] == rb["type"])
        if same:
            unchanged += 1
        else:
            modified.append({"path": path, "class": ra["class"], "size_before": rb.get("size"), "size_after": ra.get("size")})
    kinds_before = set(kind_of(p) for p in b if b[p]["type"] != "dir")
    kinds_after = set(kind_of(p) for p in a if a[p]["type"] != "dir")
    return {
        "added": added,
        "removed": removed,
        "modified": modified,
        "unchanged_count": unchanged,
        "new_file_kinds": sorted(kinds_after - kinds_before),
        "vanished_file_kinds": sorted(kinds_before - kinds_after),
        "state_files_added": [p for p in added if a[p]["class"] == "state" and a[p]["type"] == "file"],
        "state_files_modified": [m["path"] for m in modified if m["class"] == "state"],
    }


def directory_listing(root, limit=400):
    rows = []
    for dirpath, dirnames, filenames in os.walk(str(root)):
        dirnames.sort()
        for name in sorted(filenames):
            full = os.path.join(dirpath, name)
            rows.append("%s %d" % (os.path.relpath(full, str(root)), os.lstat(full).st_size))
            if len(rows) >= limit:
                return rows + ["... truncated"]
    return rows


def copy_tree(src, dst):
    need(not os.path.exists(str(dst)), "refusing to overwrite existing copy target %s" % dst)
    shutil.copytree(str(src), str(dst), symlinks=True)


# ---------------------------------------------------------------- HTTP / chain --

def http_json(port, path, timeout=10):
    url = "http://127.0.0.1:%d%s" % (port, path)
    try:
        with urllib.request.urlopen(url, timeout=timeout) as response:
            if response.status != 200:
                return None
            return json.loads(response.read().decode("utf-8"))
    except (urllib.error.URLError, ConnectionError, socket.timeout, ValueError, OSError):
        return None


def dump_chain(port, tip):
    blocks = []
    for height in range(0, tip + 1):
        block = http_json(port, "/block/%d" % height)
        if block is None:
            blocks.append({"h": height, "missing": True})
        else:
            header = block.get("header") or {}
            blocks.append({
                "h": height,
                "hash": block.get("hash"),
                "state_root": header.get("state_root"),
                "parent_hash": header.get("parent_hash"),
                "tx_count": header.get("tx_count"),
                "protocol_major": (header.get("protocol_version") or {}).get("major"),
            })
    return blocks


def chain_of(blocks):
    out = {}
    for block in blocks or []:
        if not block.get("missing"):
            out[block["h"]] = (norm_hex(block.get("hash")), norm_hex(block.get("state_root")))
    return out


def expected_from_obs(node_obs):
    health = node_obs.get("health") or {}
    info = node_obs.get("network_info") or {}
    snap = node_obs.get("snapshot_info") or {}
    return {
        "port": node_obs.get("port"),
        "height": health.get("height"),
        "tip": info.get("last_block_height"),
        "tip_hash": norm_hex(info.get("last_block_hash")),
        "snapshot_height": snap.get("height"),
        "snapshot_root": norm_hex(snap.get("state_root")),
        "chain": chain_of(node_obs.get("blocks")),
    }


def observation_by_label(record, label):
    for observation in record.get("observations", []):
        if observation.get("label") == label:
            return observation
    raise LabError("observation %r missing from step %r" % (label, record.get("step")))


def history_preserved(earlier, later):
    """Every block the earlier observation served is served identically by the later one, node by node."""
    problems = []
    later_by_port = {n["port"]: n for n in later["nodes"]}
    compared = 0
    for node in earlier["nodes"]:
        other = later_by_port.get(node["port"])
        if other is None:
            problems.append("port %s absent" % node["port"])
            continue
        mine, theirs = chain_of(node.get("blocks")), chain_of(other.get("blocks"))
        for height, value in mine.items():
            compared += 1
            if theirs.get(height) != value:
                problems.append("port %s height %s differs or is missing" % (node["port"], height))
                break
    return {"ok": not problems and compared > 0, "compared_blocks": compared, "problems": problems[:10]}


# ------------------------------------------------------------------- logs ------

ANSI = re.compile(r"\x1b\[[0-9;]*[A-Za-z]")
TIMESTAMP = re.compile(r"^\s*\d{4}-\d{2}-\d{2}T[\d:.]+Z\s+")
LEVEL = re.compile(r"^\s*(TRACE|DEBUG|INFO|WARN|ERROR)\b")
HARD = re.compile(
    r"panicked at|\bpanic\b|\bFATAL\b|corrupt|checksum|(?:digest|hash|state root) mismatch|"
    r"cannot (?:decode|deserialize|parse)|failed to (?:decode|deserialize|parse|load|read|open|replay)|"
    r"unsupported (?:format|version)|incompatible|invalid (?:magic|header|record|manifest|snapshot)|"
    r"unknown (?:record|tag|variant|version)|EQUIVOCATION|equivocation detected|Slash applied",
    re.IGNORECASE,
)


def log_signature(line):
    text = ANSI.sub("", line)
    text = TIMESTAMP.sub("", text)
    text = re.sub(r"0x[0-9a-fA-F]{6,}|\b[0-9a-fA-F]{16,}\b", "<hex>", text)
    text = re.sub(r"\d+", "<n>", text)
    return text.strip()[:300]


def scan_log(text):
    levels = {}
    errors, hard = set(), set()
    count = 0
    for raw in text.splitlines():
        count += 1
        line = ANSI.sub("", raw)
        match = LEVEL.match(TIMESTAMP.sub("", line))
        level = match.group(1) if match else None
        if level:
            levels[level] = levels.get(level, 0) + 1
        if level == "ERROR":
            errors.add(log_signature(line))
        if HARD.search(line):
            hard.add(log_signature(line))
    return {"lines": count, "levels": levels, "error_signatures": sorted(errors), "hard_signatures": sorted(hard)}


def new_signatures(scan, control):
    """Error/damage signatures present in `scan` that the control run did not show."""
    base = set(control["error_signatures"]) | set(control["hard_signatures"]) if control else set()
    mine = set(scan["error_signatures"]) | set(scan["hard_signatures"])
    return sorted(mine - base)


# ------------------------------------------------------------------ verdicts ---

def judge_node(expected, observed, expect_sha, expect_version, require_stable, scan_new):
    """The per-node verdict of one reopen. Pure: observed and expected are plain data."""
    checks = []

    def add(name, ok, detail=""):
        checks.append({"check": name, "ok": bool(ok), "detail": detail})

    add("process started and served /health", observed.get("started"), observed.get("start_error", ""))
    samples = observed.get("samples") or []
    last = samples[-1] if samples else {}
    health = last.get("health") or {}
    snap = last.get("snapshot_info") or {}
    add("the running executable is the expected binary (self-reported sha256)",
        bool(expect_sha) and health.get("binary_sha256") == expect_sha,
        "reported=%s expected=%s" % (health.get("binary_sha256"), expect_sha))
    add("reports the expected version", health.get("version") == expect_version,
        "reported=%s expected=%s" % (health.get("version"), expect_version))
    reopened = health.get("height")
    want = expected.get("height")
    add("height is not below the candidate's last observed height",
        isinstance(reopened, int) and isinstance(want, int) and reopened >= want,
        "reopened=%s candidate=%s" % (reopened, want))
    served = chain_of(observed.get("blocks"))
    missing, mismatched = [], []
    for height, value in expected["chain"].items():
        got = served.get(height)
        if got is None:
            missing.append(height)
        elif got != value:
            mismatched.append(height)
    add("every block the candidate served is served identically (hash and state root)",
        bool(expected["chain"]) and not missing and not mismatched,
        "compared=%d missing=%s mismatched=%s" % (len(expected["chain"]), missing[:5], mismatched[:5]))
    snap_height = snap.get("height")
    snap_root = norm_hex(snap.get("state_root"))
    stored = served.get(snap_height) if isinstance(snap_height, int) else None
    add("live state root equals the stored header state root at that height",
        stored is not None and snap_root is not None and stored[1] == snap_root,
        "height=%s live=%s stored=%s" % (snap_height, snap_root, stored[1] if stored else None))
    if expected.get("snapshot_height") is not None and snap_height == expected["snapshot_height"]:
        add("live state root equals the candidate's own live root at the same height",
            snap_root == expected["snapshot_root"], "reopened=%s candidate=%s" % (snap_root, expected["snapshot_root"]))
    tip_hash = norm_hex((last.get("network_info") or {}).get("last_block_hash"))
    tip_height = (last.get("network_info") or {}).get("last_block_height")
    tip_block = served.get(tip_height) if isinstance(tip_height, int) else None
    add("reported tip hash equals the served block hash at the tip",
        tip_block is not None and tip_block[0] == tip_hash, "tip=%s" % tip_height)
    if require_stable:
        views = set()
        for sample in samples:
            h = sample.get("health") or {}
            i = sample.get("network_info") or {}
            s = sample.get("snapshot_info") or {}
            views.add((h.get("height"), i.get("last_block_height"), norm_hex(i.get("last_block_hash")),
                       s.get("height"), norm_hex(s.get("state_root"))))
        add("state is stable across samples (nothing was committed or rewritten while open)",
            len(samples) >= 2 and len(views) == 1, "distinct views=%d samples=%d" % (len(views), len(samples)))
        add("no consensus engine was running (signing off)", health.get("chain_participation_enabled") is False,
            "chain_participation_enabled=%s" % health.get("chain_participation_enabled"))
    add("clean exit on SIGTERM", observed.get("exit_code") == 0, "exit=%s" % observed.get("exit_code"))
    add("no error or damage signatures beyond the control run's", not scan_new, "new=%s" % scan_new[:3])
    return {"port": expected.get("port"), "ok": all(c["ok"] for c in checks), "checks": checks}


def cross_node_agreement(observed_nodes):
    """On every height served by all nodes, hash and state root are identical on all of them."""
    chains = [chain_of(n.get("blocks")) for n in observed_nodes if n.get("started")]
    if len(chains) < 2:
        return {"ok": False, "detail": "fewer than two nodes served blocks"}
    common = set(chains[0])
    for chain in chains[1:]:
        common &= set(chain)
    bad = [h for h in sorted(common) if len(set(c[h] for c in chains)) != 1]
    return {"ok": bool(common) and not bad, "common_heights": len(common), "disagreements": bad[:10]}


def judge_reopen(expected_nodes, observed_nodes, expect_sha, expect_version, require_stable, scans, control_scans):
    by_port = {n.get("port"): n for n in observed_nodes}
    verdicts = []
    for expected in expected_nodes:
        observed = by_port.get(expected["port"]) or {"started": False, "start_error": "no result for this node"}
        scan = scans.get(expected["port"])
        control = control_scans.get(expected["port"]) if control_scans else None
        new = new_signatures(scan, control) if scan else ["no log was captured"]
        verdicts.append(judge_node(expected, observed, expect_sha, expect_version, require_stable, new))
    if len(expected_nodes) > 1:
        agreement = cross_node_agreement(list(by_port.values()))
    else:
        agreement = {"ok": True, "detail": "single node: cross-node agreement not applicable"}
    return {"ok": all(v["ok"] for v in verdicts) and agreement["ok"], "nodes": verdicts, "agreement": agreement}


def failed_checks(verdict):
    names = []
    for node in verdict["nodes"]:
        for check in node["checks"]:
            if not check["ok"]:
                names.append(check["check"])
    return sorted(set(names))


# ------------------------------------------------------------- isolation -------

def interface_names():
    names = []
    with open("/proc/net/dev") as stream:
        for line in stream.readlines()[2:]:
            names.append(line.split(":")[0].strip())
    return names


def bring_up_loopback():
    """SIOCSIFFLAGS on lo, so 127.0.0.1 works inside an otherwise empty network namespace."""
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        request = struct.pack("16sH", b"lo", 0)
        flags = struct.unpack("16sH", fcntl.ioctl(sock.fileno(), 0x8913, request))[1]
        fcntl.ioctl(sock.fileno(), 0x8914, struct.pack("16sH", b"lo", flags | 0x1))
    finally:
        sock.close()


def describe_isolation():
    evidence = {"netns": os.readlink("/proc/self/ns/net")}
    try:
        bring_up_loopback()
        evidence["loopback_up"] = True
    except OSError as exc:
        evidence["loopback_up"] = False
        evidence["loopback_error"] = repr(exc)
    evidence["interfaces"] = interface_names()
    try:
        with open("/proc/net/route") as stream:
            evidence["ipv4_routes"] = [line.strip() for line in stream.readlines()[1:] if line.strip()]
    except OSError as exc:
        evidence["ipv4_routes_error"] = repr(exc)
    tests = []
    for kind, target in (("tcp", ("1.1.1.1", 443)), ("udp", ("8.8.8.8", 53)), ("tcp", ("9.9.9.9", 443))):
        try:
            if kind == "tcp":
                conn = socket.create_connection(target, timeout=3)
            else:
                conn = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
                conn.connect(target)
            conn.close()
            tests.append({"target": "%s:%d" % target, "kind": kind, "reachable": True})
        except OSError as exc:
            tests.append({"target": "%s:%d" % target, "kind": kind, "reachable": False,
                          "error": os.strerror(exc.errno) if exc.errno else repr(exc)})
    evidence["outbound_tests"] = tests
    evidence["isolated"] = (evidence.get("loopback_up") is True and evidence["interfaces"] == ["lo"]
                            and not any(t["reachable"] for t in tests))
    return evidence


def isolation_prefixes():
    return [
        ("unshare --user --map-root-user --net", ["unshare", "-Urn", "--"]),
        ("sudo unshare --net (privileges dropped for the node)", ["sudo", "-n", "unshare", "-n", "--"]),
    ]


def pick_isolation():
    """The first way of getting an empty network namespace that really works on this runner."""
    probe = [sys.executable, str(Path(__file__).resolve()), "isolation-check"]
    for name, prefix in isolation_prefixes():
        try:
            result = subprocess.run(prefix + probe, capture_output=True, text=True, timeout=60)
        except (OSError, subprocess.SubprocessError):
            continue
        if result.returncode == 0:
            try:
                evidence = json.loads(result.stdout)
            except ValueError:
                continue
            if evidence.get("isolated") and evidence.get("netns") != os.readlink("/proc/self/ns/net"):
                return name, prefix, evidence
    return None, None, None


def cmd_isolation_check(_args):
    print(json.dumps(describe_isolation(), sort_keys=True))
    return 0


# ------------------------------------------------------------ the node probe ---

def node_argv(spec):
    """Argument vector for one isolated reopen. No --peers: there is nobody to talk to."""
    index = spec["index"]
    argv = [
        spec["binary"],
        "--rpc", "127.0.0.1:%d" % (BASE_RPC + index),
        "--p2p-port", str(BASE_P2P + index),
        "--data-dir", spec["data_dir"],
        "--genesis", spec["genesis"],
        "--native-inference-activation", spec["activation"],
    ]
    if spec["mode"] == "observer":
        # --stake 0 and no key: the node holds only a process-ephemeral identity
        # and starts no consensus engine, so it cannot sign a block, vote or vertex.
        argv += ["--stake", "0", "--archive"]
    else:
        argv += ["--stake", str(STAKES[index]), "--validator-key-file", spec["key_file"],
                 "--recovery-epoch", "1", "--validator-set-id", "1", "--archive",
                 "--snapshot-every-blocks", "50"]
        if spec.get("native_runtime"):
            argv += ["--native-inference-runtime", "--native-inference-test-executor",
                     "--enable-native-inference-requests"]
    return argv


def take_sample(port):
    return {
        "unix": int(time.time()),
        "health": http_json(port, "/health"),
        "network_info": http_json(port, "/network/info"),
        "snapshot_info": http_json(port, "/sync/snapshot/info"),
    }


def cmd_probe_reopen(args):
    """Runs INSIDE the isolated namespace: starts one node, watches it, stops it, writes a result."""
    spec = read_json(args.spec)
    result = {"index": spec["index"], "port": BASE_RPC + spec["index"], "mode": spec["mode"], "started": False,
              "samples": [], "blocks": [], "exit_code": None}
    process = None
    try:
        if spec.get("isolation_override") is not None and os.environ.get("STATECOMPAT_ALLOW_TEST_OVERRIDES") == "1":
            result["isolation"] = dict(spec["isolation_override"], test_override=True)
        else:
            result["isolation"] = describe_isolation()
        argv = node_argv(spec)
        result["argv"] = argv
        kwargs = {}
        if spec.get("drop_uid") is not None and os.geteuid() == 0:
            kwargs["user"] = spec["drop_uid"]
            kwargs["group"] = spec["drop_gid"]
        log_path = Path(spec["log"])
        log_path.parent.mkdir(parents=True, exist_ok=True)
        env = dict(os.environ, RUST_LOG="info")
        with open(str(log_path), "ab") as log_file:
            process = subprocess.Popen(argv, stdout=log_file, stderr=subprocess.STDOUT, env=env, **kwargs)
            port = result["port"]
            deadline = time.time() + spec.get("start_timeout", 240)
            while time.time() < deadline:
                if process.poll() is not None:
                    result["start_error"] = "exited with status %s before serving /health" % process.returncode
                    break
                if http_json(port, "/health", timeout=3):
                    result["started"] = True
                    break
                time.sleep(1)
            else:
                result["start_error"] = "no /health within %ss" % spec.get("start_timeout", 240)
            if result["started"]:
                digest_deadline = time.time() + 150
                while time.time() < digest_deadline:
                    health = http_json(port, "/health") or {}
                    if isinstance(health.get("binary_sha256"), str):
                        break
                    time.sleep(1)
                for _ in range(spec.get("samples", 3)):
                    result["samples"].append(take_sample(port))
                    time.sleep(spec.get("sample_gap", 4))
                tip = ((result["samples"][-1].get("network_info") or {}).get("last_block_height"))
                if isinstance(tip, int):
                    result["blocks"] = dump_chain(port, tip)
            if process.poll() is None:
                process.send_signal(signal.SIGTERM)
                try:
                    result["exit_code"] = process.wait(timeout=60)
                except subprocess.TimeoutExpired:
                    process.kill()
                    process.wait()
                    result["exit_code"] = "killed after 60 s without exiting on SIGTERM"
            else:
                result["exit_code"] = process.returncode
    except Exception as exc:  # recorded, never swallowed
        result["probe_error"] = repr(exc)
    finally:
        if process is not None and process.poll() is None:
            process.kill()
            process.wait()
    write_json(args.out, result)
    return 0


# ----------------------------------------------------------- harness steps -----

def run_harness(harness, tier, step, env_extra, log_path, timeout):
    env = dict(os.environ)
    env.update({k: str(v) for k, v in env_extra.items()})
    env["LAB_STEP"] = step
    env["LAB_TIER"] = tier
    command = [str(harness), "lab_step", "--exact", "--nocapture", "--test-threads=1"]
    Path(log_path).parent.mkdir(parents=True, exist_ok=True)
    with open(str(log_path), "wb") as stream:
        process = subprocess.Popen(command, env=env, stdout=stream, stderr=subprocess.STDOUT, start_new_session=True)
        try:
            return process.wait(timeout=timeout)
        except subprocess.TimeoutExpired:
            os.killpg(process.pid, signal.SIGTERM)
            try:
                process.wait(timeout=30)
            except subprocess.TimeoutExpired:
                os.killpg(process.pid, signal.SIGKILL)
                process.wait()
            return -999


def binary_version_line(path):
    try:
        out = subprocess.run([str(path), "--version"], capture_output=True, text=True, timeout=60)
        return (out.stdout + out.stderr).strip().splitlines()[0] if (out.stdout + out.stderr).strip() else ""
    except (OSError, subprocess.SubprocessError) as exc:
        return "unavailable: %r" % exc


def started_reports(record):
    reports = []
    for event in record.get("events", []):
        if event.get("event") == "started":
            reports.append(event["detail"])
    return reports


def binary_reports_ok(record, expect_sha, require_feature=None):
    problems = []
    reports = started_reports(record)
    if not reports:
        problems.append("no start report recorded")
    for report in reports:
        for node in report["binary_report"]:
            if node.get("binary_sha256") != expect_sha:
                problems.append("port %s reported %s" % (node.get("port"), node.get("binary_sha256")))
            if require_feature and require_feature not in (node.get("features") or []):
                problems.append("port %s lacks feature %s" % (node.get("port"), require_feature))
    return {"ok": not problems, "starts": len(reports), "problems": problems[:10]}


# ---------------------------------------------------------------- tier runner --

FRESHNESS = "height is not below the candidate's last observed height"


class TierRunner:
    def __init__(self, args):
        self.args = args
        self.tier = args.tier
        self.root = Path(args.work).resolve() / args.tier
        self.out = Path(args.out).resolve()
        self.harness = Path(args.harness).resolve()
        self.old_bin = Path(args.old_bin).resolve()
        self.new_bin = Path(args.new_bin).resolve()
        self.old_sha = args.old_sha
        self.new_sha = args.new_sha
        self.steps = []
        self.checks = {}
        self.flags = []
        self.caveats = []
        self.digests = {}
        self.extra = "--recovery-epoch 1 --validator-set-id 1 --archive --snapshot-every-blocks 50"
        self.native = args.tier == "native"
        self.isolation_name = None
        self.isolation_prefix = None
        self.isolation_evidence = None
        self.reopen_runs = {}
        self.binaries = None
        self.fixture_meta = None
        self.sample_gap = 4
        self.start_timeout = 240
        self.test_isolation_override = None  # honoured only with STATECOMPAT_ALLOW_TEST_OVERRIDES=1 (unit tests)
        self.root.mkdir(parents=True, exist_ok=True)
        for sub in ("manifests", "observations", "logs", "harness-logs", "reopen", "fixture"):
            (self.out / sub).mkdir(parents=True, exist_ok=True)

    # ----- recording
    def begin(self, name, **info):
        record = {"step": name, "started": now(), "status": "running"}
        record.update(info)
        self.steps.append(record)
        log("%s: begin %s" % (self.tier, name))
        return record

    def finish(self, record, ok, **info):
        record.update(info)
        record["finished"] = now()
        record["status"] = "pass" if ok else "fail"
        log("%s: %s %s" % (self.tier, record["step"], record["status"]))
        return ok

    def check(self, name, ok, detail=""):
        self.checks[name] = {"ok": bool(ok), "detail": detail}

    def flag(self, text):
        self.flags.append(text)
        log("%s: FLAG %s" % (self.tier, text))

    def keep_manifest(self, manifest):
        write_json(self.out / "manifests" / (manifest["label"] + ".json"), manifest)
        self.digests["manifest:" + manifest["label"]] = {
            "tree_sha256": manifest["tree_sha256"], "state_tree_sha256": manifest["state_tree_sha256"],
            "files": manifest["file_count"], "bytes": manifest["total_bytes"]}
        return manifest

    def keep_logs(self, label, data_dir):
        target = self.out / "logs" / label
        target.mkdir(parents=True, exist_ok=True)
        for node_dir in sorted(Path(data_dir).glob("node-*")):
            source = node_dir / "node.log"
            if source.exists():
                shutil.copyfile(str(source), str(target / (node_dir.name + ".log")))

    def copy_with_proof(self, src, dst, label_src, label_dst):
        """Byte copy of a STOPPED data directory, proven equal by manifest, source proven unchanged."""
        before = self.keep_manifest(build_manifest(src, label_src))
        copy_tree(src, dst)
        copy = self.keep_manifest(build_manifest(dst, label_dst))
        after = build_manifest(src, label_src + "-after-copy")
        ok = manifests_equal(before, copy) and manifests_equal(before, after)
        return before, copy, ok

    def run_step(self, step, data_dir, binary, sha, prev, label):
        out_json = self.out / "observations" / (label + ".json")
        env = {
            "LAB_ROOT": self.root, "LAB_DATA": data_dir, "LAB_BIN": binary, "LAB_OUT": out_json,
            "LAB_EXPECT_SHA256": sha, "LAB_EXTRA_ARGS": self.extra, "LAB_PREV": ":".join(str(p) for p in prev),
        }
        rc = run_harness(self.harness, self.tier, step, env, self.out / "harness-logs" / (label + ".log"),
                         timeout=self.args.step_timeout)
        record = read_json(out_json) if out_json.exists() else None
        self.keep_logs(label, data_dir)
        complete = bool(record and record.get("complete"))
        return rc, record, complete

    # ----- foundation steps (every later step needs them)
    def s00_binaries(self):
        rec = self.begin("S00-binaries")
        rows = {}
        ok = True
        for role, path, expect, version in (("old", self.old_bin, self.old_sha, OLD_VERSION),
                                            ("new", self.new_bin, self.new_sha, NEW_VERSION)):
            digest = sha256_file(path)
            line = binary_version_line(path)
            rows[role] = {"path": str(path), "sha256": digest, "expected_sha256": expect, "size": path.stat().st_size,
                          "version_line": line, "expected_version": version}
            ok = ok and digest == expect and version in line
        self.binaries = rows
        self.check("binary digests and versions are as expected", ok, json.dumps(rows, sort_keys=True))
        return self.finish(rec, ok, binaries=rows)

    def s01_fixture(self):
        rec = self.begin("S01-fixture")
        rc, record, complete = self.run_step("fixture", self.root / "unused-data", self.old_bin, "", [], "fixture")
        fixture_dir = self.root / "fixture"
        ok = rc == 0 and complete and (fixture_dir / "fixture.json").exists()
        listing = []
        if fixture_dir.exists():
            for item in sorted(fixture_dir.iterdir()):
                if item.name.endswith(".key.json"):
                    # disposable lab validator keys: named and sized, never copied, hashed or printed
                    listing.append({"name": item.name, "kind": "disposable lab validator key", "size": item.stat().st_size})
                else:
                    listing.append({"name": item.name, "sha256": sha256_file(item), "size": item.stat().st_size})
                    shutil.copyfile(str(item), str(self.out / "fixture" / item.name))
        self.fixture_meta = read_json(fixture_dir / "fixture.json") if ok else {}
        return self.finish(rec, ok, exit_code=rc, fixture_files=listing,
                           activation_height=self.fixture_meta.get("activation_height"),
                           checkpoint_manifest=self.fixture_meta.get("manifest"))

    def s02_old_run(self):
        rec = self.begin("S02-old-run", binary=str(self.old_bin))
        self.d0 = self.root / "d0-old-live"
        rc, record, complete = self.run_step("old_run", self.d0, self.old_bin, self.old_sha, [], "old_run")
        self.old_record = record
        ok = rc == 0 and complete
        reports = binary_reports_ok(record or {}, self.old_sha, "native-test-executor" if self.native else None)
        self.check("old run: every node reported the old binary's digest on every start", reports["ok"], json.dumps(reports))
        return self.finish(rec, ok and reports["ok"], exit_code=rc, complete=complete, start_reports=reports)

    def s03_copy_pre(self):
        rec = self.begin("S03-copy-pre")
        self.d1 = self.root / "d1-pre-candidate-copy"
        _, copy, ok = self.copy_with_proof(self.d0, self.d1, "d0-old-live", "d1-pre-candidate-copy")
        self.m_pre = copy
        self.check("pre-candidate byte copy equals the stopped source, and the source is unchanged", ok,
                   "tree_sha256=%s" % copy["tree_sha256"])
        return self.finish(rec, ok, tree_sha256=copy["tree_sha256"], files=copy["file_count"], bytes=copy["total_bytes"])

    def s04_candidate(self):
        rec = self.begin("S04-candidate-run", binary=str(self.new_bin))
        self.d2 = self.root / "d2-candidate-working-copy"
        before, _, ok = self.copy_with_proof(self.d1, self.d2, "d1-pre-candidate-copy-recheck", "d2-candidate-working-copy-before-run")
        ok = ok and manifests_equal(before, self.m_pre)
        old_json = self.out / "observations" / "old_run.json"
        rc, record, complete = self.run_step("new_run", self.d2, self.new_bin, self.new_sha, [old_json], "new_run")
        self.new_record = record
        ok = ok and rc == 0 and complete
        reports = binary_reports_ok(record or {}, self.new_sha, "native-test-executor" if self.native else None)
        self.check("candidate run: every node reported the candidate binary's digest on every start", reports["ok"], json.dumps(reports))
        ok = ok and reports["ok"]
        if record and complete:
            start = observation_by_label(record, "start")
            final = observation_by_label(record, "final")
            old_final = observation_by_label(self.old_record, "final")
            seen = history_preserved(old_final, start)
            self.check("the candidate serves exactly the history the old binary wrote", seen["ok"], json.dumps(seen))
            kept = history_preserved(start, final)
            self.check("the candidate did not rewrite history while extending it", kept["ok"], json.dumps(kept))
            start_h = [(o["health"] or {}).get("height") for o in start["nodes"]]
            final_h = [(n["health"] or {}).get("height") for n in final["nodes"]]
            grew = all(isinstance(a, int) and isinstance(b, int) and b > a for a, b in zip(start_h, final_h))
            self.check("the candidate committed new blocks on every node", grew, "heights %s -> %s" % (start_h, final_h))
            versions = [(n["health"] or {}).get("version") for n in final["nodes"]]
            self.check("every candidate node reports version %s" % NEW_VERSION, all(v == NEW_VERSION for v in versions), str(versions))
            ok = ok and seen["ok"] and kept["ok"] and grew and all(v == NEW_VERSION for v in versions)
        else:
            ok = False
        return self.finish(rec, ok, exit_code=rc, complete=complete, start_reports=reports)

    def s05_copy_post(self):
        rec = self.begin("S05-copy-post")
        self.d3 = self.root / "d3-post-candidate-copy"
        _, copy, ok = self.copy_with_proof(self.d2, self.d3, "d2-candidate-working-copy-after-run", "d3-post-candidate-copy")
        self.m_post = copy
        delta = manifest_delta(self.m_pre, copy)
        write_json(self.out / "delta-pre-to-post-candidate.json", delta)
        self.delta = delta
        self.check("post-candidate byte copy equals the stopped candidate directory, and the source is unchanged", ok,
                   "tree_sha256=%s" % copy["tree_sha256"])
        if delta["new_file_kinds"]:
            self.flag("the candidate created file kinds the old state did not have (review each): %s" % delta["new_file_kinds"])
        if delta["vanished_file_kinds"]:
            self.flag("file kinds present before the candidate ran are gone after it: %s" % delta["vanished_file_kinds"])
        return self.finish(rec, ok, tree_sha256=copy["tree_sha256"], files=copy["file_count"], bytes=copy["total_bytes"],
                           added=len(delta["added"]), modified=len(delta["modified"]),
                           new_file_kinds=delta["new_file_kinds"], vanished_file_kinds=delta["vanished_file_kinds"])

    # ----- reopen machinery
    def expected_nodes(self, record, label="final"):
        return [expected_from_obs(n) for n in observation_by_label(record, label)["nodes"]]

    def reopen_set(self, label, data_dir, mode, nodes=None):
        """One isolated process per node, all started together, each in its own empty network namespace."""
        nodes = list(range(NODES)) if nodes is None else list(nodes)
        reopen_dir = self.out / "reopen" / label
        reopen_dir.mkdir(parents=True, exist_ok=True)
        sudo = (self.isolation_name or "").startswith("sudo")
        procs = []
        for index in nodes:
            spec = {
                "index": index, "mode": mode, "binary": str(self.old_bin),
                "data_dir": str(Path(data_dir) / ("node-%d" % index)),
                "genesis": str(self.root / "fixture" / "genesis.toml"),
                "activation": str(self.root / "fixture" / "activation.json"),
                "key_file": str(self.root / "fixture" / ("validator-%d.key.json" % index)),
                "native_runtime": self.native, "log": str(reopen_dir / ("node-%d.log" % index)),
                "start_timeout": self.start_timeout, "samples": 3, "sample_gap": self.sample_gap,
                "isolation_override": self.test_isolation_override,
                "drop_uid": os.getuid() if sudo else None, "drop_gid": os.getgid() if sudo else None,
            }
            spec_path = reopen_dir / ("spec-%d.json" % index)
            out_path = reopen_dir / ("result-%d.json" % index)
            write_json(spec_path, spec)
            command = list(self.isolation_prefix or []) + [sys.executable, str(Path(__file__).resolve()),
                                                          "probe-reopen", "--spec", str(spec_path), "--out", str(out_path)]
            procs.append((index, out_path, subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)))
        results = []
        for index, out_path, proc in procs:
            try:
                output, _ = proc.communicate(timeout=900)
            except subprocess.TimeoutExpired:
                proc.kill()
                output, _ = proc.communicate()
            (reopen_dir / ("probe-%d.out" % index)).write_bytes(output or b"")
            if out_path.exists():
                results.append(read_json(out_path))
            else:
                results.append({"index": index, "port": BASE_RPC + index, "started": False,
                                "start_error": "probe produced no result (exit %s)" % proc.returncode})
        scans = {}
        for index in nodes:
            path = reopen_dir / ("node-%d.log" % index)
            scans[BASE_RPC + index] = scan_log(path.read_text(errors="replace") if path.exists() else "")
        return results, scans

    def judged(self, label, data_dir, mode, expected, expect_sha, expect_version, baseline_scans=None, nodes=None):
        results, scans = self.reopen_set(label, data_dir, mode, nodes=nodes)
        wanted = [e for e in expected if nodes is None or (e["port"] - BASE_RPC) in nodes]
        verdict = judge_reopen(wanted, results, expect_sha, expect_version, mode == "observer", scans, baseline_scans)
        return results, scans, verdict

    def reopen_pair(self, name, mode, note):
        """The post-candidate reopen and its control on the pre-candidate copy, both by the OLD binary."""
        new_expected = self.expected_nodes(self.new_record)
        old_expected = self.expected_nodes(self.old_record)
        d_ctl = self.root / ("d4-control-" + name)
        d_post = self.root / ("d4-reopen-" + name)
        copy_tree(self.d1, d_ctl)
        copy_tree(self.d3, d_post)
        before = self.keep_manifest(build_manifest(d_post, "d4-reopen-%s-before" % name))
        # control: the old binary on the OLD state. Its own log is the baseline of what normal looks like here.
        ctl_results, ctl_scans, _ = self.judged("control-" + name, d_ctl, mode, old_expected, self.old_sha, OLD_VERSION)
        ctl_vs_old = judge_reopen(old_expected, ctl_results, self.old_sha, OLD_VERSION, mode == "observer", ctl_scans, ctl_scans)
        ctl_vs_new = judge_reopen(new_expected, ctl_results, self.old_sha, OLD_VERSION, mode == "observer", ctl_scans, ctl_scans)
        results, scans, verdict = self.judged("post-" + name, d_post, mode, new_expected, self.old_sha, OLD_VERSION,
                                              baseline_scans=ctl_scans)
        after = self.keep_manifest(build_manifest(d_post, "d4-reopen-%s-after" % name))
        moved = manifest_delta(before, after)
        signing_changed = [m["path"] for m in moved["modified"] if m["path"].endswith("consensus-signing-record.bin")]
        control_hard = sorted(set(sig for scan in ctl_scans.values() for sig in scan["hard_signatures"]))
        control_errors = sorted(set(sig for scan in ctl_scans.values() for sig in scan["error_signatures"]))
        if control_hard:
            self.flag("%s control (old binary on old state) already shows damage-class log lines: %s" % (name, control_hard[:3]))
        run = {
            "name": name, "mode": mode, "note": note, "verdict": verdict, "failed_checks": failed_checks(verdict),
            "control_vs_old_state_ok": ctl_vs_old["ok"], "control_vs_old_failed": failed_checks(ctl_vs_old),
            "control_fails_freshness": FRESHNESS in failed_checks(ctl_vs_new),
            "control_vs_candidate_failed": failed_checks(ctl_vs_new),
            "control_error_signatures": control_errors, "control_hard_signatures": control_hard,
            "files_modified_by_reopen": moved["modified"], "files_added_by_reopen": moved["added"],
            "signing_record_changed": signing_changed,
            "exit_codes": [r.get("exit_code") for r in results],
            "log_scans": {str(k): v for k, v in scans.items()},
            "control_log_scans": {str(k): v for k, v in ctl_scans.items()},
            "results_sha256": sha256_bytes(canonical(results)),
            "isolation_verified_per_node": [bool((r.get("isolation") or {}).get("isolated")) for r in results],
            "binary_reported_per_node": [((r.get("samples") or [{}])[-1].get("health") or {}).get("binary_sha256") for r in results],
            "chain_participation_per_node": [((r.get("samples") or [{}])[-1].get("health") or {}).get("chain_participation_enabled")
                                             for r in results],
        }
        write_json(self.out / "reopen" / ("evidence-%s.json" % name), run)
        self.reopen_runs[name] = run
        state_changed = [m["path"] for m in moved["modified"] if m["class"] == "state"] + \
                        [p for p in moved["added"] if classify(p) == "state"]
        if mode == "observer" and state_changed:
            self.flag("the observer reopen modified or added state files (review): %s" % state_changed[:6])
        return run

    def s06_isolation(self):
        self.isolation_name, self.isolation_prefix, self.isolation_evidence = pick_isolation()
        rec = self.begin("S06-isolation", method=self.isolation_name)
        ok = self.isolation_name is not None
        self.check("an empty network namespace (loopback only, no outbound route) was obtained for the reopen tests", ok,
                   "method=%s" % self.isolation_name)
        if not ok:
            self.caveats.append("no network-namespace isolation was available on this runner; 'networking: off' is NOT claimed")
        return self.finish(rec, ok, isolation_evidence=self.isolation_evidence)

    def s07_reopen_observer(self):
        rec = self.begin("S07-reopen-observer", mode="observer")
        run = self.reopen_pair("observer", "observer",
                               "v0.8.10, --stake 0, no validator key (no consensus engine, no signing), isolated empty network, "
                               "post-candidate copy; control on the pre-candidate copy")
        isolated = bool(self.isolation_name) and all(run["isolation_verified_per_node"])
        no_consensus = all(v is False for v in run["chain_participation_per_node"])
        self.check("observer reopen: all six nodes pass every state check", run["verdict"]["ok"], "failed: %s" % run["failed_checks"])
        self.check("observer reopen: the control (old binary, pre-candidate copy) is clean against its own expectations",
                   run["control_vs_old_state_ok"], "failed: %s" % run["control_vs_old_failed"])
        self.check("observer reopen: the control FAILS the candidate-freshness expectation (the test discriminates)",
                   run["control_fails_freshness"], "control vs candidate failed: %s" % run["control_vs_candidate_failed"])
        self.check("observer reopen: the signing record was not touched", not run["signing_record_changed"],
                   "changed: %s" % run["signing_record_changed"])
        self.check("observer reopen: every node ran in a verified empty network namespace", isolated,
                   "per node: %s" % run["isolation_verified_per_node"])
        self.check("observer reopen: no node ran a consensus engine (signing off)", no_consensus,
                   "chain_participation_enabled per node: %s" % run["chain_participation_per_node"])
        ok = (run["verdict"]["ok"] and run["control_vs_old_state_ok"] and run["control_fails_freshness"]
              and not run["signing_record_changed"] and isolated and no_consensus)
        return self.finish(rec, ok)

    def s08_reopen_validator(self):
        rec = self.begin("S08-reopen-validator-argv", mode="validator")
        run = self.reopen_pair("validator", "validator",
                               "v0.8.10, production validator argv (stake, key file, native flags in the native tier), "
                               "isolated empty network, no peers, post-candidate copy; control on the pre-candidate copy")
        isolated = bool(self.isolation_name) and all(run["isolation_verified_per_node"])
        self.check("validator-argv reopen: all six nodes pass every state check", run["verdict"]["ok"], "failed: %s" % run["failed_checks"])
        self.check("validator-argv reopen: the control is clean against its own expectations", run["control_vs_old_state_ok"],
                   "failed: %s" % run["control_vs_old_failed"])
        self.check("validator-argv reopen: the control FAILS the candidate-freshness expectation", run["control_fails_freshness"],
                   "control vs candidate failed: %s" % run["control_vs_candidate_failed"])
        self.check("validator-argv reopen: every node ran in a verified empty network namespace", isolated)
        if run["signing_record_changed"]:
            self.flag("the validator-argv reopen rewrote the signing record on: %s (a validator signs; informational)"
                      % run["signing_record_changed"])
        ok = run["verdict"]["ok"] and run["control_vs_old_state_ok"] and run["control_fails_freshness"] and isolated
        return self.finish(rec, ok)

    def s09_inspectors(self):
        rec = self.begin("S09-inspectors")
        notes = {}
        checkpoint = self.root / "fixture" / "approved.arcchkpt"
        run = subprocess.run([str(self.old_bin), "recovery", "inspect", "--checkpoint", str(checkpoint)],
                             capture_output=True, text=True, timeout=120)
        notes["recovery inspect --checkpoint (fixture checkpoint, old binary; informational)"] = {
            "exit_code": run.returncode, "stdout_head": run.stdout.strip()[:600], "stderr_head": run.stderr.strip()[:300]}
        node0 = Path(self.d3) / "node-0"
        legacy_files = [n for n in ("state.wal", "state.snapshot.lz4") if (node0 / n).exists()]
        wal_dirs = [p for p in (node0 / "dag-wal",) if p.is_dir()]
        notes["layout (post-candidate copy, node-0)"] = directory_listing(node0, 150)
        notes["inspect-legacy-block"] = {
            "applicable": bool(legacy_files),
            "reason": ("legacy state.wal and/or state.snapshot.lz4 present" if legacy_files else
                       "NOT APPLICABLE: the recovered-v3 layout has no legacy state.wal / state.snapshot.lz4 (listing above); "
                       "the inspector reads only an exact, stopped legacy WAL/snapshot pair pinned by expected digests")}
        if wal_dirs:
            run = subprocess.run([str(self.old_bin), "recovery", "inspect-legacy-dag-round", "--dag-wal-dir", str(wal_dirs[0])],
                                 capture_output=True, text=True, timeout=120)
            notes["inspect-legacy-dag-round"] = {
                "applicable": "attempted: a dag-wal directory exists in the recovered layout", "exit_code": run.returncode,
                "stdout_head": run.stdout.strip()[:600], "stderr_head": run.stderr.strip()[:300],
                "interpretation": "informational only: the inspector is for the legacy segmented WAL; its answer on the "
                                  "recovered layout's own dag-wal is not a state-compatibility result"}
        else:
            notes["inspect-legacy-dag-round"] = {"applicable": False, "reason": "no dag-wal directory in the recovered layout"}
        write_json(self.out / "reopen" / "inspectors.json", notes)
        self.digests["inspectors"] = sha256_bytes(canonical(notes))
        return self.finish(rec, True, notes=notes)

    def s10_resume(self):
        rec = self.begin("S10-resume", binary=str(self.old_bin))
        self.d5 = self.root / "d5-resume-working-copy"
        _, _, ok = self.copy_with_proof(self.d3, self.d5, "d3-post-candidate-copy-recheck", "d5-resume-working-copy-before-run")
        prev = [self.out / "observations" / "old_run.json", self.out / "observations" / "new_run.json"]
        rc, record, complete = self.run_step("resume", self.d5, self.old_bin, self.old_sha, prev, "resume")
        ok = ok and rc == 0 and complete
        reports = binary_reports_ok(record or {}, self.old_sha, "native-test-executor" if self.native else None)
        self.check("resume: every node reported the old binary's digest", reports["ok"], json.dumps(reports))
        ok = ok and reports["ok"]
        if record and complete:
            start = observation_by_label(record, "start")
            final = observation_by_label(record, "final")
            cand_final = observation_by_label(self.new_record, "final")
            seen = history_preserved(cand_final, start)
            kept = history_preserved(start, final)
            cand_h = [(c["health"] or {}).get("height") for c in cand_final["nodes"]]
            final_h = [(n["health"] or {}).get("height") for n in final["nodes"]]
            grew = all(isinstance(a, int) and isinstance(b, int) and b > a for a, b in zip(cand_h, final_h))
            self.check("resume: the old binary serves exactly the history the candidate extended", seen["ok"], json.dumps(seen))
            self.check("resume: the old binary extends it without rewriting", kept["ok"], json.dumps(kept))
            self.check("resume: the old binary committed new blocks on every node", grew, "heights %s -> %s" % (cand_h, final_h))
            ok = ok and seen["ok"] and kept["ok"] and grew
            fresh, equivocation = {}, {}
            for node_dir in sorted(Path(self.d5).glob("node-*")):
                mine = scan_log((node_dir / "node.log").read_text(errors="replace"))
                theirs_path = Path(self.d3) / node_dir.name / "node.log"
                theirs = scan_log(theirs_path.read_text(errors="replace")) if theirs_path.exists() else None
                fresh[node_dir.name] = new_signatures(mine, theirs)
                equivocation[node_dir.name] = [s for s in fresh[node_dir.name] if "equivocat" in s.lower() or "slash" in s.lower()]
            self.check("resume: no equivocation or slash message appeared in any log", not any(equivocation.values()),
                       json.dumps(equivocation, sort_keys=True))
            ok = ok and not any(equivocation.values())
            if any(fresh.values()):
                self.flag("resume: log signatures not seen in the candidate's logs (review): %s" % json.dumps(fresh, sort_keys=True)[:500])
            write_json(self.out / "reopen" / "resume-log-signatures.json", {"new_relative_to_post_candidate_logs": fresh})
        self.keep_manifest(build_manifest(self.d5, "d5-resume-working-copy-after-run"))
        return self.finish(rec, ok, exit_code=rc, complete=complete, start_reports=reports)

    def s11_negatives(self):
        rec = self.begin("S11-negative-controls")
        new_expected = self.expected_nodes(self.new_record)
        d_ref = self.root / "d6-negative-reference"
        copy_tree(self.d3, d_ref)
        ref_results, ref_scans = self.reopen_set("negative-reference", d_ref, "validator", nodes=[0])
        results = {}
        # (a) one flipped byte inside the largest WAL-like file of node 0's copy
        d_a = self.root / "d6-negative-a"
        copy_tree(self.d3, d_a)
        victim, size = None, 0
        for path in sorted((d_a / "node-0").rglob("*")):
            if path.is_file() and path.name != "node.log" and re.search(r"wal|record|snapshot|\.bin$", path.name) \
                    and path.stat().st_size > size:
                victim, size = path, path.stat().st_size
        flipped = None
        if victim is not None and size > 256:
            position = size // 3
            with open(str(victim), "r+b") as stream:
                stream.seek(position)
                byte = stream.read(1)
                stream.seek(position)
                stream.write(bytes([byte[0] ^ 0x01]))
            flipped = {"file": str(victim.relative_to(d_a)), "offset": position, "size": size}
        # (b) another validator's anti-equivocation record in node 0's copy
        d_b = self.root / "d6-negative-b"
        copy_tree(self.d3, d_b)
        src = d_b / "node-1" / "consensus-signing-record.bin"
        dst = d_b / "node-0" / "consensus-signing-record.bin"
        swapped = None
        if src.exists() and dst.exists() and sha256_file(src) != sha256_file(dst):
            shutil.copyfile(str(src), str(dst))
            swapped = {"from": "node-1", "to": "node-0"}
        for name, data_dir, damage in (("a-one-flipped-byte", d_a, flipped), ("b-swapped-signing-record", d_b, swapped)):
            if damage is None:
                results[name] = {"applied": False, "detected": None,
                                 "detail": "the damage could not be applied to this layout (no suitable file)"}
                continue
            res, scans, verdict = self.judged("negative-" + name, data_dir, "validator", new_expected, self.old_sha,
                                              OLD_VERSION, baseline_scans=ref_scans, nodes=[0])
            node = res[0] if res else {}
            detected = (not verdict["ok"]) or (not node.get("started")) or node.get("exit_code") != 0
            results[name] = {"applied": True, "damage": damage, "detected": bool(detected),
                             "failed_checks": failed_checks(verdict), "start_error": node.get("start_error"),
                             "exit_code": node.get("exit_code"),
                             "new_log_signatures": new_signatures(scans[BASE_RPC], ref_scans.get(BASE_RPC))[:5]}
        write_json(self.out / "reopen" / "negative-controls.json", results)
        for name, row in results.items():
            self.check("negative control %s: the damage is detected" % name, bool(row.get("detected")),
                       "applied=%s detected=%s" % (row.get("applied"), row.get("detected")))
        undetected = [n for n, r in results.items() if not r.get("detected")]
        if undetected:
            self.flag("negative control(s) %s were not detected: the lab's ability to see that kind of damage is not "
                      "demonstrated (the real reopen verdicts stand on their own checks)" % undetected)
        return self.finish(rec, True, results=results)

    def s12_pristine(self):
        rec = self.begin("S12-pristine")
        pre = build_manifest(self.d1, "d1-pre-candidate-copy-final")
        post = build_manifest(self.d3, "d3-post-candidate-copy-final")
        ok = manifests_equal(pre, self.m_pre) and manifests_equal(post, self.m_post)
        self.check("the pre- and post-candidate copies are byte-identical to their recorded manifests after every test", ok,
                   "pre=%s post=%s" % (pre["tree_sha256"], post["tree_sha256"]))
        return self.finish(rec, ok, pre_tree_sha256=pre["tree_sha256"], post_tree_sha256=post["tree_sha256"])

    # ----- driver
    def call(self, step):
        try:
            result = step()
            return result is not False
        except Exception as exc:  # recorded, never swallowed
            log("%s: %s raised %r" % (self.tier, step.__name__, exc))
            if self.steps and self.steps[-1].get("status") == "running":
                self.finish(self.steps[-1], False, error=repr(exc))
            else:
                self.steps.append({"step": step.__name__, "status": "fail", "error": repr(exc)})
            self.check("%s completed without an error" % step.__name__, False, repr(exc))
            return False

    def archive_copies(self):
        for label, path in (("pre-candidate", self.d1), ("post-candidate", self.d3)):
            size = sum(f.stat().st_size for f in Path(path).rglob("*") if f.is_file())
            if size <= 150 * 1024 * 1024:
                target = self.out / "copies" / (label + "-copy.tar.gz")
                target.parent.mkdir(parents=True, exist_ok=True)
                with tarfile.open(str(target), "w:gz") as tar:
                    tar.add(str(path), arcname=label + "-copy")
                self.digests["archive:" + label] = sha256_file(target)
            else:
                self.caveats.append("the %s copy is %d bytes and was not archived into the evidence artifact" % (label, size))

    def run(self):
        foundation = [self.s00_binaries, self.s01_fixture, self.s02_old_run, self.s03_copy_pre, self.s04_candidate, self.s05_copy_post]
        later = [self.s06_isolation, self.s07_reopen_observer, self.s08_reopen_validator, self.s09_inspectors,
                 self.s10_resume, self.s11_negatives, self.s12_pristine]
        halted = None
        for step in foundation:
            if not self.call(step):
                halted = step.__name__
                break
        if halted is None:
            for step in later:
                self.call(step)
            try:
                self.archive_copies()
            except Exception as exc:
                self.caveats.append("could not archive the copies: %r" % exc)
        else:
            skipped = foundation[foundation.index(getattr(self, halted)) + 1:] + later
            for step in skipped:
                self.steps.append({"step": step.__name__, "status": "skipped", "reason": "foundation step %s failed" % halted})
        return self.result()

    def result(self):
        gating = [name for name, row in self.checks.items() if not name.startswith("negative control")]
        failing = [name for name in gating if not self.checks[name]["ok"]]
        incomplete = [s["step"] for s in self.steps if s.get("status") in ("skipped", "running")]
        failed_steps = [s["step"] for s in self.steps if s.get("status") == "fail"]
        verdict = "pass" if not failing and not incomplete and not failed_steps else "fail"
        result = {
            "schema": SCHEMA_TIER, "tier": self.tier, "verdict": verdict, "failing_checks": failing,
            "failed_steps": failed_steps, "incomplete_steps": incomplete, "checks": self.checks, "flags": self.flags,
            "steps": self.steps, "digests": self.digests, "caveats": self.caveats,
            "not_reproduced": tier_not_reproduced(self.tier),
            "binaries": self.binaries,
            "isolation": {"method": self.isolation_name, "evidence": self.isolation_evidence},
            "fixture": self.fixture_meta, "extra_node_args": self.extra,
            "test_override_used": bool(self.test_isolation_override),
            "environment": {"python": sys.version.split()[0], "platform": sys.platform,
                            "uname": " ".join(os.uname()) if hasattr(os, "uname") else "",
                            "image": {k: os.environ.get(k) for k in ("ImageOS", "ImageVersion")}},
            "finished": now(),
        }
        reopen = {"schema": SCHEMA_REOPEN, "tier": self.tier, "verdict": verdict,
                  "runs": self.reopen_runs, "isolation": result["isolation"],
                  "delta_file": "delta-pre-to-post-candidate.json",
                  "manifest_digests": self.digests}
        write_json(self.out / "reopen-evidence.json", reopen)
        result["reopen_evidence_sha256"] = sha256_file(self.out / "reopen-evidence.json")
        write_json(self.out / "tier-result.json", result)
        return result


def tier_not_reproduced(tier):
    common = [
        "production-sized state (the lab chain has a few hundred blocks; production has far more history and larger stores)",
        "the real 7B model, shard/row-owner topology and real native runtime flags (--model, --native-inference-artifact, "
        "--native-inference-qualification, --native-package-manifest, --native-row-workers, --native-low-residency, "
        "--native-kv-budget-bytes): they need the real model and packages",
        "real network latencies and the fleet's CPU architecture/OS image (the lab uses one GitHub-hosted x86_64 runner)",
        "the production chain's own history (lineage): the fixture is a freshly generated six-validator recovered chain",
        "a rolling, one-validator-at-a-time rollback: the resume test restarts all six together",
    ]
    if tier == "native":
        common.append("native results are bound to the SOURCES (lab builds with the deterministic test executor), "
                      "not to the deployed binary bytes; build_identity::features() reports native-test-executor")
    else:
        common.append("native-inference lifecycle (paid requests, receipts, settlements, refunds): not exercisable with "
                      "production-feature binaries (no test executor); see the native tier")
    return common


def cmd_run_tier(args):
    runner = TierRunner(args)
    result = runner.run()
    log("%s tier verdict: %s (failing: %s)" % (args.tier, result["verdict"], result["failing_checks"]))
    return 0 if result["verdict"] == "pass" else 1


# ------------------------------------------------------ production binaries ----

PROD_OLD_SHA256 = "1fd253cd09520549534bb8b3be64b81022f4adcf66c24884967c621305097724"
PROD_NEW_SHA256 = "54d4d0708ae41d32958110cce9961851911c9b72ca269756cd49dfbc731e061b"
PROD_ZIP_SHA256 = "db1b4d9f399808a7ab3cf2a1a41a148dae6abf6e432c112bf6fa55fb9cf76d60"
PROD_ARCHIVE_SHA256 = "0cb6c5b2f2cac5c7c5aca3ed22fc430a2b30948b17d6cdb00860fdb407341f06"
PROD_ARTIFACT_ID = "11471705295"
PROD_BUILD_JOB_ID = "112708205184"
PROD_PREFLIGHT_RUN = "37595837809"


def gh(*argv, capture=True, stdout=None):
    result = subprocess.run(["gh"] + list(argv), capture_output=capture and stdout is None, stdout=stdout,
                            text=stdout is None, timeout=600)
    need(result.returncode == 0, "gh %s failed: %s" % (" ".join(argv[:3]), (result.stderr or "")[:200] if capture and stdout is None else ""))
    return result.stdout if stdout is None else None


def cmd_fetch_production(args):
    """The deployed v0.8.10 binary and the preflight-built v0.8.11 candidate, each bound by digest chain."""
    out = Path(args.out)
    (out / "old").mkdir(parents=True, exist_ok=True)
    (out / "new").mkdir(parents=True, exist_ok=True)
    report = {"schema": "arc.statecompat-lab.production-binaries.v1", "checks": []}

    def check(name, ok, detail=""):
        report["checks"].append({"check": name, "ok": bool(ok), "detail": detail})
        need(ok, "%s: %s" % (name, detail))

    # --- baseline: the immutable v0.8.10 release asset
    release = json.loads(gh("api", "repos/%s/releases/tags/v0.8.10" % REPOSITORY))
    asset = [a for a in release["assets"] if a["name"] == "arc-node-linux-x86_64"]
    check("release asset exists once", len(asset) == 1)
    gh("release", "download", "v0.8.10", "-R", REPOSITORY, "-p", "arc-node-linux-x86_64", "-p", "SHA256SUMS",
       "-D", str(out / "old"), "--clobber")
    old_path = out / "old" / "arc-node-linux-x86_64"
    digest = sha256_file(old_path)
    check("v0.8.10 asset sha256 equals the pinned production digest", digest == PROD_OLD_SHA256, digest)
    check("...and the release API digest", asset[0].get("digest") == "sha256:" + digest, str(asset[0].get("digest")))
    sums = (out / "old" / "SHA256SUMS").read_text()
    check("...and the release's SHA256SUMS entry", re.search(r"^%s\s+\*?arc-node-linux-x86_64\s*$" % digest, sums, re.M) is not None)
    os.chmod(str(old_path), 0o755)
    report["old"] = {"path": str(old_path), "sha256": digest, "size": old_path.stat().st_size,
                     "source": "GitHub release v0.8.10 asset arc-node-linux-x86_64 (tag v0.8.10 = %s)" % BASELINE_SHA,
                     "release_immutable": release.get("immutable")}
    # --- candidate: the pre-tag artifact of preflight run 37595837809
    zip_path = out / "new" / "artifact.zip"
    with open(str(zip_path), "wb") as stream:
        gh("api", "repos/%s/actions/artifacts/%s/zip" % (REPOSITORY, PROD_ARTIFACT_ID), capture=False, stdout=stream)
    check("artifact zip sha256 equals the pinned digest", sha256_file(zip_path) == PROD_ZIP_SHA256, sha256_file(zip_path))
    with zipfile.ZipFile(str(zip_path)) as archive:
        names = sorted(archive.namelist())
        check("zip members are exactly SHA256SUMS and one tar.gz", len(names) == 2 and "SHA256SUMS" in names, str(names))
        tar_name = [n for n in names if n.endswith(".tar.gz")][0]
        check("tar name carries the exact source and run",
              tar_name == "arc-pretag-headless-linux-x86_64-%s-%s-1.tar.gz" % (SOURCE_SHA, PROD_PREFLIGHT_RUN), tar_name)
        tar_bytes = archive.read(tar_name)
        sums_text = archive.read("SHA256SUMS").decode()
    check("inner archive sha256 equals the pinned digest", sha256_bytes(tar_bytes) == PROD_ARCHIVE_SHA256, sha256_bytes(tar_bytes))
    check("...and the SHA256SUMS line", PROD_ARCHIVE_SHA256 in sums_text and ("commit=" + SOURCE_SHA) in sums_text)
    import io
    with tarfile.open(fileobj=io.BytesIO(tar_bytes), mode="r:gz") as tar:
        members = {m.name: m for m in tar.getmembers()}
        check("tar members are the three payload files and BUILD-METADATA.json",
              sorted(members) == ["BUILD-METADATA.json", "arc-cli-linux-x86_64", "arc-node-linux-x86_64", "genesis.toml"], str(sorted(members)))
        check("all members are regular files", all(m.isreg() for m in members.values()))
        metadata = json.loads(tar.extractfile("BUILD-METADATA.json").read())
        new_path = out / "new" / "arc-node-linux-x86_64"
        digest_new = hashlib.sha256()
        total = 0
        with open(str(new_path), "wb") as stream:
            source = tar.extractfile("arc-node-linux-x86_64")
            for block in iter(lambda: source.read(1024 * 1024), b""):
                total += len(block)
                need(total <= 256 * 1024 * 1024, "binary larger than the cap")
                digest_new.update(block)
                stream.write(block)
    check("BUILD-METADATA names the exact source commit, run and version",
          metadata.get("commit") == SOURCE_SHA and str(metadata.get("workflow_run_id")) == PROD_PREFLIGHT_RUN
          and metadata.get("version") == NEW_VERSION and metadata.get("repository") == REPOSITORY, json.dumps(metadata, sort_keys=True))
    check("BUILD-METADATA's recorded arc-node hash equals the extracted bytes",
          metadata["files"]["arc-node-linux-x86_64"] == digest_new.hexdigest(), digest_new.hexdigest())
    check("...and the pinned candidate digest", digest_new.hexdigest() == PROD_NEW_SHA256, digest_new.hexdigest())
    os.chmod(str(new_path), 0o755)
    report["new"] = {"path": str(new_path), "sha256": digest_new.hexdigest(), "size": total,
                     "source": "pre-tag artifact %s of preflight run %s (job %s)" % (PROD_ARTIFACT_ID, PROD_PREFLIGHT_RUN, PROD_BUILD_JOB_ID),
                     "zip_sha256": PROD_ZIP_SHA256, "archive_sha256": PROD_ARCHIVE_SHA256, "build_metadata": metadata}
    write_json(out / "prod-binaries.json", report)
    log("production binaries fetched and verified: old %s new %s" % (report["old"]["sha256"][:12], report["new"]["sha256"][:12]))
    return 0


def cmd_build_record(args):
    rows = []
    for spec in args.binary:
        name, path = spec.split("=", 1)
        rows.append({"name": name, "path": path, "sha256": sha256_file(path), "size": os.path.getsize(path),
                     "version_line": binary_version_line(path)})

    def tool(*argv):
        try:
            return subprocess.run(list(argv), capture_output=True, text=True, timeout=60).stdout.strip()
        except (OSError, subprocess.SubprocessError):
            return ""

    record = {"schema": "arc.statecompat-lab.build-record.v1", "label": args.label, "source_sha": args.source_sha,
              "source_tree": args.source_tree, "binaries": rows, "build_commands": args.build_commands,
              "rustc": tool("rustc", "-Vv"), "cargo": tool("cargo", "-V"), "uname": tool("uname", "-a"),
              "image": {k: os.environ.get(k) for k in ("ImageOS", "ImageVersion")}, "finished": now()}
    write_json(args.out, record)
    return 0


def cmd_record_sha(args):
    record = read_json(args.record)
    rows = [b for b in record["binaries"] if b["name"] == args.name]
    need(len(rows) == 1, "no unique binary named %s in %s" % (args.name, args.record))
    print(rows[0]["sha256"])
    return 0


# ------------------------------------------------------------------ assemble --

def cmd_assemble(args):
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    summary = {"schema": SCHEMA_SUMMARY, "candidate_source_sha": SOURCE_SHA, "baseline_source_sha": BASELINE_SHA,
               "ci": {k: os.environ.get(k) for k in ("GITHUB_REPOSITORY", "GITHUB_RUN_ID", "GITHUB_RUN_ATTEMPT", "GITHUB_SHA",
                                                      "GITHUB_REF", "GITHUB_WORKFLOW", "ImageOS", "ImageVersion")},
               "tiers": {}, "lab_builds": {}, "created": now()}
    run_id = os.environ.get("GITHUB_RUN_ID")
    if run_id:
        summary["ci"]["run_url"] = "https://github.com/%s/actions/runs/%s" % (os.environ.get("GITHUB_REPOSITORY", REPOSITORY), run_id)
    if args.prod_binaries and Path(args.prod_binaries).exists():
        summary["production_binaries"] = read_json(args.prod_binaries)
    for path in args.build_record or []:
        if Path(path).exists():
            record = read_json(path)
            summary["lab_builds"][record["label"]] = record
    # reproducibility: release-flag lab builds against the deployed bytes
    repro = {}
    for label, prod_key in (("baseline-release-flags", "old"), ("candidate-release-flags", "new")):
        build = summary["lab_builds"].get(label.split("-")[0])
        prod = (summary.get("production_binaries") or {}).get(prod_key)
        if build and prod:
            row = [b for b in build["binaries"] if b["name"] == "release-flags"]
            if row:
                repro[label] = {"lab_sha256": row[0]["sha256"], "production_sha256": prod["sha256"],
                                "bit_identical": row[0]["sha256"] == prod["sha256"]}
    summary["reproducibility"] = repro
    for tier_dir in args.tier_dir or []:
        tier_dir = Path(tier_dir)
        result_path = tier_dir / "tier-result.json"
        if not result_path.exists():
            continue
        result = read_json(result_path)
        summary["tiers"][result["tier"]] = {
            "verdict": result["verdict"], "failing_checks": result["failing_checks"],
            "tier_result_sha256": sha256_file(result_path), "dir": tier_dir.name,
            "reopen_observer_evidence_sha256": sha256_file(tier_dir / "reopen" / "evidence-observer.json")
            if (tier_dir / "reopen" / "evidence-observer.json").exists() else None,
            "reopen_validator_evidence_sha256": sha256_file(tier_dir / "reopen" / "evidence-validator.json")
            if (tier_dir / "reopen" / "evidence-validator.json").exists() else None,
            "caveats": result["caveats"], "not_reproduced": result["not_reproduced"],
            "isolation_method": (result.get("isolation") or {}).get("method"),
        }
    verdicts = [t["verdict"] for t in summary["tiers"].values()]
    summary["verdict"] = "pass" if verdicts and all(v == "pass" for v in verdicts) and len(verdicts) == 2 else (
        "fail" if "fail" in verdicts else "incomplete")
    files = {}
    for root in [Path(p) for p in (args.tier_dir or [])] + [Path(p).parent for p in (args.build_record or []) if Path(p).exists()]:
        for path in sorted(root.rglob("*")):
            if path.is_file():
                files[str(path.relative_to(root.parent))] = sha256_file(path)
    summary["files"] = files
    write_json(out / "lab-summary.json", summary)
    digest = sha256_file(out / "lab-summary.json")
    (out / "lab-summary.sha256").write_text("%s  lab-summary.json\n" % digest)
    log("summary verdict: %s; lab-summary.json sha256 %s" % (summary["verdict"], digest))
    return 0 if summary["verdict"] == "pass" else 1


# ------------------------------------------------------------------ selftest ---

def cmd_selftest(_args):
    here = Path(__file__).resolve().parent
    suite = unittest.defaultTestLoader.discover(str(here), pattern="test_statecompat_lab.py")
    result = unittest.TextTestRunner(verbosity=2).run(suite)
    return 0 if result.wasSuccessful() else 1


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("selftest").set_defaults(func=cmd_selftest)
    sub.add_parser("isolation-check").set_defaults(func=cmd_isolation_check)
    p = sub.add_parser("fetch-production")
    p.add_argument("--out", required=True)
    p.set_defaults(func=cmd_fetch_production)
    p = sub.add_parser("build-record")
    p.add_argument("--label", required=True)
    p.add_argument("--source-sha", required=True)
    p.add_argument("--source-tree", default="")
    p.add_argument("--binary", action="append", required=True, help="NAME=PATH")
    p.add_argument("--build-command", dest="build_commands", action="append", default=[])
    p.add_argument("--out", required=True)
    p.set_defaults(func=cmd_build_record)
    p = sub.add_parser("record-sha")
    p.add_argument("--record", required=True)
    p.add_argument("--name", required=True)
    p.set_defaults(func=cmd_record_sha)
    p = sub.add_parser("run-tier")
    p.add_argument("--tier", choices=("prod", "native"), required=True)
    p.add_argument("--harness", required=True)
    p.add_argument("--old-bin", required=True)
    p.add_argument("--new-bin", required=True)
    p.add_argument("--old-sha", required=True)
    p.add_argument("--new-sha", required=True)
    p.add_argument("--work", required=True)
    p.add_argument("--out", required=True)
    p.add_argument("--step-timeout", type=int, default=1500)
    p.set_defaults(func=cmd_run_tier)
    p = sub.add_parser("probe-reopen")
    p.add_argument("--spec", required=True)
    p.add_argument("--out", required=True)
    p.set_defaults(func=cmd_probe_reopen)
    p = sub.add_parser("assemble")
    p.add_argument("--out", required=True)
    p.add_argument("--tier-dir", action="append")
    p.add_argument("--build-record", action="append")
    p.add_argument("--prod-binaries")
    p.set_defaults(func=cmd_assemble)
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
