//! STATECOMPAT old-binary-reopen lab harness (v0.8.11 release lab).
//!
//! THROWAWAY BRANCH ONLY. This file exists on `statecompat-v0811-lab` and is
//! never merged. It does not change any product code.
//!
//! It drives real `arc-node` processes on the repository's own six-validator
//! recovered-v3 fixture (the one `native_multivalidator_paid_flow.rs` builds:
//! a signed ARCCHKPT checkpoint, five of six signatures, 6_666_667/6_666_666
//! stakes, `--snapshot-every-blocks 50`, `--validator-key-file`), but selects
//! the `arc-node` binary PER STEP from the environment, so that one data
//! directory can be produced by v0.8.10, extended by the v0.8.11 candidate and
//! reopened by v0.8.10 again. The existing test hard-codes
//! `CARGO_BIN_EXE_arc-node`, which cannot express that.
//!
//! Everything here is disposable lab data: validator keys, requester keys,
//! checkpoint signatures and genesis are generated by this file for this run
//! and no real network, key, address or state is read. Key material is never
//! printed. The Python driver (lab/statecompat/statecompat_lab.py) copies,
//! digests, isolates and judges; this file only runs nodes and records what
//! the nodes themselves report.
//!
//! One test function dispatches on environment variables:
//!   LAB_STEP   fixture | old_run | new_run | resume
//!   LAB_TIER   prod (no native runtime: production flag set) | native
//!              (native runtime with the deterministic test executor)
//!   LAB_ROOT   directory holding `fixture/`
//!   LAB_DATA   directory holding node-0 .. node-5 data directories
//!   LAB_BIN    arc-node binary for this step
//!   LAB_OUT    observation JSON written here (progressively; "complete")
//!   LAB_PREV   previous step's observation JSON (new_run / resume)
//!   LAB_EXPECT_SHA256  expected sha256 of LAB_BIN (nodes must report it)
//!   LAB_EXTRA_ARGS     extra node arguments, whitespace separated
//! Without LAB_STEP the test does nothing, so an ordinary `cargo test` is inert.

use arc_crypto::signature::KeyPair;
use arc_crypto::{Hash256, hash_bytes};
use arc_types::inference_contract::{
    INFERENCE_CONTRACT_VERSION, InferenceDomain, InferenceJob, InferenceRequest,
};
use arc_types::transaction::{NativeInferenceRequestBody, Transaction, TxBody};
use serde_json::{Value, json};
use std::path::{Path, PathBuf};
use std::process::{Child, Command};
use std::time::{Duration, Instant};

const NODES: usize = 6;
const BASE_RPC: u16 = 9980;
const BASE_P2P: u16 = 9180;
const STAKES: [u64; NODES] = [
    6_666_667, 6_666_667, 6_666_667, 6_666_667, 6_666_666, 6_666_666,
];
const SCHEMA: &str = "arc.statecompat-lab.observation.v1";

// ---------------------------------------------------------------- helpers ----
// (curl / get_json / submit / wait_for are the helpers of the existing
// native_multivalidator_paid_flow.rs, unchanged apart from the Value type.)

fn validator_keypair(seed: &str) -> KeyPair {
    let bytes = blake3::derive_key("ARC-chain-validator-keypair-v1", seed.as_bytes());
    KeyPair::Ed25519(ed25519_dalek::SigningKey::from_bytes(&bytes))
}

fn requester_keypair(seed: &str) -> KeyPair {
    let bytes = blake3::derive_key(
        "ARC-native-multivalidator-test-requester-v1",
        seed.as_bytes(),
    );
    KeyPair::Ed25519(ed25519_dalek::SigningKey::from_bytes(&bytes))
}

fn curl(args: &[&str]) -> (u32, String) {
    let out = Command::new("curl")
        .args(["-s", "-w", "\n%{http_code}", "--max-time", "10"])
        .args(args)
        .output()
        .expect("curl must be available");
    let body = String::from_utf8_lossy(&out.stdout).to_string();
    let (body, code) = body.rsplit_once('\n').unwrap_or((body.as_str(), "0"));
    (code.trim().parse().unwrap_or(0), body.to_string())
}

fn get_json(port: u16, path: &str) -> Option<Value> {
    let (code, body) = curl(&[&format!("http://127.0.0.1:{port}{path}")]);
    (code == 200)
        .then(|| serde_json::from_str(&body).ok())
        .flatten()
}

fn submit(port: u16, tx: &Transaction) -> (u32, String) {
    let payload = serde_json::to_string(tx).unwrap();
    curl(&[
        "-X",
        "POST",
        "-H",
        "Content-Type: application/json",
        "-d",
        &payload,
        &format!("http://127.0.0.1:{port}/tx/submit_signed"),
    ])
}

fn wait_for<F: FnMut() -> bool>(timeout: Duration, label: &str, mut f: F) {
    let start = Instant::now();
    while start.elapsed() < timeout {
        if f() {
            return;
        }
        std::thread::sleep(Duration::from_millis(500));
    }
    panic!("timed out after {timeout:?} waiting for: {label}");
}

fn env_required(name: &str) -> String {
    std::env::var(name).unwrap_or_else(|_| panic!("{name} must be set"))
}

fn env_path(name: &str) -> PathBuf {
    PathBuf::from(env_required(name))
}

fn now_unix() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_secs()
}

/// A fresh chain-run identity for every execution (as in the existing test).
fn chain_instance_id() -> String {
    format!(
        "{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    )
}

// --------------------------------------------------------------- processes ----

struct NodeProcess {
    child: Child,
    port: u16,
}

impl Drop for NodeProcess {
    fn drop(&mut self) {
        let _ = self.child.kill();
        let _ = self.child.wait();
    }
}

/// Send every TERM first, then wait: a stopped validator may be the next
/// required leader, so serial stop-and-wait must not masquerade as progress.
/// Returns each node's exit record; the caller decides what is acceptable.
fn stop_nodes(nodes: &mut [NodeProcess]) -> Vec<Value> {
    for node in nodes.iter() {
        let _ = Command::new("kill")
            .args(["-TERM", &node.child.id().to_string()])
            .status();
    }
    let deadline = Instant::now() + Duration::from_secs(60);
    let mut codes = Vec::new();
    for node in nodes.iter_mut() {
        loop {
            if let Some(status) = node.child.try_wait().unwrap() {
                codes.push(json!({
                    "port": node.port,
                    "success": status.success(),
                    "status": status.to_string(),
                }));
                break;
            }
            assert!(
                Instant::now() < deadline,
                "validator {} did not stop durably within 60 s of SIGTERM",
                node.port
            );
            std::thread::sleep(Duration::from_millis(50));
        }
    }
    codes
}

fn heights(nodes: &[NodeProcess]) -> Vec<Option<u64>> {
    nodes
        .iter()
        .map(|n| get_json(n.port, "/health").and_then(|h| h["height"].as_u64()))
        .collect()
}

fn recovered_account(port: u16, who: Hash256) -> arc_types::Account {
    serde_json::from_value(
        get_json(port, &format!("/account/{}", who.to_hex())).expect("account RPC"),
    )
    .unwrap()
}

/// No StateDB execution in this helper: the only writer is the real node's
/// DAG loop. Every replica must publish the same successful canonical receipt
/// and v3 header, with an actual nonzero DAG decision commitment.
fn recovered_commit(nodes: &[NodeProcess], tx: Hash256, native: bool, phase: &str) -> u64 {
    let label = format!(
        "{phase}: transaction {} committed on all recovered validators",
        tx.to_hex()
    );
    eprintln!("Waiting for {label}");
    wait_for(Duration::from_secs(90), &label, || {
        nodes.iter().all(|n| {
            get_json(n.port, &format!("/tx/{}", tx.to_hex())).is_some_and(|r| r["success"] == true)
        })
    });
    let reference = get_json(nodes[0].port, &format!("/tx/{}", tx.to_hex())).unwrap();
    let height = reference["block_height"].as_u64().unwrap();
    let reference_block = get_json(nodes[0].port, &format!("/block/{height}")).unwrap();
    let block: arc_types::Block = serde_json::from_value(reference_block.clone()).unwrap();
    assert_eq!(block.header.protocol_version.major, 3);
    assert_ne!(
        block.header.proof_hash,
        Hash256::ZERO,
        "must commit through actual recovered DAG"
    );
    assert!(block.tx_hashes.contains(&tx));
    if native {
        assert_eq!(
            block.header.tx_count, 1,
            "native transition gets an isolated state block"
        );
    }
    for node in nodes {
        assert_eq!(
            get_json(node.port, &format!("/tx/{}", tx.to_hex())).unwrap(),
            reference
        );
        assert_eq!(
            get_json(node.port, &format!("/block/{height}")).unwrap(),
            reference_block,
            "recovered replicas disagree on header/root/body"
        );
    }
    eprintln!(
        "Completed {phase}: transaction {} at height {height}",
        tx.to_hex()
    );
    height
}

fn wait_recovered_peers(nodes: &[NodeProcess], phase: &str) {
    wait_for(
        Duration::from_secs(90),
        &format!("six recovered validators fully connected: {phase}"),
        || {
            nodes
                .iter()
                .all(|n| get_json(n.port, "/health").and_then(|h| h["peers"].as_u64()) == Some(5))
        },
    );
}

/// The receipt fields that must be identical on every replica.
fn settlement(port: u16, request_id: Hash256) -> Option<(String, u64, String, Vec<(String, u64)>)> {
    let r = get_json(
        port,
        &format!("/native-inference/receipt/{}", request_id.to_hex()),
    )?;
    let status = r["observed_status"].as_str()?.to_string();
    let height = r["terminal_transaction"]["block_height"]
        .as_u64()
        .unwrap_or(0);
    let output = r["output_hash"].as_str().unwrap_or("").to_string();
    let mut credits: Vec<(String, u64)> = r["settlement_credits"]
        .as_array()
        .map(|c| {
            c.iter()
                .map(|x| {
                    (
                        x["payee"].as_str().unwrap_or("").to_string(),
                        x["amount"].as_u64().unwrap_or(0),
                    )
                })
                .collect()
        })
        .unwrap_or_default();
    credits.sort();
    Some((status, height, output, credits))
}

fn wait_finalized(nodes: &[&NodeProcess], id: Hash256, timeout: Duration, label: &str) {
    wait_for(timeout, label, || {
        nodes
            .iter()
            .all(|n| settlement(n.port, id).is_some_and(|(status, ..)| status == "Finalized"))
    });
}

/// Each node publishes the SHA-256 of its own executable (hashed in the
/// background after start). Wait for it, require it to equal the expected
/// digest when one is given, and return what every node reported.
fn wait_binary_digest(nodes: &[NodeProcess], expected: Option<&str>) -> Vec<Value> {
    wait_for(
        Duration::from_secs(180),
        "every node publishes the digest of its own executable",
        || {
            nodes.iter().all(|n| {
                get_json(n.port, "/health").is_some_and(|h| h["binary_sha256"].is_string())
            })
        },
    );
    let mut reported = Vec::new();
    for node in nodes {
        let health = get_json(node.port, "/health").unwrap();
        let digest = health["binary_sha256"].as_str().unwrap().to_string();
        if let Some(expected) = expected {
            assert_eq!(
                digest, expected,
                "node on port {} is not running the expected binary",
                node.port
            );
        }
        reported.push(json!({
            "port": node.port,
            "binary_sha256": digest,
            "features": health["features"],
            "version": health["version"],
        }));
    }
    reported
}

fn wait_activation(nodes: &[NodeProcess]) {
    wait_for(
        Duration::from_secs(300),
        "DAG reaches coordinated native activation with admission closed",
        || {
            nodes.iter().all(|n| {
                get_json(n.port, "/native-inference/context").is_some_and(|ctx| {
                    ctx["chain_protocol"] == 3
                        && ctx["native_only_chain"] == false
                        && ctx["request_admission_open"] == false
                        && ctx["request_admission"]["operator_enabled"] == false
                        && ctx["request_admission"]["runtime_ready"] == false
                })
            })
        },
    );
}

fn wait_runtime_ready(nodes: &[NodeProcess], node0_ingress: bool) {
    wait_for(
        Duration::from_secs(90),
        "every native runtime live, ingress as configured",
        || {
            nodes.iter().enumerate().all(|(i, n)| {
                get_json(n.port, "/native-inference/context").is_some_and(|ctx| {
                    ctx["request_admission"]["runtime_ready"] == true
                        && ctx["request_admission_open"] == (node0_ingress && i == 0)
                        && ctx["chain_protocol"] == 3
                        && ctx["native_only_chain"] == false
                })
            })
        },
    );
}

fn domain_from_context(node: &NodeProcess) -> InferenceDomain {
    let ctx = get_json(node.port, "/native-inference/context").unwrap();
    InferenceDomain {
        chain_genesis: Hash256::from_hex(ctx["chain_genesis"].as_str().unwrap()).unwrap(),
        recovery_epoch: ctx["recovery_epoch"].as_u64().unwrap(),
        validator_set_hash: Hash256::from_hex(ctx["validator_set_hash"].as_str().unwrap()).unwrap(),
    }
}

/// Every node must reach a height past the next snapshot boundary
/// (`--snapshot-every-blocks 50`) and at least `min_extra` blocks further.
fn advance_past_snapshot(nodes: &[NodeProcess], min_extra: u64, label: &str) -> u64 {
    let start = heights(nodes).into_iter().flatten().max().unwrap();
    let boundary = (start / 50 + 1) * 50;
    let target = (start + min_extra).max(boundary + 10);
    wait_for(
        Duration::from_secs(420),
        &format!("{label}: every node reaches height {target}"),
        || {
            heights(nodes)
                .iter()
                .all(|h| h.is_some_and(|h| h >= target))
        },
    );
    target
}

// --------------------------------------------------------------- observation ----

/// What one node reports about itself: health (with its executable digest and
/// compiled features), chain identity, the live state root, and every block
/// it can serve (hash, state root, parent, tx count) from 0 to its tip.
fn observe_port(port: u16) -> Value {
    let health = get_json(port, "/health").unwrap_or(Value::Null);
    let info = get_json(port, "/network/info").unwrap_or(Value::Null);
    let snapshot = get_json(port, "/sync/snapshot/info").unwrap_or(Value::Null);
    let tip = info["last_block_height"].as_u64();
    let mut blocks = Vec::new();
    if let Some(tip) = tip {
        for h in 0..=tip {
            match get_json(port, &format!("/block/{h}")) {
                Some(b) => blocks.push(json!({
                    "h": h,
                    "hash": b["hash"],
                    "state_root": b["header"]["state_root"],
                    "parent_hash": b["header"]["parent_hash"],
                    "tx_count": b["header"]["tx_count"],
                    "protocol_major": b["header"]["protocol_version"]["major"],
                })),
                None => blocks.push(json!({ "h": h, "missing": true })),
            }
        }
    }
    json!({
        "port": port,
        "health": health,
        "network_info": info,
        "snapshot_info": snapshot,
        "blocks": blocks,
    })
}

fn observe(nodes: &[NodeProcess], label: &str) -> Value {
    let ports: Vec<u16> = nodes.iter().map(|n| n.port).collect();
    let observed: Vec<Value> = std::thread::scope(|scope| {
        let handles: Vec<_> = ports
            .iter()
            .map(|port| {
                let port = *port;
                scope.spawn(move || observe_port(port))
            })
            .collect();
        handles
            .into_iter()
            .map(|handle| handle.join().unwrap())
            .collect()
    });
    json!({
        "label": label,
        "unix": now_unix(),
        "nodes": observed,
    })
}

// ------------------------------------------------------------------- fixture ----

struct Lab {
    dir: PathBuf,
    checkpoint: PathBuf,
    genesis: PathBuf,
    activation: PathBuf,
    manifest: Hash256,
    transaction_domain: Hash256,
    activation_height: u64,
    /// Two requesters: ingress admits only the nonce valid at the next
    /// height, so two native requests can share a DAG block only when they
    /// come from different accounts.
    requesters: [KeyPair; 2],
    tuple: [Hash256; 4],
}

fn lab_requesters() -> [KeyPair; 2] {
    [requester_keypair("p5"), requester_keypair("p5-second")]
}

fn lab_tuple() -> [Hash256; 4] {
    [
        hash_bytes(b"p5-model"),
        hash_bytes(b"p5-profile"),
        hash_bytes(b"p5-generation"),
        hash_bytes(b"p5-assignment"),
    ]
}

/// The recovered fixture of `Fixture::recovered()` in the existing test:
/// a complete six-member production-shaped recovery identity. All secrets
/// and checkpoint signatures are generated for this disposable lab. The only
/// differences are that the directory is a persistent path (so later steps can
/// reload it) instead of a TempDir, and that the fixture is described by a
/// fixture.json for those later steps.
fn create_lab(dir: &Path) -> Lab {
    use arc_state::recovery::{ArcCheckpoint, RecoveryExportSpec, RecoveryValidator};
    use arc_types::inference_contract::{ValidatorMember, validator_set_commitment};
    use std::io::Write;
    std::fs::create_dir_all(dir).unwrap();
    let stakes = STAKES.to_vec();
    let requesters = lab_requesters();
    let tuple = lab_tuple();
    let mut genesis = format!(
        "[chain]\nname = \"arc-p5-paid-flow\"\nchain_id = \"0x415243\"\n\
         validator_set_complete = true\ninstance_id = \"{}\"\n\n",
        chain_instance_id()
    );
    for requester in &requesters {
        genesis.push_str(&format!(
            "[[accounts]]\naddress = \"{}\"\nbalance = 1_000_000_000_000\n\n",
            requester.address().to_hex()
        ));
    }
    for i in 0..stakes.len() {
        let v = validator_keypair(&format!("p5-validator-{i}"))
            .address()
            .to_hex();
        // Validators need canonical accounts: any of them may submit the
        // finalize transaction once it holds a supermajority certificate.
        genesis.push_str(&format!(
            "[[accounts]]\naddress = \"{v}\"\nbalance = 1_000_000_000_000\n\n"
        ));
    }
    for i in 0..stakes.len() {
        let v = validator_keypair(&format!("p5-validator-{i}"))
            .address()
            .to_hex();
        genesis.push_str(&format!(
            "[[validators]]\naddress = \"{v}\"\nstake = {}\n\n",
            stakes[i]
        ));
    }
    let genesis_path = dir.join("genesis.toml");
    std::fs::write(&genesis_path, genesis).unwrap();
    let activation = dir.join("activation.json");
    let genesis = arc_node::config::load_genesis(genesis_path.to_str().unwrap()).unwrap();
    let genesis_hash = genesis.network_hash(false).unwrap();
    let keys: Vec<_> = (0..stakes.len())
        .map(|i| validator_keypair(&format!("p5-validator-{i}")))
        .collect();
    for (i, key) in keys.iter().enumerate() {
        let KeyPair::Ed25519(secret) = key else {
            panic!("lab needs Ed25519");
        };
        let mut file = arc_crypto::secret_file::create_new_private(
            &dir.join(format!("validator-{i}.key.json")),
        )
        .unwrap();
        file.write_all(
            serde_json::json!({ "scheme": "ed25519", "secret_key": hex::encode(secret.to_bytes()),
                "public_key": hex::encode(key.public_key_bytes()), "address": key.address().to_hex() })
            .to_string()
            .as_bytes(),
        )
        .unwrap();
        file.sync_all().unwrap();
    }
    let mut funds = genesis.validated_accounts().unwrap();
    funds.push((
        arc_state::recovery::recovery_stake_reserve_address(),
        40_000_000,
    ));
    let source = arc_state::StateDB::with_genesis(&funds);
    let joins: Vec<_> = keys
        .iter()
        .enumerate()
        .map(|(i, key)| {
            let mut tx = Transaction::new_transfer(key.address(), key.address(), 0, 0);
            tx.body = TxBody::JoinValidator(arc_types::transaction::JoinValidatorBody {
                pubkey: key.public_key_bytes().try_into().unwrap(),
                initial_stake: stakes[i],
            });
            tx.tx_type = tx.body.tx_type();
            tx.sign(key).unwrap();
            tx
        })
        .collect();
    let (_, receipts) = source.execute_block(&joins, keys[0].address()).unwrap();
    assert!(receipts.iter().all(|r| r.success));
    for key in &keys {
        let mut account = source.get_account(&key.address()).unwrap();
        account.staked_balance = 0;
        source.update_account(&key.address(), account);
    }
    source.execute_block(&[], keys[0].address()).unwrap();
    let validators = keys
        .iter()
        .enumerate()
        .map(|(i, key)| RecoveryValidator {
            address: key.address(),
            public_key: key.public_key_bytes().try_into().unwrap(),
            stake: stakes[i],
        })
        .collect();
    let mut checkpoint = ArcCheckpoint::export_unsigned(
        &source,
        RecoveryExportSpec {
            chain_id: genesis.chain.chain_id.clone(),
            genesis_hash,
            source_consensus_round: 64,
            recovery_epoch: 1,
            validator_set_id: 1,
            validators,
            community_rewards_v1_activation_height: None,
            created_at_unix_ms: 1,
        },
    )
    .unwrap();
    for key in keys.iter().take(5) {
        checkpoint.add_signature(key).unwrap();
    }
    let checkpoint_path = dir.join("approved.arcchkpt");
    checkpoint.write_to(&checkpoint_path).unwrap();
    let mut members: Vec<_> = keys
        .iter()
        .enumerate()
        .map(|(i, key)| ValidatorMember::new(key.address(), stakes[i]))
        .collect();
    members.sort_by_key(|m| m.address.0);
    let context = arc_state::InferenceAdmissionContext {
        domain: InferenceDomain {
            chain_genesis: genesis_hash,
            recovery_epoch: 1,
            validator_set_hash: validator_set_commitment(&members).unwrap(),
        },
        members,
        allowed_executions: vec![arc_state::AllowedExecution {
            model_hash: tuple[0],
            profile_hash: tuple[1],
            generation_hash: tuple[2],
            assignment_hash: tuple[3],
        }],
        selection_rule: arc_state::NativeSelectionRule::SkipUsedNoncesV2,
    };
    // Plenty of actual DAG rounds for the ordinary transfer before H.
    let activation_height = checkpoint.manifest.source_height + 1 + 256;
    std::fs::write(
        &activation,
        serde_json::json!({
            "recovery_epoch": 1, "allowed_executions": context.allowed_executions,
            "selection_rule": context.selection_rule,
            "migration": arc_state::NativeMigrationRecord { chain_genesis: genesis_hash, recovery_epoch: 1,
                validator_set_id: 1, activation_height, context_commitment: context.commitment().unwrap() },
        })
        .to_string(),
    )
    .unwrap();
    let manifest = checkpoint.manifest_hash();
    let transaction_domain = checkpoint.manifest.recovery_context().domain_hash();
    std::fs::write(
        dir.join("fixture.json"),
        serde_json::to_string_pretty(&json!({
            "schema": "arc.statecompat-lab.fixture.v1",
            "nodes": NODES,
            "stakes": stakes,
            "base_rpc": BASE_RPC,
            "base_p2p": BASE_P2P,
            "manifest": manifest.to_hex(),
            "transaction_domain": transaction_domain.to_hex(),
            "activation_height": activation_height,
            "source_height": checkpoint.manifest.source_height,
            "checkpoint_signatures": 5,
            "genesis_validator_set_complete": true,
        }))
        .unwrap(),
    )
    .unwrap();
    Lab {
        dir: dir.to_path_buf(),
        checkpoint: checkpoint_path,
        genesis: genesis_path,
        activation,
        manifest,
        transaction_domain,
        activation_height,
        requesters,
        tuple,
    }
}

fn load_lab(dir: &Path) -> Lab {
    let meta: Value =
        serde_json::from_str(&std::fs::read_to_string(dir.join("fixture.json")).unwrap()).unwrap();
    Lab {
        dir: dir.to_path_buf(),
        checkpoint: dir.join("approved.arcchkpt"),
        genesis: dir.join("genesis.toml"),
        activation: dir.join("activation.json"),
        manifest: Hash256::from_hex(meta["manifest"].as_str().unwrap()).unwrap(),
        transaction_domain: Hash256::from_hex(meta["transaction_domain"].as_str().unwrap())
            .unwrap(),
        activation_height: meta["activation_height"].as_u64().unwrap(),
        requesters: lab_requesters(),
        tuple: lab_tuple(),
    }
}

impl Lab {
    /// Start node `index`, or restart it on the data directory it had. The
    /// argument vector is the existing fixture's `spawn_mode`, with the binary
    /// chosen by the caller and extra arguments appended (the production
    /// `--recovery-epoch 1 --validator-set-id 1 --archive` and
    /// `--snapshot-every-blocks 50` come in through LAB_EXTRA_ARGS).
    fn spawn(
        &self,
        bin: &Path,
        data_root: &Path,
        index: usize,
        runtime: bool,
        admit_requests: bool,
        extra: &[String],
    ) -> NodeProcess {
        let port = BASE_RPC + index as u16;
        let data_dir = data_root.join(format!("node-{index}"));
        std::fs::create_dir_all(&data_dir).unwrap();
        let peers: Vec<String> = (0..NODES)
            .filter(|j| *j != index)
            .map(|j| format!("127.0.0.1:{}", BASE_P2P + j as u16))
            .collect();
        // Appended, so a restarted node's log follows its first life's.
        let log = std::fs::OpenOptions::new()
            .create(true)
            .append(true)
            .open(data_dir.join("node.log"))
            .unwrap();
        let mut command = Command::new(bin);
        command.args([
            "--rpc",
            &format!("127.0.0.1:{port}"),
            "--p2p-port",
            &(BASE_P2P + index as u16).to_string(),
            "--data-dir",
            data_dir.to_str().unwrap(),
            "--genesis",
            self.genesis.to_str().unwrap(),
            "--peers",
            &peers.join(","),
            "--stake",
            &STAKES[index].to_string(),
            "--native-inference-activation",
            self.activation.to_str().unwrap(),
        ]);
        command
            .arg("--validator-key-file")
            .arg(self.dir.join(format!("validator-{index}.key.json")));
        if !data_dir.join("recovery.active").exists() {
            command
                .arg("--recovery-checkpoint")
                .arg(&self.checkpoint)
                .arg("--approved-recovery-manifest-hash")
                .arg(self.manifest.to_hex());
        }
        if runtime {
            command.args([
                "--native-inference-runtime",
                "--native-inference-test-executor",
            ]);
        }
        if admit_requests {
            command.arg("--enable-native-inference-requests");
        }
        let child = command
            .args(extra)
            .env("RUST_LOG", "info")
            .stdout(log.try_clone().unwrap())
            .stderr(log)
            .spawn()
            .expect("arc-node must start");
        NodeProcess { child, port }
    }

    fn request(
        &self,
        who: usize,
        domain: InferenceDomain,
        nonce: u64,
        expires_at: u64,
    ) -> (Transaction, Hash256) {
        let tuple = self.tuple;
        let requester = &self.requesters[who];
        let input = format!("p5 input {who}/{nonce}").into_bytes();
        let job = InferenceJob {
            version: INFERENCE_CONTRACT_VERSION,
            domain,
            requester: requester.address(),
            nonce,
            model_hash: tuple[0],
            profile_hash: tuple[1],
            input_hash: hash_bytes(&input),
            generation_hash: tuple[2],
            assignment_hash: tuple[3],
            max_tokens: 8,
            max_output_bytes: 128,
            execution_price: 10,
            reserved_max_payment: 100,
            expires_at,
        };
        let request_id = job.request_id();
        let request = InferenceRequest::sign(job, requester).unwrap();
        let body = TxBody::NativeInferenceRequest(NativeInferenceRequestBody {
            request,
            input_blob: input,
        });
        let mut tx = Transaction {
            tx_type: body.tx_type(),
            from: requester.address(),
            nonce,
            body,
            fee: 0,
            gas_limit: 5_000_000,
            hash: Hash256::ZERO,
            signature: arc_crypto::signature::Signature::null(),
            sig_verified: false,
        };
        tx.sign_in_domain(requester, &self.transaction_domain)
            .unwrap();
        (tx, request_id)
    }
}

// ------------------------------------------------------------------ the steps ----

struct Ctx {
    step: String,
    tier: String,
    lab: Lab,
    bin: PathBuf,
    data: PathBuf,
    out: PathBuf,
    extra: Vec<String>,
    expected_sha: Option<String>,
    prev: Vec<Value>,
    started: u64,
    events: Vec<Value>,
    observations: Vec<Value>,
    workload: serde_json::Map<String, Value>,
}

impl Ctx {
    fn prev_step(&self, step: &str) -> Value {
        self.prev
            .iter()
            .find(|v| v["step"] == step)
            .unwrap_or_else(|| panic!("LAB_PREV has no {step} observation"))
            .clone()
    }

    fn save(&self, complete: bool) {
        let record = json!({
            "schema": SCHEMA,
            "step": self.step,
            "tier": self.tier,
            "complete": complete,
            "binary_path": self.bin.display().to_string(),
            "expected_binary_sha256": self.expected_sha,
            "extra_args": self.extra,
            "started_unix": self.started,
            "saved_unix": now_unix(),
            "events": self.events,
            "observations": self.observations,
            "workload": Value::Object(self.workload.clone()),
        });
        std::fs::write(&self.out, serde_json::to_string_pretty(&record).unwrap()).unwrap();
    }

    fn note(&mut self, name: &str, detail: Value) {
        eprintln!("[lab] {name}: {detail}");
        self.events
            .push(json!({ "event": name, "unix": now_unix(), "detail": detail }));
        self.save(false);
    }

    fn put(&mut self, key: &str, value: Value) {
        self.workload.insert(key.to_string(), value);
        self.save(false);
    }

    fn push(&mut self, key: &str, value: Value) {
        let entry = self
            .workload
            .entry(key.to_string())
            .or_insert_with(|| Value::Array(Vec::new()));
        entry.as_array_mut().unwrap().push(value);
        self.save(false);
    }

    fn start(&mut self, runtime: bool, node0_ingress: bool, label: &str) -> Vec<NodeProcess> {
        let nodes: Vec<NodeProcess> = (0..NODES)
            .map(|i| {
                self.lab.spawn(
                    &self.bin,
                    &self.data,
                    i,
                    runtime,
                    node0_ingress && i == 0,
                    &self.extra,
                )
            })
            .collect();
        wait_recovered_peers(&nodes, label);
        let reported = wait_binary_digest(&nodes, self.expected_sha.as_deref());
        self.note(
            "started",
            json!({
                "label": label,
                "runtime": runtime,
                "node0_ingress": node0_ingress,
                "binary_report": reported,
            }),
        );
        nodes
    }

    fn observe(&mut self, nodes: &[NodeProcess], label: &str) {
        let value = observe(nodes, label);
        self.observations.push(value);
        self.save(false);
    }

    fn stop(&mut self, nodes: &mut Vec<NodeProcess>, label: &str) {
        let codes = stop_nodes(nodes);
        self.note("stopped", json!({ "label": label, "exit": codes }));
        assert!(
            codes.iter().all(|c| c["success"] == true),
            "{label}: not every validator exited cleanly: {codes:?}"
        );
        nodes.clear();
    }

    /// One ordinary transfer from requester `from` to requester `to`, accepted
    /// by node `via`, committed identically on all six.
    fn transfer(
        &mut self,
        nodes: &[NodeProcess],
        from: usize,
        to: usize,
        via: usize,
        phase: &str,
    ) -> Hash256 {
        let nonce = recovered_account(nodes[via].port, self.lab.requesters[from].address()).nonce;
        let mut tx = Transaction::new_transfer(
            self.lab.requesters[from].address(),
            self.lab.requesters[to].address(),
            1,
            nonce,
        );
        tx.fee = 1;
        tx.sign_in_domain(&self.lab.requesters[from], &self.lab.transaction_domain)
            .unwrap();
        let (code, reason) = submit(nodes[via].port, &tx);
        assert_eq!(code, 200, "{phase}: ordinary transfer refused: {reason}");
        let height = recovered_commit(nodes, tx.hash, false, phase);
        self.push(
            "transfers",
            json!({ "phase": phase, "tx": tx.hash.to_hex(), "height": height, "nonce": nonce }),
        );
        tx.hash
    }

    /// One paid native request from requester `who`, admitted by node 0 only,
    /// finalized by the committee. Returns the request id.
    fn paid_request(
        &mut self,
        nodes: &[NodeProcess],
        who: usize,
        domain: InferenceDomain,
        phase: &str,
    ) -> Hash256 {
        let nonce = recovered_account(nodes[0].port, self.lab.requesters[who].address()).nonce;
        let (paid, paid_id) = self.lab.request(who, domain, nonce, 1_000_000);
        assert_eq!(
            submit(nodes[1].port, &paid).0,
            503,
            "{phase}: a node without ingress must refuse new requests"
        );
        let (code, reason) = submit(nodes[0].port, &paid);
        assert_eq!(
            code, 200,
            "{phase}: ready opted-in node refused request: {reason}"
        );
        recovered_commit(nodes, paid.hash, true, &format!("{phase}: request"));
        wait_finalized(
            &nodes.iter().collect::<Vec<_>>(),
            paid_id,
            Duration::from_secs(120),
            &format!("{phase}: native quorum finalizes"),
        );
        let path = format!("/native-inference/receipt/{}", paid_id.to_hex());
        let receipt = get_json(nodes[0].port, &path).unwrap();
        let votes = receipt["certificate_votes"].as_u64().unwrap();
        assert!(
            votes >= 4,
            "the uneven six-member committee cannot certify with fewer than four votes"
        );
        let finalized_tx =
            Hash256::from_hex(receipt["terminal_transaction"]["tx_hash"].as_str().unwrap())
                .unwrap();
        recovered_commit(nodes, finalized_tx, true, &format!("{phase}: finalization"));
        let expected = settlement(nodes[0].port, paid_id).unwrap();
        assert_eq!(
            expected.3.iter().map(|(_, amount)| amount).sum::<u64>(),
            100
        );
        for node in nodes {
            assert_eq!(settlement(node.port, paid_id).unwrap(), expected);
        }
        self.push(
            "paid_requests",
            json!({
                "phase": phase,
                "request_id": paid_id.to_hex(),
                "certificate_votes": votes,
                "settlement": serde_json::to_value(&expected).unwrap(),
            }),
        );
        paid_id
    }
}

/// Production-flag-set steps: ordinary traffic only (no native runtime).
fn run_prod(c: &mut Ctx) {
    let step = c.step.clone();
    let mut nodes = c.start(false, false, &format!("{step}: recovered start"));
    c.observe(&nodes, "start");
    match step.as_str() {
        "old_run" => {
            c.transfer(&nodes, 0, 1, 0, "ordinary transfer before activation");
            wait_activation(&nodes);
            c.transfer(&nodes, 0, 1, 1, "ordinary transfer after activation");
        }
        "new_run" => {
            c.transfer(&nodes, 0, 1, 0, "ordinary transfer under candidate (a)");
            c.transfer(&nodes, 1, 0, 2, "ordinary transfer under candidate (b)");
            let target = advance_past_snapshot(&nodes, 60, "candidate run");
            c.put("advanced_to_height", json!(target));
        }
        "resume" => {
            c.transfer(
                &nodes,
                0,
                1,
                3,
                "ordinary transfer under resumed old binary",
            );
            let target = advance_past_snapshot(&nodes, 20, "old binary resume");
            c.put("advanced_to_height", json!(target));
        }
        other => panic!("unknown step {other}"),
    }
    c.observe(&nodes, "final");
    c.stop(&mut nodes, &step);
}

/// (label, request id, recorded settlement) for every paid request the given
/// earlier observations recorded, so a later binary can be held to them.
fn requests_of(observations: &[&Value]) -> Vec<(String, Hash256, Value)> {
    let mut rows = Vec::new();
    for observation in observations {
        if let Some(list) = observation["workload"]["paid_requests"].as_array() {
            for row in list {
                rows.push((
                    row["phase"].as_str().unwrap_or("").to_string(),
                    Hash256::from_hex(row["request_id"].as_str().unwrap()).unwrap(),
                    row["settlement"].clone(),
                ));
            }
        }
    }
    rows
}

/// Native-runtime steps: the repo's recovered-v3 paid lifecycle, split
/// across binaries (old binary writes, candidate extends, old binary resumes).
fn run_native(c: &mut Ctx) {
    let step = c.step.clone();
    match step.as_str() {
        "old_run" => {
            // Phase A: no runtime, ordinary transfer, cross activation.
            let mut nodes = c.start(false, false, "old_run phase A: signed-checkpoint import");
            c.observe(&nodes, "after_import");
            c.transfer(&nodes, 0, 1, 0, "ordinary transfer before activation");
            wait_activation(&nodes);
            c.stop(&mut nodes, "old_run phase A");
            // Phase B: native runtimes, exactly one ingress node, one paid
            // request, then a refundable bounded request left Pending.
            let mut nodes = c.start(true, true, "old_run phase B: native runtimes");
            wait_runtime_ready(&nodes, true);
            let domain = domain_from_context(&nodes[0]);
            c.paid_request(&nodes, 0, domain, "paid request on the old binary");
            c.transfer(
                &nodes,
                0,
                1,
                1,
                "ordinary transfer after native finalization",
            );
            // A valid one-token job is deliberately smaller than the
            // synthetic executor's fixed two-token answer: each worker must
            // refuse the output bounds, so the request stays refundable.
            let expires = heights(&nodes).into_iter().flatten().max().unwrap() + 40;
            let nonce = recovered_account(nodes[0].port, c.lab.requesters[1].address()).nonce;
            let (mut bounded, _) = c.lab.request(1, domain, nonce, expires);
            let TxBody::NativeInferenceRequest(body) = &mut bounded.body else {
                unreachable!()
            };
            let mut job = body.request.job.clone();
            job.max_tokens = 1;
            job.max_output_bytes = 4;
            body.request = InferenceRequest::sign(job, &c.lab.requesters[1]).unwrap();
            let refund_id = body.request.job.request_id();
            bounded
                .sign_in_domain(&c.lab.requesters[1], &c.lab.transaction_domain)
                .unwrap();
            let (code, reason) = submit(nodes[0].port, &bounded);
            assert_eq!(
                code, 200,
                "bounded valid request refused before execution: {reason}"
            );
            recovered_commit(
                &nodes,
                bounded.hash,
                true,
                "bounded request before candidate",
            );
            for node in &nodes {
                assert_eq!(settlement(node.port, refund_id).unwrap().0, "Pending");
            }
            c.put("refund_request_id", json!(refund_id.to_hex()));
            c.put("refund_expires_at", json!(expires));
            c.put("domain_chain_genesis", json!(domain.chain_genesis.to_hex()));
            c.observe(&nodes, "final");
            c.stop(&mut nodes, "old_run phase B");
        }
        "new_run" => {
            let old = c.prev_step("old_run");
            let held = requests_of(&[&old]);
            let refund_id =
                Hash256::from_hex(old["workload"]["refund_request_id"].as_str().unwrap()).unwrap();
            let expires = old["workload"]["refund_expires_at"].as_u64().unwrap();
            let mut nodes = c.start(
                true,
                true,
                "candidate: native runtimes on the pre-candidate copy",
            );
            wait_runtime_ready(&nodes, true);
            c.observe(&nodes, "start");
            // What the old binary wrote must read back identically through
            // the candidate on every node.
            for (label, id, recorded) in &held {
                for node in &nodes {
                    assert_eq!(
                        &serde_json::to_value(settlement(node.port, *id).unwrap()).unwrap(),
                        recorded,
                        "candidate reads a different settlement for: {label}"
                    );
                }
            }
            for node in &nodes {
                assert_eq!(settlement(node.port, refund_id).unwrap().0, "Pending");
            }
            // The candidate executes the refund the old binary left pending.
            wait_for(
                Duration::from_secs(240),
                "candidate DAG advances to the refund height",
                || {
                    heights(&nodes)
                        .iter()
                        .all(|h| h.is_some_and(|h| h + 1 >= expires))
                },
            );
            let body =
                TxBody::NativeInferenceRefund(arc_types::transaction::NativeInferenceRefundBody {
                    request_id: refund_id.0,
                });
            let nonce = recovered_account(nodes[2].port, c.lab.requesters[1].address()).nonce;
            let mut refund = Transaction::new_transfer(
                c.lab.requesters[1].address(),
                c.lab.requesters[1].address(),
                0,
                nonce,
            );
            refund.tx_type = body.tx_type();
            refund.body = body;
            refund.gas_limit = arc_types::transaction::gas_costs::NATIVE_INFERENCE_REFUND;
            refund
                .sign_in_domain(&c.lab.requesters[1], &c.lab.transaction_domain)
                .unwrap();
            let (code, reason) = submit(nodes[2].port, &refund);
            assert_eq!(
                code, 200,
                "closed local ingress stranded an eligible refund: {reason}"
            );
            recovered_commit(&nodes, refund.hash, true, "refund under the candidate");
            for node in &nodes {
                let receipt = settlement(node.port, refund_id).unwrap();
                assert_eq!(receipt.0, "Refunded");
                assert_eq!(
                    receipt.3,
                    vec![(c.lab.requesters[1].address().to_hex(), 100)]
                );
            }
            let refunded =
                serde_json::to_value(settlement(nodes[0].port, refund_id).unwrap()).unwrap();
            c.push(
                "refunds",
                json!({ "request_id": refund_id.to_hex(), "settlement": refunded }),
            );
            // New native work written by the candidate itself.
            let domain = domain_from_context(&nodes[0]);
            c.paid_request(&nodes, 0, domain, "paid request on the candidate");
            c.transfer(&nodes, 0, 1, 1, "ordinary transfer under candidate");
            let target = advance_past_snapshot(&nodes, 60, "candidate run");
            c.put("advanced_to_height", json!(target));
            c.observe(&nodes, "final");
            c.stop(&mut nodes, "new_run");
        }
        "resume" => {
            let old = c.prev_step("old_run");
            let cand = c.prev_step("new_run");
            let held = requests_of(&[&old, &cand]);
            let refund_id = Hash256::from_hex(
                cand["workload"]["refunds"][0]["request_id"]
                    .as_str()
                    .unwrap(),
            )
            .unwrap();
            let refund_recorded = cand["workload"]["refunds"][0]["settlement"].clone();
            let mut nodes = c.start(
                true,
                true,
                "old binary resume: native runtimes on the post-candidate copy",
            );
            wait_runtime_ready(&nodes, true);
            c.observe(&nodes, "start");
            // Everything the candidate wrote must read back identically.
            for (label, id, recorded) in &held {
                for node in &nodes {
                    assert_eq!(
                        &serde_json::to_value(settlement(node.port, *id).unwrap()).unwrap(),
                        recorded,
                        "old binary reads a different settlement for: {label}"
                    );
                }
            }
            for node in &nodes {
                assert_eq!(
                    serde_json::to_value(settlement(node.port, refund_id).unwrap()).unwrap(),
                    refund_recorded,
                    "old binary reads a different refund settlement"
                );
            }
            // The old binary must resume native execution: a NEW request
            // finalizes on it.
            let domain = domain_from_context(&nodes[0]);
            c.paid_request(&nodes, 0, domain, "paid request on the resumed old binary");
            c.transfer(
                &nodes,
                0,
                1,
                3,
                "ordinary transfer on the resumed old binary",
            );
            let target = advance_past_snapshot(&nodes, 20, "old binary resume");
            c.put("advanced_to_height", json!(target));
            c.observe(&nodes, "final");
            c.stop(&mut nodes, "resume");
        }
        other => panic!("unknown step {other}"),
    }
}

fn run_step(step: &str) {
    let out = env_path("LAB_OUT");
    if step == "fixture" {
        let dir = env_path("LAB_ROOT").join("fixture");
        let lab = create_lab(&dir);
        let record = json!({
            "schema": SCHEMA,
            "step": "fixture",
            "complete": true,
            "fixture_dir": dir.display().to_string(),
            "manifest": lab.manifest.to_hex(),
            "transaction_domain": lab.transaction_domain.to_hex(),
            "activation_height": lab.activation_height,
        });
        std::fs::write(&out, serde_json::to_string_pretty(&record).unwrap()).unwrap();
        eprintln!("[lab] fixture written to {}", dir.display());
        return;
    }
    let tier = env_required("LAB_TIER");
    assert!(
        tier == "prod" || tier == "native",
        "LAB_TIER must be prod or native"
    );
    // LAB_PREV: colon-separated observation files of earlier steps.
    let prev: Vec<Value> = std::env::var("LAB_PREV")
        .unwrap_or_default()
        .split(':')
        .filter(|path| !path.is_empty())
        .map(|path| serde_json::from_str(&std::fs::read_to_string(path).unwrap()).unwrap())
        .collect();
    let mut ctx = Ctx {
        step: step.to_string(),
        tier: tier.clone(),
        lab: load_lab(&env_path("LAB_ROOT").join("fixture")),
        bin: env_path("LAB_BIN"),
        data: env_path("LAB_DATA"),
        out,
        extra: std::env::var("LAB_EXTRA_ARGS")
            .unwrap_or_default()
            .split_whitespace()
            .map(str::to_string)
            .collect(),
        expected_sha: std::env::var("LAB_EXPECT_SHA256")
            .ok()
            .filter(|s| !s.is_empty()),
        prev,
        started: now_unix(),
        events: Vec::new(),
        observations: Vec::new(),
        workload: serde_json::Map::new(),
    };
    ctx.note("begin", json!({ "step": step, "tier": tier }));
    if tier == "prod" {
        run_prod(&mut ctx);
    } else {
        run_native(&mut ctx);
    }
    ctx.save(true);
}

#[test]
fn lab_step() {
    let Ok(step) = std::env::var("LAB_STEP") else {
        eprintln!("LAB_STEP is not set: the STATECOMPAT lab harness does nothing");
        return;
    };
    run_step(&step);
}
