import base64
import hashlib
import importlib.util
import json
import tempfile
import unittest
from pathlib import Path

SPEC = importlib.util.spec_from_file_location(
    "sbom", Path(__file__).resolve().parents[1] / "sbom.py")
sbom = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(sbom)

CARGO = '''# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "arc-node"
version = "0.8.0"
dependencies = [
 "serde",
 "rand 0.8.5",
]

[[package]]
name = "rand"
version = "0.8.5"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "aa"

[[package]]
name = "rand"
version = "0.9.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "bb"

[[package]]
name = "serde"
version = "1.0.0"
source = "git+https://github.com/serde-rs/serde?rev=abc#abc"
dependencies = ["rand 0.9.0"]
'''

NPM = {
    "lockfileVersion": 3,
    "packages": {
        "": {"name": "arc-desktop", "version": "0.8.0"},
        "node_modules/@scope/pkg": {
            "version": "1.2.3",
            "resolved": "https://registry.npmjs.org/@scope/pkg/-/pkg-1.2.3.tgz",
            "integrity": "sha512-" + base64.b64encode(hashlib.sha512(b"x").digest()).decode(),
            "dev": True,
            "license": "MIT",
        },
    },
}


class Sbom(unittest.TestCase):
    def setUp(self):
        self.dir = tempfile.TemporaryDirectory()
        root = Path(self.dir.name)
        self.cargo = root / "Cargo.lock"
        self.cargo.write_text(CARGO)
        self.npm = root / "package-lock.json"
        self.npm.write_text(json.dumps(NPM))

    def tearDown(self):
        self.dir.cleanup()

    def test_components_hashes_sources_and_the_dependency_graph(self):
        doc = sbom.build("arc-chain", "0.8.0", [self.cargo], [self.npm])
        by_ref = {c["bom-ref"]: c for c in doc["components"]}
        self.assertEqual(by_ref["pkg:cargo/rand@0.8.5"]["hashes"],
                         [{"alg": "SHA-256", "content": "aa"}])
        self.assertNotIn("hashes", by_ref["pkg:cargo/arc-node@0.8.0"], "workspace crates have no checksum")
        git = [c for c in doc["components"] if c["name"] == "serde"][0]
        self.assertIn("vcs_url=", git["purl"])
        scoped = by_ref["pkg:npm/%40scope%2Fpkg@1.2.3"]
        self.assertEqual(scoped["hashes"][0]["content"], hashlib.sha512(b"x").hexdigest())
        self.assertIn({"name": "arc:scope", "value": "dev"}, scoped["properties"])
        deps = {d["ref"]: d["dependsOn"] for d in doc["dependencies"]}
        # "rand 0.8.5" resolves to the exact version, not the other rand.
        self.assertIn("pkg:cargo/rand@0.8.5", deps["pkg:cargo/arc-node@0.8.0"])
        self.assertNotIn("pkg:cargo/rand@0.9.0", deps["pkg:cargo/arc-node@0.8.0"])
        self.assertEqual(doc["bomFormat"], "CycloneDX")
        self.assertTrue(doc["serialNumber"].startswith("urn:uuid:"))

    def test_the_same_lock_files_give_the_same_bytes(self):
        first = json.dumps(sbom.build("arc-chain", "0.8.0", [self.cargo], [self.npm]), sort_keys=True)
        second = json.dumps(sbom.build("arc-chain", "0.8.0", [self.cargo], [self.npm]), sort_keys=True)
        self.assertEqual(first, second)


if __name__ == "__main__":
    unittest.main()
