// Add to lib.rs: pub mod bridge;

use serde::{Deserialize, Serialize};

/// 20-byte EVM-compatible address used in bridge contexts.
/// Both ARC Chain and external EVM chains use this format for cross-chain transfers.
pub type EvmAddress = [u8; 20];

/// Zero EVM address — indicates native token (ETH, ARC, etc.).
pub const ZERO_EVM_ADDRESS: EvmAddress = [0u8; 20];

// ─── Chain Identifiers ──────────────────────────────────────────────────────

/// Supported bridge chains.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ChainId {
    ArcMainnet,
    Ethereum,
    Base,
    Arbitrum,
    Optimism,
    Polygon,
    Bsc,
    Avalanche,
    /// Arbitrary EVM chain by numeric chain ID.
    Custom(u64),
}

impl ChainId {
    /// Return the EVM-standard numeric chain ID.
    pub fn evm_chain_id(&self) -> u64 {
        match self {
            ChainId::ArcMainnet => 0xA4C, // 2636 — ARC custom chain ID
            ChainId::Ethereum => 1,
            ChainId::Base => 8453,
            ChainId::Arbitrum => 42161,
            ChainId::Optimism => 10,
            ChainId::Polygon => 137,
            ChainId::Bsc => 56,
            ChainId::Avalanche => 43114,
            ChainId::Custom(id) => *id,
        }
    }

    /// Returns true if the chain is EVM-compatible (all currently supported chains are).
    pub fn is_evm_compatible(&self) -> bool {
        true
    }

    /// Human-readable chain name.
    pub fn name(&self) -> &str {
        match self {
            ChainId::ArcMainnet => "ARC Mainnet",
            ChainId::Ethereum => "Ethereum",
            ChainId::Base => "Base",
            ChainId::Arbitrum => "Arbitrum One",
            ChainId::Optimism => "Optimism",
            ChainId::Polygon => "Polygon",
            ChainId::Bsc => "BNB Smart Chain",
            ChainId::Avalanche => "Avalanche C-Chain",
            ChainId::Custom(id) => {
                // Can't return a dynamic string from &str, so use a generic label
                // Callers needing the ID should use evm_chain_id() directly.
                let _ = id;
                "Custom EVM Chain"
            }
        }
    }
}

// ─── Bridge Transfer ────────────────────────────────────────────────────────

/// Bridge transfer status lifecycle.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum BridgeStatus {
    /// Transfer submitted, awaiting lock on source chain.
    Pending,
    /// Assets locked on source chain.
    SourceLocked,
    /// Merkle proof being generated by relayer.
    Proving,
    /// Wrapped assets minted on destination chain.
    DestMinted,
    /// Confirmed on both chains — terminal success state.
    Completed,
    /// Transaction reverted — terminal failure state.
    Failed,
    /// Timeout reached without completion — terminal failure state.
    Expired,
}

/// Cross-chain bridge transfer request.
///
/// Represents a lock-and-mint bridge operation: assets are locked on the source
/// chain and equivalent wrapped assets are minted on the destination chain.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BridgeTransfer {
    /// Unique transfer ID (BLAKE3 hash of all content fields).
    pub transfer_id: [u8; 32],
    /// Chain where assets are locked.
    pub source_chain: ChainId,
    /// Chain where wrapped assets are minted.
    pub dest_chain: ChainId,
    /// Sender address on source chain.
    pub source_address: EvmAddress,
    /// Recipient address on destination chain.
    pub dest_address: EvmAddress,
    /// Token contract on source chain (zero address = native token).
    pub token_address: EvmAddress,
    /// Amount in smallest unit (wei / lamports / etc.).
    pub amount: u128,
    /// Sequence number per sender (replay protection).
    pub nonce: u64,
    /// Unix timestamp of transfer creation.
    pub timestamp: u64,
    /// Current status in the bridge lifecycle.
    pub status: BridgeStatus,
}

impl BridgeTransfer {
    /// Create a new pending bridge transfer and compute its transfer ID.
    pub fn new(
        source: ChainId,
        dest: ChainId,
        from: EvmAddress,
        to: EvmAddress,
        token: EvmAddress,
        amount: u128,
        nonce: u64,
    ) -> Self {
        let timestamp = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs();

        let mut transfer = Self {
            transfer_id: [0u8; 32],
            source_chain: source,
            dest_chain: dest,
            source_address: from,
            dest_address: to,
            token_address: token,
            amount,
            nonce,
            timestamp,
            status: BridgeStatus::Pending,
        };
        transfer.transfer_id = transfer.compute_transfer_id();
        transfer
    }

    /// Compute the deterministic transfer ID from all content fields.
    ///
    /// Covers: source_chain || dest_chain || source_address || dest_address
    ///         || token_address || amount || nonce || timestamp
    pub fn compute_transfer_id(&self) -> [u8; 32] {
        let mut hasher = blake3::Hasher::new_derive_key("ARC-bridge-transfer-v1");
        hasher.update(&self.source_chain.evm_chain_id().to_le_bytes());
        hasher.update(&self.dest_chain.evm_chain_id().to_le_bytes());
        hasher.update(&self.source_address);
        hasher.update(&self.dest_address);
        hasher.update(&self.token_address);
        hasher.update(&self.amount.to_le_bytes());
        hasher.update(&self.nonce.to_le_bytes());
        hasher.update(&self.timestamp.to_le_bytes());
        *hasher.finalize().as_bytes()
    }

    /// Returns true if this transfer uses the native token (zero address).
    pub fn is_native_token(&self) -> bool {
        self.token_address == ZERO_EVM_ADDRESS
    }

    /// Returns true if the transfer has reached a terminal state.
    pub fn is_finalized(&self) -> bool {
        matches!(
            self.status,
            BridgeStatus::Completed | BridgeStatus::Failed | BridgeStatus::Expired
        )
    }

    /// Calculate the estimated bridge fee for this transfer given a config.
    ///
    /// Fee = amount * fee_bps / 10_000
    pub fn estimated_fee(&self, config: &BridgeConfig) -> u128 {
        self.amount
            .checked_mul(config.fee_bps as u128)
            .unwrap_or(u128::MAX)
            / 10_000
    }
}

// ─── Bridge Proof ───────────────────────────────────────────────────────────

/// Merkle inclusion proof for cross-chain bridge verification.
///
/// The relayer generates this proof from the source chain's state to prove
/// that a lock transaction was included in a finalized block.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BridgeProof {
    /// Transfer ID this proof corresponds to.
    pub transfer_id: [u8; 32],
    /// Block hash on source chain containing the lock transaction.
    pub source_block_hash: [u8; 32],
    /// Block height on source chain.
    pub source_block_height: u64,
    /// Merkle sibling hashes from leaf to root.
    pub merkle_siblings: Vec<[u8; 32]>,
    /// Index of the leaf in the Merkle tree.
    pub leaf_index: u64,
    /// Hash of the leaf (the transfer commitment).
    pub leaf_hash: [u8; 32],
}

impl BridgeProof {
    /// Verify this Merkle proof against an expected root hash.
    ///
    /// Walks from the leaf up through the sibling path, hashing pairs,
    /// and checks whether the computed root matches the expected root.
    pub fn verify(&self, expected_root: &[u8; 32]) -> bool {
        let mut current = self.leaf_hash;
        let mut index = self.leaf_index;

        for sibling in &self.merkle_siblings {
            let mut hasher = blake3::Hasher::new();
            if index % 2 == 0 {
                // Current is the left child
                hasher.update(&current);
                hasher.update(sibling);
            } else {
                // Current is the right child
                hasher.update(sibling);
                hasher.update(&current);
            }
            current = *hasher.finalize().as_bytes();
            index /= 2;
        }

        current == *expected_root
    }
}

// ─── Relay Message ──────────────────────────────────────────────────────────

/// Message submitted by a bridge relayer to the destination chain.
///
/// Contains the original transfer, the Merkle inclusion proof, and the
/// relayer's signature authorizing the mint operation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BridgeRelayMessage {
    /// The original bridge transfer being relayed.
    pub transfer: BridgeTransfer,
    /// Merkle proof of lock inclusion on the source chain.
    pub proof: BridgeProof,
    /// Address of the relayer submitting this message.
    pub relayer_address: EvmAddress,
    /// Relayer's signature over (transfer_id || proof commitment).
    pub relayer_signature: Vec<u8>,
}

// ─── Bridge Config ──────────────────────────────────────────────────────────

/// Configuration for a specific chain-pair bridge route.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BridgeConfig {
    /// Source chain for this route.
    pub source_chain: ChainId,
    /// Destination chain for this route.
    pub dest_chain: ChainId,
    /// Bridge contract address on the source chain.
    pub bridge_contract: EvmAddress,
    /// Minimum source chain confirmations before proof generation.
    pub min_confirmations: u32,
    /// Maximum transfer amount (in smallest unit).
    pub max_transfer_amount: u128,
    /// Minimum transfer amount (in smallest unit).
    pub min_transfer_amount: u128,
    /// Fee in basis points (100 = 1%).
    pub fee_bps: u16,
    /// Blocks before an uncompleted transfer expires.
    pub timeout_blocks: u64,
    /// Whether this bridge route is currently accepting transfers.
    pub is_active: bool,
}

impl BridgeConfig {
    /// Default configuration for Ethereum -> ARC Mainnet bridge.
    pub fn default_eth_to_arc() -> Self {
        Self {
            source_chain: ChainId::Ethereum,
            dest_chain: ChainId::ArcMainnet,
            bridge_contract: [0u8; 20], // Placeholder — set after deployment
            min_confirmations: 12,
            max_transfer_amount: 1_000_000_000_000_000_000_000, // 1000 ETH in wei
            min_transfer_amount: 10_000_000_000_000_000,        // 0.01 ETH in wei
            fee_bps: 30,                                        // 0.30%
            timeout_blocks: 7200,                                // ~24h at 12s blocks
            is_active: true,
        }
    }

    /// Default configuration for ARC Mainnet -> Ethereum bridge.
    pub fn default_arc_to_eth() -> Self {
        Self {
            source_chain: ChainId::ArcMainnet,
            dest_chain: ChainId::Ethereum,
            bridge_contract: [0u8; 20], // Placeholder — set after deployment
            min_confirmations: 1,
            max_transfer_amount: 1_000_000_000_000_000_000_000,
            min_transfer_amount: 10_000_000_000_000_000,
            fee_bps: 30,
            timeout_blocks: 14400,
            is_active: true,
        }
    }

    /// Check whether a transfer amount falls within the allowed range.
    pub fn is_amount_valid(&self, amount: u128) -> bool {
        amount >= self.min_transfer_amount && amount <= self.max_transfer_amount
    }
}

// ─── Token Mapping ──────────────────────────────────────────────────────────

/// Mapping between a token on the source chain and its wrapped representation
/// on the destination chain.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TokenMapping {
    /// Chain where the original token lives.
    pub source_chain: ChainId,
    /// Chain where the wrapped token is minted.
    pub dest_chain: ChainId,
    /// Token contract address on source chain.
    pub source_token: EvmAddress,
    /// Wrapped token contract address on destination chain.
    pub dest_token: EvmAddress,
    /// Decimal precision on source chain.
    pub decimals_source: u8,
    /// Decimal precision on destination chain.
    pub decimals_dest: u8,
    /// Token ticker symbol (e.g. "WETH", "ARC").
    pub symbol: String,
    /// Full token name (e.g. "Wrapped Ether").
    pub name: String,
}

// ─── Bridge Stats ───────────────────────────────────────────────────────────

/// Aggregate statistics for bridge activity.
#[derive(Debug, Clone, Default)]
pub struct BridgeStats {
    /// Total number of transfers ever submitted.
    pub total_transfers: u64,
    /// Cumulative volume (in smallest unit of the bridge's base token).
    pub total_volume: u128,
    /// Number of currently non-finalized transfers.
    pub pending_transfers: u64,
    /// Number of successfully completed transfers.
    pub completed_transfers: u64,
    /// Number of failed or expired transfers.
    pub failed_transfers: u64,
    /// Number of unique sender addresses.
    pub unique_users: u64,
}

impl BridgeStats {
    /// Record a bridge transfer, updating all counters.
    pub fn record_transfer(&mut self, transfer: &BridgeTransfer) {
        self.total_transfers += 1;
        self.total_volume = self.total_volume.saturating_add(transfer.amount);

        match transfer.status {
            BridgeStatus::Completed => {
                self.completed_transfers += 1;
            }
            BridgeStatus::Failed | BridgeStatus::Expired => {
                self.failed_transfers += 1;
            }
            _ => {
                self.pending_transfers += 1;
            }
        }
    }

    /// Percentage of completed transfers out of all finalized transfers.
    /// Returns 0.0 if no transfers have been finalized.
    pub fn success_rate(&self) -> f64 {
        let finalized = self.completed_transfers + self.failed_transfers;
        if finalized == 0 {
            return 0.0;
        }
        self.completed_transfers as f64 / finalized as f64
    }
}

// ─── Tests ──────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn test_evm_addr(n: u8) -> EvmAddress {
        let mut addr = [0u8; 20];
        addr[19] = n;
        addr
    }

    // 1. Chain ID EVM mapping
    #[test]
    fn test_chain_id_evm_ids() {
        assert_eq!(ChainId::Ethereum.evm_chain_id(), 1);
        assert_eq!(ChainId::Base.evm_chain_id(), 8453);
        assert_eq!(ChainId::Arbitrum.evm_chain_id(), 42161);
        assert_eq!(ChainId::Optimism.evm_chain_id(), 10);
        assert_eq!(ChainId::Polygon.evm_chain_id(), 137);
        assert_eq!(ChainId::Bsc.evm_chain_id(), 56);
        assert_eq!(ChainId::Avalanche.evm_chain_id(), 43114);
        assert_eq!(ChainId::ArcMainnet.evm_chain_id(), 0xA4C);
        assert_eq!(ChainId::Custom(999).evm_chain_id(), 999);

        // All chains are EVM-compatible
        assert!(ChainId::Ethereum.is_evm_compatible());
        assert!(ChainId::ArcMainnet.is_evm_compatible());
        assert!(ChainId::Custom(42).is_evm_compatible());

        // Names
        assert_eq!(ChainId::Ethereum.name(), "Ethereum");
        assert_eq!(ChainId::ArcMainnet.name(), "ARC Mainnet");
        assert_eq!(ChainId::Custom(777).name(), "Custom EVM Chain");
    }

    // 2. Transfer creation
    #[test]
    fn test_bridge_transfer_creation() {
        let from = test_evm_addr(1);
        let to = test_evm_addr(2);
        let token = test_evm_addr(0xAA);

        let transfer = BridgeTransfer::new(
            ChainId::Ethereum,
            ChainId::ArcMainnet,
            from,
            to,
            token,
            1_000_000_000_000_000_000, // 1 ETH
            0,
        );

        assert_eq!(transfer.source_chain, ChainId::Ethereum);
        assert_eq!(transfer.dest_chain, ChainId::ArcMainnet);
        assert_eq!(transfer.source_address, from);
        assert_eq!(transfer.dest_address, to);
        assert_eq!(transfer.token_address, token);
        assert_eq!(transfer.amount, 1_000_000_000_000_000_000);
        assert_eq!(transfer.nonce, 0);
        assert_eq!(transfer.status, BridgeStatus::Pending);
        assert_ne!(transfer.transfer_id, [0u8; 32]);
    }

    // 3. Transfer ID determinism
    #[test]
    fn test_transfer_id_deterministic() {
        let from = test_evm_addr(1);
        let to = test_evm_addr(2);
        let token = ZERO_EVM_ADDRESS;

        let mut a = BridgeTransfer::new(
            ChainId::Ethereum,
            ChainId::ArcMainnet,
            from,
            to,
            token,
            500,
            1,
        );
        // Force same timestamp for determinism
        a.timestamp = 1_700_000_000;
        a.transfer_id = a.compute_transfer_id();

        let mut b = BridgeTransfer::new(
            ChainId::Ethereum,
            ChainId::ArcMainnet,
            from,
            to,
            token,
            500,
            1,
        );
        b.timestamp = 1_700_000_000;
        b.transfer_id = b.compute_transfer_id();

        assert_eq!(a.transfer_id, b.transfer_id);
    }

    // 4. Different nonce produces different transfer ID
    #[test]
    fn test_transfer_id_changes_with_nonce() {
        let from = test_evm_addr(1);
        let to = test_evm_addr(2);
        let token = ZERO_EVM_ADDRESS;

        let mut a = BridgeTransfer::new(
            ChainId::Ethereum,
            ChainId::ArcMainnet,
            from,
            to,
            token,
            500,
            0,
        );
        a.timestamp = 1_700_000_000;
        a.transfer_id = a.compute_transfer_id();

        let mut b = BridgeTransfer::new(
            ChainId::Ethereum,
            ChainId::ArcMainnet,
            from,
            to,
            token,
            500,
            1,
        );
        b.timestamp = 1_700_000_000;
        b.transfer_id = b.compute_transfer_id();

        assert_ne!(a.transfer_id, b.transfer_id);
    }

    // 5. Native token detection
    #[test]
    fn test_native_token_detection() {
        let native = BridgeTransfer::new(
            ChainId::Ethereum,
            ChainId::ArcMainnet,
            test_evm_addr(1),
            test_evm_addr(2),
            ZERO_EVM_ADDRESS,
            1000,
            0,
        );
        assert!(native.is_native_token());

        let erc20 = BridgeTransfer::new(
            ChainId::Ethereum,
            ChainId::ArcMainnet,
            test_evm_addr(1),
            test_evm_addr(2),
            test_evm_addr(0xAA),
            1000,
            0,
        );
        assert!(!erc20.is_native_token());
    }

    // 6. Valid Merkle proof verification
    #[test]
    fn test_bridge_proof_verification() {
        // Build a small Merkle tree manually: 4 leaves
        let leaves: Vec<[u8; 32]> = (0u8..4)
            .map(|i| *blake3::hash(&[i]).as_bytes())
            .collect();

        // Level 0: [L0, L1, L2, L3]
        // Level 1: [H(L0,L1), H(L2,L3)]
        // Level 2: [H(H(L0,L1), H(L2,L3))]  <- root

        let h01 = {
            let mut h = blake3::Hasher::new();
            h.update(&leaves[0]);
            h.update(&leaves[1]);
            *h.finalize().as_bytes()
        };
        let h23 = {
            let mut h = blake3::Hasher::new();
            h.update(&leaves[2]);
            h.update(&leaves[3]);
            *h.finalize().as_bytes()
        };
        let root = {
            let mut h = blake3::Hasher::new();
            h.update(&h01);
            h.update(&h23);
            *h.finalize().as_bytes()
        };

        // Prove leaf[0]: siblings = [L1, H(L2,L3)]
        let proof = BridgeProof {
            transfer_id: [0u8; 32],
            source_block_hash: [0u8; 32],
            source_block_height: 100,
            merkle_siblings: vec![leaves[1], h23],
            leaf_index: 0,
            leaf_hash: leaves[0],
        };

        assert!(proof.verify(&root));
    }

    // 7. Tampered proof fails
    #[test]
    fn test_bridge_proof_invalid() {
        let leaves: Vec<[u8; 32]> = (0u8..4)
            .map(|i| *blake3::hash(&[i]).as_bytes())
            .collect();

        let h01 = {
            let mut h = blake3::Hasher::new();
            h.update(&leaves[0]);
            h.update(&leaves[1]);
            *h.finalize().as_bytes()
        };
        let h23 = {
            let mut h = blake3::Hasher::new();
            h.update(&leaves[2]);
            h.update(&leaves[3]);
            *h.finalize().as_bytes()
        };
        let root = {
            let mut h = blake3::Hasher::new();
            h.update(&h01);
            h.update(&h23);
            *h.finalize().as_bytes()
        };

        // Tampered: use wrong leaf hash
        let proof = BridgeProof {
            transfer_id: [0u8; 32],
            source_block_hash: [0u8; 32],
            source_block_height: 100,
            merkle_siblings: vec![leaves[1], h23],
            leaf_index: 0,
            leaf_hash: *blake3::hash(b"tampered").as_bytes(),
        };

        assert!(!proof.verify(&root));

        // Tampered: wrong sibling
        let proof2 = BridgeProof {
            transfer_id: [0u8; 32],
            source_block_hash: [0u8; 32],
            source_block_height: 100,
            merkle_siblings: vec![*blake3::hash(b"wrong-sibling").as_bytes(), h23],
            leaf_index: 0,
            leaf_hash: leaves[0],
        };

        assert!(!proof2.verify(&root));
    }

    // 8. Config amount validation
    #[test]
    fn test_bridge_config_amount_validation() {
        let config = BridgeConfig::default_eth_to_arc();

        // Below minimum
        assert!(!config.is_amount_valid(1_000));
        // At minimum
        assert!(config.is_amount_valid(config.min_transfer_amount));
        // In range
        assert!(config.is_amount_valid(1_000_000_000_000_000_000)); // 1 ETH
        // At maximum
        assert!(config.is_amount_valid(config.max_transfer_amount));
        // Above maximum
        assert!(!config.is_amount_valid(config.max_transfer_amount + 1));
    }

    // 9. Stats tracking
    #[test]
    fn test_bridge_stats_tracking() {
        let mut stats = BridgeStats::default();

        // Record a pending transfer
        let t1 = BridgeTransfer::new(
            ChainId::Ethereum,
            ChainId::ArcMainnet,
            test_evm_addr(1),
            test_evm_addr(2),
            ZERO_EVM_ADDRESS,
            1000,
            0,
        );
        stats.record_transfer(&t1);
        assert_eq!(stats.total_transfers, 1);
        assert_eq!(stats.pending_transfers, 1);
        assert_eq!(stats.total_volume, 1000);

        // Record a completed transfer
        let mut t2 = BridgeTransfer::new(
            ChainId::Ethereum,
            ChainId::ArcMainnet,
            test_evm_addr(3),
            test_evm_addr(4),
            ZERO_EVM_ADDRESS,
            2000,
            0,
        );
        t2.status = BridgeStatus::Completed;
        stats.record_transfer(&t2);
        assert_eq!(stats.total_transfers, 2);
        assert_eq!(stats.completed_transfers, 1);
        assert_eq!(stats.total_volume, 3000);

        // Record a failed transfer
        let mut t3 = BridgeTransfer::new(
            ChainId::Ethereum,
            ChainId::ArcMainnet,
            test_evm_addr(5),
            test_evm_addr(6),
            ZERO_EVM_ADDRESS,
            500,
            0,
        );
        t3.status = BridgeStatus::Failed;
        stats.record_transfer(&t3);
        assert_eq!(stats.total_transfers, 3);
        assert_eq!(stats.failed_transfers, 1);
    }

    // 10. Fee calculation
    #[test]
    fn test_fee_calculation() {
        let config = BridgeConfig {
            fee_bps: 100, // 1%
            ..BridgeConfig::default_eth_to_arc()
        };

        let transfer = BridgeTransfer::new(
            ChainId::Ethereum,
            ChainId::ArcMainnet,
            test_evm_addr(1),
            test_evm_addr(2),
            ZERO_EVM_ADDRESS,
            1_000_000_000_000_000_000, // 1 ETH
            0,
        );

        let fee = transfer.estimated_fee(&config);
        // 1% of 1 ETH = 0.01 ETH
        assert_eq!(fee, 10_000_000_000_000_000);

        // 0.30% (default)
        let default_config = BridgeConfig::default_eth_to_arc();
        let fee_30bps = transfer.estimated_fee(&default_config);
        assert_eq!(fee_30bps, 3_000_000_000_000_000); // 0.003 ETH
    }

    // 11. Bridge status types
    #[test]
    fn test_bridge_status_transitions() {
        let mut transfer = BridgeTransfer::new(
            ChainId::Ethereum,
            ChainId::ArcMainnet,
            test_evm_addr(1),
            test_evm_addr(2),
            ZERO_EVM_ADDRESS,
            1000,
            0,
        );

        // Pending — not finalized
        assert_eq!(transfer.status, BridgeStatus::Pending);
        assert!(!transfer.is_finalized());

        // SourceLocked — not finalized
        transfer.status = BridgeStatus::SourceLocked;
        assert!(!transfer.is_finalized());

        // Proving — not finalized
        transfer.status = BridgeStatus::Proving;
        assert!(!transfer.is_finalized());

        // DestMinted — not finalized
        transfer.status = BridgeStatus::DestMinted;
        assert!(!transfer.is_finalized());

        // Completed — finalized
        transfer.status = BridgeStatus::Completed;
        assert!(transfer.is_finalized());

        // Failed — finalized
        transfer.status = BridgeStatus::Failed;
        assert!(transfer.is_finalized());

        // Expired — finalized
        transfer.status = BridgeStatus::Expired;
        assert!(transfer.is_finalized());
    }

    // 12. Token mapping
    #[test]
    fn test_token_mapping() {
        let mapping = TokenMapping {
            source_chain: ChainId::Ethereum,
            dest_chain: ChainId::ArcMainnet,
            source_token: test_evm_addr(0xAA),
            dest_token: test_evm_addr(0xBB),
            decimals_source: 18,
            decimals_dest: 18,
            symbol: "WETH".to_string(),
            name: "Wrapped Ether".to_string(),
        };

        assert_eq!(mapping.source_chain, ChainId::Ethereum);
        assert_eq!(mapping.dest_chain, ChainId::ArcMainnet);
        assert_eq!(mapping.source_token[19], 0xAA);
        assert_eq!(mapping.dest_token[19], 0xBB);
        assert_eq!(mapping.decimals_source, 18);
        assert_eq!(mapping.decimals_dest, 18);
        assert_eq!(mapping.symbol, "WETH");
        assert_eq!(mapping.name, "Wrapped Ether");

        // Verify bincode serde round-trip
        let encoded = bincode::serialize(&mapping).unwrap();
        let recovered: TokenMapping = bincode::deserialize(&encoded).unwrap();
        assert_eq!(recovered.symbol, "WETH");
        assert_eq!(recovered.source_token, mapping.source_token);
    }

    // Success rate
    #[test]
    fn test_success_rate() {
        let mut stats = BridgeStats::default();
        assert_eq!(stats.success_rate(), 0.0);

        stats.completed_transfers = 9;
        stats.failed_transfers = 1;
        assert!((stats.success_rate() - 0.9).abs() < f64::EPSILON);

        stats.completed_transfers = 0;
        stats.failed_transfers = 5;
        assert_eq!(stats.success_rate(), 0.0);
    }
}
