#!/usr/bin/env bash
# One consumption attempt, as an operator runs it, with timing markers the host orchestrator parses.
# THROWAWAY LAB FILE.
#   published: scripts/legacy-bridge/canary-consume.sh UNMODIFIED, fetching the real release by tag.
#   artifact : the same script with its single download line replaced by a copy of the launcher bytes of the
#              Stage A handoff artifact (a rehearsal; generated by the host and labelled as such).
# Usage: apply.sh published|artifact TAG SHA256 [--dry-run]
set -uo pipefail
mode="${1:?mode}"
tag="${2:?tag}"
sha="${3:?sha256}"
dry="${4:-}"
arc_dir="$HOME/.arc"
flags=(--tag "$tag" --expect-sha256 "$sha" --arc-dir "$arc_dir")
if [ "$dry" != "--dry-run" ]; then flags+=(--apply); fi
echo "APPLY_BEGIN $(date +%s.%N) mode=$mode tag=$tag dry=$([ "$dry" = "--dry-run" ] && echo yes || echo no)"
case "$mode" in
    published) bash /opt/arc-w0/scripts/legacy-bridge/canary-consume.sh "${flags[@]}" ;;
    artifact) ARC_W0_LAUNCHER_SRC=/opt/arc-w0/launcher/arc-node-linux-x86_64 bash /opt/arc-w0/lab/canary-consume-local.sh "${flags[@]}" ;;
    *) echo "unknown mode $mode" >&2; exit 64 ;;
esac
rc=$?
echo "APPLY_END $(date +%s.%N) rc=$rc"
exit "$rc"
