//! ARC-specific regression vectors.
//!
//! These are not conformance vectors (RFC 9381 Appendix B.3, ERC-2333 and the
//! Ethereum BLS vectors are checked elsewhere); they pin ARC's own choices: the
//! leader-election `alpha` layout and the proof-of-possession bytes for fixed,
//! obviously public test keys. The ignored `print_vectors` test prints them as
//! JSON; CI runs it with `--ignored --nocapture` so the run that produced the
//! committed data can be cited next to it.

use arc_vrf::{BlsSecretKey, Purpose, SecretKey, VrfInput};
use serde_json::json;

fn ecvrf_cases() -> Vec<serde_json::Value> {
    let mut cases = Vec::new();
    for seed in 1..=3u8 {
        let sk = SecretKey::from_bytes([seed; 32]);
        let pk = sk.public_key();
        for (purpose, epoch, slot) in [
            (Purpose::LeaderElection, 1u64, 0u64),
            (Purpose::LeaderElection, 7, 11),
            (Purpose::CommitteeSampling, 7, 0),
            (Purpose::EpochSeedContribution, 8, 0),
        ] {
            let input = VrfInput {
                purpose,
                chain_id: [0x11; 32],
                epoch,
                slot,
                epoch_seed: [0x22; 32],
            };
            let alpha = input.alpha();
            let proof = sk.prove(&alpha).unwrap();
            let beta = pk.verify(&alpha, &proof).unwrap();
            cases.push(json!({
                "sk": hex::encode(sk.to_bytes()),
                "pk": hex::encode(pk.to_bytes()),
                "purpose": format!("{purpose:?}"),
                "chain_id": hex::encode(input.chain_id),
                "epoch": epoch,
                "slot": slot,
                "epoch_seed": hex::encode(input.epoch_seed),
                "alpha": hex::encode(alpha),
                "pi": hex::encode(proof.to_bytes()),
                "beta": hex::encode(beta.to_bytes()),
            }));
        }
    }
    cases
}

fn bls_pop_cases() -> Vec<serde_json::Value> {
    (1..=3u8)
        .map(|seed| {
            let ikm = [seed; 32];
            let sk = BlsSecretKey::key_gen(&ikm, &[]).unwrap();
            let pk = sk.public_key();
            let pop = sk.prove_possession();
            assert!(pk.verify_possession(&pop));
            json!({
                "ikm": hex::encode(ikm),
                "key_info": "",
                "sk": hex::encode(sk.to_bytes()),
                "pk": hex::encode(pk.to_bytes()),
                "pop": hex::encode(pop.to_bytes()),
                "message": hex::encode(b"ARC"),
                "signature": hex::encode(sk.sign(b"ARC").to_bytes()),
            })
        })
        .collect()
}

#[test]
#[ignore = "prints the ARC regression vectors; run with --ignored --nocapture"]
fn print_vectors() {
    let document = json!({
        "description": "ARC regression vectors generated by crates/arc-vrf/tests/regression_vectors.rs",
        "ecvrf_leader_election": ecvrf_cases(),
        "bls_proof_of_possession": bls_pop_cases(),
    });
    println!("ARC_VRF_REGRESSION_VECTORS_BEGIN");
    println!("{}", serde_json::to_string_pretty(&document).unwrap());
    println!("ARC_VRF_REGRESSION_VECTORS_END");
}
