"""Tests for the pure helpers and the phase logic of stage_b/host_run.py (THROWAWAY LAB FILE).

The VM is faked: `guest` returns scripted results, so no ssh, qemu or network is involved."""
from __future__ import annotations

import json
import subprocess
import tempfile
import unittest
from pathlib import Path
from unittest import mock

import _paths  # noqa: F401
import host_run as hr

try:
    import yaml
except ImportError:  # pragma: no cover
    yaml = None

CONFIG = json.loads((_paths.LAB / "config.json").read_text(encoding="utf-8"))
PINS = json.loads((_paths.ROOT / "crates/arc-legacy-bridge/pins/active.json").read_text(encoding="utf-8"))
CANARY = (_paths.ROOT / "scripts/legacy-bridge/canary-consume.sh").read_text(encoding="utf-8")
LAUNCHER_BYTES = 2663184
NODE_BYTES = PINS["node_release"]["assets"]["arc-node-linux-x86_64"]["size"]


class HelperTests(unittest.TestCase):
    def test_effective_config(self):
        smoke = json.loads(json.dumps(CONFIG))
        smoke["stage_b"]["profile"] = "smoke"
        eff = hr.effective_config(smoke, PINS)
        self.assertEqual(eff["schema"], hr.EFFECTIVE_SCHEMA)
        self.assertEqual(eff["profile"], "smoke")
        self.assertEqual(eff["expected_launcher_sha256"], CONFIG["stage_b"]["expect_sha256"])
        self.assertEqual(eff["node_tag"], "v0.8.11")
        self.assertEqual(eff["node_sha256"], "54d4d0708ae41d32958110cce9961851911c9b72ca269756cd49dfbc731e061b")
        self.assertEqual(eff["sample_interval_s"], 10)
        full = json.loads(json.dumps(CONFIG))
        full["stage_b"]["profile"] = "full"
        eff = hr.effective_config(full, PINS)
        self.assertEqual((eff["sample_interval_s"], eff["min_total_s"], eff["min_steady_s"], eff["min_steady_samples"], eff["post_reboot_healthy_s"]), (60, 14400, 7200, 121, 600))

    def test_interrupt_quota_lands_inside_the_node_download(self):
        for network_launcher in (LAUNCHER_BYTES, 0):
            quota = hr.interrupt_quota(network_launcher, NODE_BYTES)
            cut = quota - network_launcher * 1.04
            self.assertTrue(0.15 * NODE_BYTES <= cut <= 0.75 * NODE_BYTES, (network_launcher, quota, cut))
        with self.assertRaises(ValueError):
            hr.interrupt_quota(0, 5_000_000)

    def test_resume_bound_is_far_below_a_restart(self):
        partial = 12_000_000
        bound = hr.resume_bound(LAUNCHER_BYTES, NODE_BYTES + 4_622_792, partial)
        restart = LAUNCHER_BYTES + NODE_BYTES + 4_622_792
        self.assertLess(bound, restart - partial // 2)
        self.assertGreater(bound, restart - partial)

    def test_canary_replay_changes_exactly_one_line(self):
        replay = hr.canary_replay(CANARY)
        original_lines = CANARY.split("\n")
        replay_lines = replay.split("\n")
        self.assertEqual(len(replay_lines), len(original_lines) + 2, "the banner adds two comment lines")
        removed = [line for line in original_lines if line not in replay_lines]
        self.assertEqual(removed, ["curl -fL --proto '=https' --tlsv1.2 -o \"$staged\" \"$url\""])
        added = [line for line in replay_lines if line not in original_lines]
        self.assertEqual(added[-1], 'cp "${ARC_W0_LAUNCHER_SRC:?}" "$staged"')
        self.assertTrue(replay.startswith("#!/usr/bin/env bash\n# GENERATED BY wave0-lab (rehearsal)"))
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "replay.sh"
            path.write_text(replay, encoding="utf-8")
            self.assertEqual(subprocess.run(["bash", "-n", str(path)]).returncode, 0)

    def test_canary_replay_refuses_a_changed_or_doubled_download_line(self):
        with self.assertRaises(ValueError):
            hr.canary_replay(CANARY.replace("curl -fL --proto", "curl -fsSL --proto"))
        line = "curl -fL --proto '=https' --tlsv1.2 -o \"$staged\" \"$url\""
        with self.assertRaises(ValueError):
            hr.canary_replay(CANARY.replace(line, line + "\n" + line))

    def test_canary_replay_dry_run_prints_the_same_plan_as_the_original(self):
        """Run both scripts in a fake v0.7 install: the plan text must be identical."""
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            arc = root / "arc"
            (arc / "bin").mkdir(parents=True)
            (arc / "bin" / "arc-node").write_text("#!/bin/sh\n")
            (arc / "bin" / "arc-node").chmod(0o755)
            (arc / "version.txt").write_text("0.7.7\n")
            original = root / "orig.sh"
            replay = root / "replay.sh"
            original.write_text(CANARY)
            replay.write_text(hr.canary_replay(CANARY))
            args = ["--tag", "v0.7.12", "--expect-sha256", "41d92a475db819eb190b6409ac82cb3258a557980c193decc629896718a3f69e", "--arc-dir", str(arc)]
            # The unit-file preflight needs Linux; on other systems both scripts stop at the same place.
            first = subprocess.run(["bash", str(original), *args], capture_output=True, text=True)
            second = subprocess.run(["bash", str(replay), *args], capture_output=True, text=True)
            self.assertEqual((first.returncode, first.stdout, first.stderr), (second.returncode, second.stdout, second.stderr))

    def test_cloud_init_user_data(self):
        text = hr.cloud_init_user_data("ssh-ed25519 AAAAC3Nz test@lab\n")
        self.assertTrue(text.startswith("#cloud-config\n"))
        if yaml is None:
            self.skipTest("PyYAML is not installed")
        data = yaml.safe_load(text)
        user = data["users"][0]
        self.assertEqual(user["name"], "arcw0")
        self.assertEqual(user["sudo"], "ALL=(ALL) NOPASSWD:ALL")
        self.assertEqual(user["ssh_authorized_keys"], ["ssh-ed25519 AAAAC3Nz test@lab"])
        self.assertIn("jq", data["packages"])
        self.assertIn("iptables", data["packages"])
        self.assertTrue(any("unattended-upgrades" in command for command in data["runcmd"]))
        self.assertTrue(any("/var/lib/arc-w0/cloud-init-done" in command for command in data["runcmd"]))

    def test_qemu_argv(self):
        argv = hr.qemu_argv(Path("/w"), 2, 6144)
        joined = " ".join(argv)
        self.assertIn("accel=kvm", joined)
        self.assertIn("hostfwd=tcp:127.0.0.1:2222-:22", joined)
        self.assertIn("ipv6=off", joined)
        self.assertIn("-daemonize", argv)
        self.assertNotIn("-no-reboot", argv, "a guest reboot must restart the VM, not stop it")
        self.assertIn("file=/w/disk.qcow2,if=virtio,format=qcow2", joined)

    def test_state_changes(self):
        pre = {name: 1 for name in hr.UPDATER_UNCHANGED_FIELDS}
        pre.update({"auto_update_rolled_back": 0, "health_ok": True})
        post = dict(pre)
        self.assertEqual(hr.state_changes(pre, post), [])
        post["bin_arc_node_sha256"] = 2
        self.assertEqual(len(hr.state_changes(pre, post)), 1)
        post = dict(pre, auto_update_rolled_back=1)
        self.assertTrue(hr.state_changes(pre, post))
        post = dict(pre, health_ok=False)
        self.assertTrue(hr.state_changes(pre, post))

    def test_kickstart_problems(self):
        pre = {"main_pid": 10, "health_ok": True, "address": "a", "bridge_node_address": "a", "bin_arc_node_sha256": "s", "version_txt": "0.7.12",
               "node_exe_sha256": "n", "legacy_fingerprint": "f", "bridge_log_reuse_count": 3}
        post = dict(pre, main_pid=11, bridge_log_reuse_count=4)
        self.assertEqual(hr.kickstart_problems(pre, post, "a"), [])
        for change in ({"main_pid": 10}, {"health_ok": False}, {"address": "b"}, {"bridge_node_address": "b"}, {"node_exe_sha256": "x"},
                       {"legacy_fingerprint": "g"}, {"bridge_log_reuse_count": 3}, {"bridge_log_reuse_count": 5}, {"version_txt": "0.7.7"}):
            with self.subTest(change):
                self.assertTrue(hr.kickstart_problems(pre, dict(post, **change), "a"))
        self.assertTrue(hr.kickstart_problems(pre, post, "different-first-identity"))

    def test_parse_apply_output(self):
        out = "APPLY_BEGIN 1790000000.5 mode=published\nstuff\nAPPLY_END 1790000042.25 rc=1\n"
        self.assertEqual(hr.parse_apply_output(out), {"begin": 1790000000.5, "end": 1790000042.25, "rc": 1})
        self.assertEqual(hr.parse_apply_output("nothing"), {"begin": None, "end": None, "rc": None})

    def test_stop_is_clean(self):
        self.assertTrue(hr.stop_is_clean("state=inactive\nprocs=0\nrpc=closed\n"))
        for bad in ("state=active\nprocs=0\nrpc=closed\n", "state=inactive\nprocs=1\nrpc=closed\n", "state=inactive\nprocs=3175\nrpc=closed\n",
                    "state=inactive\nprocs=0\nrpc=open\n", "inactive\n3175\nrpc-closed\n", ""):
            with self.subTest(bad):
                self.assertFalse(hr.stop_is_clean(bad))

    def test_the_updater_evidence_command_skips_the_curl_progress_meter(self):
        lab, tmp = None, None
        import re as _re
        pattern = hr.UPDATER_DECISION_LINES
        sample = "  % Total    % Received % Xferd  Average Speed\n100 2600k  100 2600k\n[x] new version available: 0.7.12 -> 0.7.11. Downloading.\ncurl: (22) The requested URL returned error: 404\n"
        kept = [line for line in sample.splitlines() if _re.search(pattern, line)]
        self.assertEqual(len(kept), 2)

    def test_last_int_tolerates_chatter(self):
        self.assertEqual(hr.last_int("sudo: unable to resolve host\n12345\n"), 12345)
        self.assertEqual(hr.last_int("nothing here"), 0)
        self.assertEqual(hr.last_int("1.5 and 7"), 7)

    def test_last_json_line(self):
        self.assertEqual(hr.last_json_line("noise\n{\"a\": 1}\n"), {"a": 1})
        self.assertIsNone(hr.last_json_line("noise only"))


class FakeLab(hr.Lab):
    """A Lab whose guest is scripted. `script` maps a substring of the command to a Result or a callable."""

    def __init__(self, cfg, evidence, work, script=None):
        super().__init__(cfg, evidence, work)
        self.script = script or {}
        self.commands = []
        self.states = []
        self.epoch = 1_000_000.0
        self.samples = []

    def say(self, message):  # keep the unit test output quiet
        pass

    def guest(self, cmd, timeout=120, retries=0, log=True):
        self.commands.append(cmd)
        if log:
            self._append("commands.jsonl", {"host_epoch": 1.0, "cmd": cmd[:600], "rc": 0})
        for needle, answer in self.script.items():
            if needle in cmd:
                return answer(cmd) if callable(answer) else answer
        return hr.Result(0, "")

    def guest_epoch(self):
        self.epoch += 60
        return self.epoch

    def capture(self):
        return self.states.pop(0)

    def wait_health(self, seconds):
        return True

    def samples_tail(self, count=5):
        return list(self.samples)

    def pull_samples(self):
        pass


def state(**overrides):
    base = {name: 1 for name in hr.UPDATER_UNCHANGED_FIELDS}
    base.update({"auto_update_rolled_back": 0, "health_ok": True, "bridge_log_reuse_count": 0, "main_pid": 100})
    base.update(overrides)
    return base


class PhaseTests(unittest.TestCase):
    def make(self, profile="smoke", **script):
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        cfg = json.loads(json.dumps(CONFIG))
        cfg["stage_b"]["profile"] = profile
        lab = FakeLab(cfg, Path(tmp.name) / "evidence", Path(tmp.name) / "work", script)
        return lab

    def checks(self, lab):
        path = lab.evidence / "checks-live.jsonl"
        return {json.loads(line)["id"]: json.loads(line) for line in path.read_text().splitlines()} if path.exists() else {}

    def events(self, lab):
        path = lab.evidence / "events.jsonl"
        return [json.loads(line) for line in path.read_text().splitlines()] if path.exists() else []

    def test_updaters_pass_when_nothing_changes_and_note_the_pre_flip_exit(self):
        tail = "[x] new version available: 0.7.12 → 0.7.11. Downloading.\ncurl: (22) The requested URL returned error: 404\n"
        lab = self.make(**{
            "systemctl start arc-updater": hr.Result(1, "Job for arc-updater.service failed"),
            "auto-update.log": hr.Result(0, tail),
            "systemctl show arc-updater": hr.Result(0, "Result=exit-code\nExecMainStatus=22\nActiveState=failed\n"),
        })
        lab.states = [state(), state(), state(), state()]
        with mock.patch.object(hr.time, "sleep"):
            lab.phase_updaters()
        checks = self.checks(lab)
        self.assertEqual(checks["L05-updater-1-noop"]["result"], "PASS")
        self.assertEqual(checks["L06-updater-2-noop"]["result"], "PASS")
        self.assertIn(hr.PRE_FLIP_NOTE, checks["L05-updater-1-noop"]["detail"])
        names = [event["name"] for event in self.events(lab)]
        self.assertEqual(names.count("updater_run_1"), 1)
        self.assertEqual(names.count("updater_run_2"), 1)
        forced = [event for event in self.events(lab) if event["name"].startswith("updater_run")]
        self.assertTrue(all(event["forced"] for event in forced))

    def test_updater_fails_when_the_binary_changed(self):
        lab = self.make(**{"auto-update.log": hr.Result(0, "log")})
        lab.states = [state(), state(bin_arc_node_sha256="other"), state(), state()]
        with mock.patch.object(hr.time, "sleep"):
            lab.phase_updaters()
        checks = self.checks(lab)
        self.assertEqual(checks["L05-updater-1-noop"]["result"], "FAIL")
        self.assertEqual(checks["L06-updater-2-noop"]["result"], "PASS")

    def test_kickstarts(self):
        lab = self.make()
        lab.t0_address = "a"
        lab.states = []
        for number in range(3):
            pre = state(address="a", bridge_node_address="a", main_pid=100 + number, bridge_log_reuse_count=number)
            post = state(address="a", bridge_node_address="a", main_pid=101 + number, bridge_log_reuse_count=number + 1)
            lab.states += [pre, post]
        # make consecutive pre states equal the previous post state, as in real life
        with mock.patch.object(hr.time, "sleep"):
            lab.phase_kickstarts()
        checks = self.checks(lab)
        for check_id in ("L07-kickstart-1", "L08-kickstart-2", "L09-kickstart-3"):
            self.assertEqual(checks[check_id]["result"], "PASS", checks[check_id])

    def test_kickstart_identity_change_fails(self):
        lab = self.make()
        lab.t0_address = "a"
        lab.states = [state(address="a", bridge_node_address="a", bridge_log_reuse_count=0), state(address="b", bridge_node_address="a", main_pid=101, bridge_log_reuse_count=1)] * 3
        with mock.patch.object(hr.time, "sleep"):
            lab.phase_kickstarts()
        self.assertEqual(self.checks(lab)["L07-kickstart-1"]["result"], "FAIL")

    def test_phase_wrapper_records_a_crash_as_a_failed_check_and_goes_on(self):
        lab = self.make()

        def boom():
            raise RuntimeError("kaboom")

        self.assertFalse(lab.phase("x", ("L05-updater-1-noop",), boom))
        self.assertEqual(self.checks(lab)["L05-updater-1-noop"]["result"], "FAIL")
        with self.assertRaises(hr.Fatal):
            lab.phase("y", ("L06-updater-2-noop",), boom, fatal=True)

    def test_steady_runs_until_both_durations_hold(self):
        lab = self.make()
        lab.t0_guest_epoch = 1_000_000.0 + 60
        lab.last_forced_end_guest = 1_000_000.0 + 3000
        lab.epoch = 1_000_000.0 + 3000
        with mock.patch.object(hr.time, "sleep"):
            lab.phase_steady()
        names = [event["name"] for event in self.events(lab)]
        self.assertEqual(names[0], "steady_begin")
        self.assertEqual(names[-1], "steady_end")
        profile = lab.profile
        target = max(lab.last_forced_end_guest + profile["min_steady_s"], lab.t0_guest_epoch + profile["min_total_s"]) + 2 * profile["sample_interval_s"]
        self.assertGreaterEqual(lab.epoch, target)
        self.assertLess(lab.epoch, target + 200, "the loop must stop soon after the target")

    def test_steady_is_cut_short_by_the_deadline(self):
        lab = self.make("full")
        lab.t0_guest_epoch = 1_000_000.0
        lab.last_forced_end_guest = 1_000_000.0
        lab.deadline = 0  # already past
        with mock.patch.object(hr.time, "sleep"):
            lab.phase_steady()
        self.assertIn("steady_cut_short_by_deadline", [event["name"] for event in self.events(lab)])

    def test_reboot_records_boot_ids_and_issues_no_start_command(self):
        boot_ids = iter(["bootA", "bootA", "bootB", "bootB"])
        lab = self.make(**{"kernel/random/boot_id": lambda cmd: hr.Result(0, next(boot_ids) + "\n"),
                           "journalctl": hr.Result(0, "journal-pre-boot.txt journal-post-boot.txt 10")})
        lab.samples = [{"boot_id": "bootB", "health_ok": True, "node_exe": "/home/arcw0/.arc/legacy-bridge/releases/v0.8.11/arc-node-linux-x86_64", "epoch": 1_000_500.0}]
        with mock.patch.object(hr.time, "sleep"):
            lab.phase_reboot()
        checks = self.checks(lab)
        self.assertEqual(checks["L10-reboot-boot-id-changed"]["result"], "PASS", checks)
        self.assertEqual(checks["L12-pre-post-boot-logs"]["result"], "PASS", checks)
        events = {event["name"]: event for event in self.events(lab)}
        self.assertTrue(events["reboot_issued"]["forced"])
        self.assertFalse(events["reboot_recovered"]["forced"])
        self.assertEqual(events["reboot_recovered"]["detail"]["boot_id_after"], "bootB")
        self.assertEqual(events["reboot_recovered"]["detail"]["first_healthy_sample_epoch"], 1_000_500.0)
        self.assertEqual(events["reboot_recovered"]["guest_epoch"], 1_000_500.0)
        self.assertEqual(lab.last_forced_end_guest, 1_000_500.0)
        for command in lab.commands:
            self.assertNotRegex(command, r"systemctl\s+(start|restart)\s[^;&|]*arc-node")

    def test_reboot_without_a_new_boot_id_fails(self):
        lab = self.make(**{"kernel/random/boot_id": hr.Result(0, "bootA\n")})
        lab.profile = dict(lab.profile, reboot_recovery_deadline_s=1)
        clock = iter(range(1000, 100000, 50))
        with mock.patch.object(hr.time, "sleep"), mock.patch.object(hr.time, "time", side_effect=lambda: next(clock)):
            with self.assertRaises(hr.Fatal):
                lab.phase_reboot()
        self.assertEqual(self.checks(lab)["L10-reboot-boot-id-changed"]["result"], "FAIL")

    def test_check_and_event_files_are_json_lines(self):
        lab = self.make()
        lab.check("L01-kvm", "t", "PASS", "d")
        lab.event("run_begin", forced=False, guest_epoch=5.0, a=1)
        self.assertEqual(self.checks(lab)["L01-kvm"]["detail"], "d")
        self.assertEqual(self.events(lab)[0]["detail"], {"a": 1})

    def test_required_ids_are_the_ids_the_evaluator_demands(self):
        self.assertEqual(
            list(hr.REQUIRED_LIVE_IDS),
            ["L01-kvm", "L02-consume-dry-run", "L03-interrupt-took-effect", "L04-interrupt-resumes", "L05-updater-1-noop", "L06-updater-2-noop",
             "L07-kickstart-1", "L08-kickstart-2", "L09-kickstart-3", "L10-reboot-boot-id-changed", "L11-stop-rollback", "L12-pre-post-boot-logs"],
        )


if __name__ == "__main__":
    unittest.main()
