#!/usr/bin/env bash
set -euo pipefail

# ══════════════════════════════════════════════════════════════════════════════
# ARC Chain — Testnet Genesis Coordinator
# Generates keypairs, genesis config, and per-validator configs for a testnet.
# ══════════════════════════════════════════════════════════════════════════════

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
OUTPUT_DIR="${ARC_TESTNET_DIR:-$PROJECT_DIR/testnet}"

NUM_VALIDATORS="${1:-4}"
CHAIN_NAME="arc-testnet-1"
CHAIN_ID="0x415243"
VALIDATOR_STAKE=5000000           # 5M ARC per validator
TEST_ACCOUNT_BALANCE=1000000000000  # 1T ARC per test account
FAUCET_BALANCE=100000000000000    # 100T ARC for faucet
NUM_TEST_ACCOUNTS=100

BASE_P2P_PORT=9091
BASE_RPC_PORT=9090

# ── Colors ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m'

info()    { echo -e "  ${CYAN}INFO${NC}  $*"; }
ok()      { echo -e "  ${GREEN} OK ${NC}  $*"; }
warn()    { echo -e "  ${YELLOW}WARN${NC}  $*"; }
fail()    { echo -e "  ${RED}FAIL${NC}  $*"; exit 1; }
section() { echo -e "\n${BOLD}── $* ──${NC}"; }

# ── Dependency check ────────────────────────────────────────────────────────
check_deps() {
    if ! command -v openssl &>/dev/null; then
        fail "openssl is required but not found. Install it and retry."
    fi
}

# ── Ed25519 keypair generation via openssl ──────────────────────────────────
# Generates a PEM private key and extracts the hex-encoded public key.
generate_keypair() {
    local name="$1"
    local key_dir="$OUTPUT_DIR/keys"
    mkdir -p "$key_dir"

    local privkey_pem="$key_dir/${name}.pem"
    local pubkey_file="$key_dir/${name}.pub"

    # Generate Ed25519 private key
    openssl genpkey -algorithm ed25519 -out "$privkey_pem" 2>/dev/null

    # Extract raw public key bytes as hex (last 32 bytes of the DER-encoded public key)
    local pubkey_hex
    pubkey_hex=$(openssl pkey -in "$privkey_pem" -pubout -outform DER 2>/dev/null \
        | tail -c 32 \
        | xxd -p -c 64)

    echo "$pubkey_hex" > "$pubkey_file"
    echo "$pubkey_hex"
}

# ── Generate a deterministic test account address ───────────────────────────
# Uses SHA-256 of the index as a stand-in for blake3 (widely available).
generate_test_address() {
    local index="$1"
    printf '%s' "arc-test-account-${index}" | openssl dgst -sha256 -hex 2>/dev/null \
        | sed 's/^.*= //'
}

# ══════════════════════════════════════════════════════════════════════════════
# Main
# ══════════════════════════════════════════════════════════════════════════════

check_deps

echo ""
echo -e "${BOLD}ARC Chain Testnet Genesis Coordinator${NC}"
echo -e "${DIM}Generating config for ${NUM_VALIDATORS} validators${NC}"
echo ""

mkdir -p "$OUTPUT_DIR"

# ── Step 1: Generate validator keypairs ──────────────────────────────────────
section "Generating Ed25519 keypairs for ${NUM_VALIDATORS} validators"

declare -a VALIDATOR_PUBKEYS
for i in $(seq 0 $((NUM_VALIDATORS - 1))); do
    pubkey=$(generate_keypair "validator-${i}")
    VALIDATOR_PUBKEYS+=("$pubkey")
    ok "validator-${i}  pubkey=${DIM}${pubkey:0:16}...${NC}"
done

# ── Step 2: Generate genesis.toml ────────────────────────────────────────────
section "Creating genesis.toml"

GENESIS_FILE="$OUTPUT_DIR/genesis.toml"

cat > "$GENESIS_FILE" <<GENESIS_HEADER
# ARC Chain Testnet Genesis Configuration
# Generated by create-testnet.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Chain: ${CHAIN_NAME}
# Validators: ${NUM_VALIDATORS}
# Test accounts: ${NUM_TEST_ACCOUNTS}

[chain]
name = "${CHAIN_NAME}"
chain_id = "${CHAIN_ID}"  # "ARC" in ASCII hex

# ── Genesis Validators ──────────────────────────────────────────────────────
GENESIS_HEADER

for i in $(seq 0 $((NUM_VALIDATORS - 1))); do
    cat >> "$GENESIS_FILE" <<VALIDATOR_ENTRY

[[validators]]
seed = "arc-validator-${i}"
pubkey = "${VALIDATOR_PUBKEYS[$i]}"
stake = ${VALIDATOR_STAKE}
VALIDATOR_ENTRY
done

# Faucet account
cat >> "$GENESIS_FILE" <<FAUCET_HEADER

# ── Faucet Account ──────────────────────────────────────────────────────────

FAUCET_HEADER

FAUCET_ADDRESS=$(generate_test_address "faucet")
cat >> "$GENESIS_FILE" <<FAUCET_ENTRY
[[accounts]]
address = "${FAUCET_ADDRESS}"
balance = ${FAUCET_BALANCE}
label = "faucet"
FAUCET_ENTRY

# Prefunded test accounts
cat >> "$GENESIS_FILE" <<ACCOUNTS_HEADER

# ── Prefunded Test Accounts (${NUM_TEST_ACCOUNTS} x ${TEST_ACCOUNT_BALANCE} ARC) ─────────────

ACCOUNTS_HEADER

for i in $(seq 0 $((NUM_TEST_ACCOUNTS - 1))); do
    addr=$(generate_test_address "$i")
    cat >> "$GENESIS_FILE" <<ACCOUNT_ENTRY

# Test account ${i}
[[accounts]]
address = "${addr}"
balance = ${TEST_ACCOUNT_BALANCE}
ACCOUNT_ENTRY
done

ok "genesis.toml written to ${GENESIS_FILE}"

# ── Step 3: Generate per-validator config files ──────────────────────────────
section "Creating per-validator config files"

SEED_P2P_PORT=${BASE_P2P_PORT}
SEED_ADDRESS="127.0.0.1:${SEED_P2P_PORT}"

for i in $(seq 0 $((NUM_VALIDATORS - 1))); do
    local_p2p_port=$((BASE_P2P_PORT + i))
    # RPC ports: 9090, 9190, 9290, 9390 (spaced by 100)
    local_rpc_port=$((BASE_RPC_PORT + i * 100))

    CONFIG_FILE="$OUTPUT_DIR/config-validator-${i}.toml"

    cat > "$CONFIG_FILE" <<VCONFIG
# ARC Chain — Validator ${i} Configuration
# Generated by create-testnet.sh

[rpc]
listen = "0.0.0.0:${local_rpc_port}"

[p2p]
port = ${local_p2p_port}
VCONFIG

    # All non-seed validators peer with validator-0
    if [ "$i" -gt 0 ]; then
        cat >> "$CONFIG_FILE" <<PEERS
peers = ["${SEED_ADDRESS}"]
PEERS
    fi

    cat >> "$CONFIG_FILE" <<VCONFIG_REST

[validator]
seed = "arc-validator-${i}"
pubkey = "${VALIDATOR_PUBKEYS[$i]}"
stake = ${VALIDATOR_STAKE}

[storage]
data_dir = "./arc-data/validator-${i}"
VCONFIG_REST

    ok "config-validator-${i}.toml  RPC=:${local_rpc_port}  P2P=:${local_p2p_port}"
done

# ── Step 4: Create seeds.toml ────────────────────────────────────────────────
section "Creating seeds.toml"

SEEDS_FILE="$OUTPUT_DIR/seeds.toml"
cat > "$SEEDS_FILE" <<SEEDS
# ARC Chain Testnet Seed Nodes
# Validator-0 is the initial seed node.
# Replace 127.0.0.1 with actual public IP before distributing.

[[seeds]]
address = "${SEED_ADDRESS}"
name = "arc-seed-0"
pubkey = "${VALIDATOR_PUBKEYS[0]}"
SEEDS

ok "seeds.toml written to ${SEEDS_FILE}"

# ── Step 5: Print summary ───────────────────────────────────────────────────
section "Testnet Setup Complete"
echo ""
echo -e "  ${BOLD}Chain:${NC}        ${CHAIN_NAME}"
echo -e "  ${BOLD}Chain ID:${NC}     ${CHAIN_ID}"
echo -e "  ${BOLD}Validators:${NC}   ${NUM_VALIDATORS}"
echo -e "  ${BOLD}Test accounts:${NC} ${NUM_TEST_ACCOUNTS} (${TEST_ACCOUNT_BALANCE} ARC each)"
echo -e "  ${BOLD}Faucet:${NC}       ${FAUCET_BALANCE} ARC"
echo ""
echo -e "  ${BOLD}Output directory:${NC} ${OUTPUT_DIR}"
echo ""
echo -e "  ${BOLD}Files generated:${NC}"
echo -e "    ${DIM}genesis.toml${NC}                    Chain genesis state"
echo -e "    ${DIM}seeds.toml${NC}                      Seed node addresses"
for i in $(seq 0 $((NUM_VALIDATORS - 1))); do
    local_rpc=$((BASE_RPC_PORT + i * 100))
    local_p2p=$((BASE_P2P_PORT + i))
    echo -e "    ${DIM}config-validator-${i}.toml${NC}         RPC=:${local_rpc}  P2P=:${local_p2p}"
done
echo -e "    ${DIM}keys/validator-*.pem${NC}            Ed25519 private keys"
echo -e "    ${DIM}keys/validator-*.pub${NC}            Public keys (hex)"
echo ""
echo -e "${BOLD}Next steps:${NC}"
echo ""
echo -e "  1. Start each validator with its own config:"
echo ""
for i in $(seq 0 $((NUM_VALIDATORS - 1))); do
    echo -e "     ${DIM}arc-node --config ${OUTPUT_DIR}/config-validator-${i}.toml \\${NC}"
    echo -e "     ${DIM}         --genesis ${OUTPUT_DIR}/genesis.toml${NC}"
    echo ""
done
echo -e "  2. Or use Docker Compose for a quick local testnet:"
echo -e "     ${DIM}docker compose up${NC}"
echo ""
echo -e "  3. Monitor the testnet:"
echo -e "     ${DIM}./scripts/monitor-testnet.sh${NC}"
echo ""
echo -e "  4. Use the faucet to fund accounts:"
echo -e "     ${DIM}curl -X POST http://127.0.0.1:9090/faucet -d '{\"address\": \"...\", \"amount\": 1000}'${NC}"
echo ""
