//! Precomputed lookup tables for integer-only inference.
//!
//! All tables are const arrays computed at build time — zero runtime float dependency.
//! Used by integer_engine.rs for exp and GeLU approximations.

/// Fixed-point fractional bits. Value x represents x / 2^FRAC_BITS.
pub const FRAC_BITS: u32 = 16;
/// 1.0 in fixed-point representation.
pub const ONE: i64 = 1 << FRAC_BITS; // 65536

/// Integer exp lookup table for softmax.
/// 256 entries covering x in [-8*ONE, 0].
/// EXP_LUT[i] = round(exp(-(256 - i) * 8.0 / 256.0) * ONE)
/// Entry 256 would be exp(0) = ONE, entry 0 is exp(-8) ≈ 0.
///
/// For x < -8*ONE, exp(x) ≈ 0 (< 0.034% of ONE).
/// For x = 0, exp(x) = ONE.
///
/// Usage: integer_exp(x) where x <= 0 in Q16 fixed-point.
pub const EXP_LUT_SIZE: usize = 256;
pub const EXP_LUT_RANGE: i64 = 8 * ONE; // covers [-8*ONE, 0]

// Generated by: for i in range(257): print(round(math.exp(-(256-i)*8.0/256.0) * 65536))
pub const EXP_LUT: [i64; 257] = {
    // We compute this as a const fn to guarantee determinism
    let mut table = [0i64; 257];
    // Entry i corresponds to x = -(256 - i) * 8 / 256 = -(256-i)/32
    // exp(-(256-i)/32) * 65536
    // We use a rational approximation: exp(-n/32) for integer n from 256..0
    // Pre-computed values (Python: [round(math.exp(-(256-i)/32.0)*65536) for i in range(257)])
    // Since we can't call exp() in const context, we hardcode the table.

    // Populate using the recurrence: exp(-k/32) = exp(-(k-1)/32) * exp(-1/32)
    // exp(-1/32) ≈ 0.96923 = 63521/65536 in Q16
    // Starting from exp(0) = 65536 (entry 256), work backwards
    table[256] = ONE; // exp(0) = 1.0

    // exp(-1/32) in Q16 ≈ 63521
    // More precisely: exp(-0.03125) = 0.969233234... * 65536 = 63521.07...
    let decay: i64 = 63521; // exp(-1/32) * ONE, rounded

    let mut i: usize = 255;
    loop {
        // table[i] = table[i+1] * decay / ONE
        table[i] = (table[i + 1] * decay) >> FRAC_BITS;
        if i == 0 { break; }
        i -= 1;
    }

    table
};

/// Integer exp for x <= 0 (Q16 fixed-point).
/// Returns round(exp(x_real) * ONE) where x_real = x / ONE.
/// Uses lookup table with linear interpolation. Deterministic on all platforms.
pub fn integer_exp(x: i64) -> i64 {
    if x >= 0 { return ONE; }
    if x <= -(EXP_LUT_RANGE) { return 0; }

    // Map x from [-8*ONE, 0] to index [0, 256]
    // index = (x + 8*ONE) * 256 / (8*ONE) = (x + 8*ONE) / (8*ONE/256) = (x + 8*ONE) >> 5
    // Since 8*ONE/256 = ONE/32 = 65536/32 = 2048
    let offset = x + EXP_LUT_RANGE; // [0, 8*ONE]
    let step = ONE / 32; // 2048
    let idx = (offset / step) as usize;
    let frac = offset % step;

    if idx >= 256 { return ONE; }

    // Linear interpolation between table[idx] and table[idx+1]
    let lo = EXP_LUT[idx];
    let hi = EXP_LUT[idx + 1];
    lo + ((hi - lo) * frac) / step
}

/// Integer softmax: input is slice of Q16 values, output is Q16 values summing to ~ONE.
/// Deterministic on all platforms (no float operations).
pub fn softmax_i64(input: &[i64]) -> Vec<i64> {
    if input.is_empty() { return vec![]; }
    if input.len() == 1 { return vec![ONE]; }

    // Find max for numerical stability
    let max_val = *input.iter().max().unwrap();

    // Compute exp(x - max) for each element
    let exps: Vec<i64> = input.iter()
        .map(|&x| integer_exp(x - max_val))
        .collect();

    // Sum of exps
    let sum: i64 = exps.iter().sum();
    if sum == 0 {
        // All values are negligible — return uniform
        let n = input.len() as i64;
        return vec![ONE / n; input.len()];
    }

    // Normalize: output[i] = exps[i] * ONE / sum
    exps.iter().map(|&e| (e * ONE) / sum).collect()
}

/// Integer argmax: returns index of largest value. Ties broken by lowest index.
pub fn argmax_i64(input: &[i64]) -> usize {
    let mut best_idx = 0;
    let mut best_val = i64::MIN;
    for (i, &v) in input.iter().enumerate() {
        if v > best_val {
            best_val = v;
            best_idx = i;
        }
    }
    best_idx
}

/// Integer ReLU: max(0, x). Pure integer, trivially deterministic.
pub fn relu_i64(x: i64) -> i64 {
    if x > 0 { x } else { 0 }
}

/// Integer inverse square root: returns round(ONE / sqrt(x)) where x is Q16.
/// Uses Newton-Raphson iteration starting from a rough estimate.
/// Deterministic across all platforms (integer-only).
pub fn integer_isqrt(x: i64) -> i64 {
    if x <= 0 { return ONE * 100; } // avoid division by zero, return large value

    // Initial estimate: find leading bit position, compute rough 1/sqrt
    // For Q16 input x, real value is x/ONE. We want ONE/sqrt(x/ONE) = ONE*sqrt(ONE/x) = ONE * sqrt(ONE) / sqrt(x)
    // = ONE * 256 / sqrt(x) (since sqrt(ONE) = sqrt(65536) = 256)

    // Simple initial estimate using bit manipulation
    let bits = 63 - (x as u64).leading_zeros() as i64; // floor(log2(x))
    // sqrt(x) ≈ 2^(bits/2), so 1/sqrt(x) ≈ 2^(-bits/2)
    // In Q16: ONE * 2^(-bits/2) = 65536 >> (bits/2)
    let mut y = ONE * 256 / (1i64 << ((bits + 1) / 2)); // rough estimate
    if y <= 0 { y = 1; }

    // 3 Newton-Raphson iterations: y = y * (3*ONE - x * y * y / ONE) / (2*ONE)
    for _ in 0..3 {
        let y2 = (y * y) >> FRAC_BITS;
        let xy2 = (x * y2) >> FRAC_BITS;
        let three_minus = 3 * ONE - xy2;
        y = (y * three_minus) / (2 * ONE);
        if y <= 0 { y = 1; }
    }

    y
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_exp_at_zero() {
        assert_eq!(integer_exp(0), ONE);
    }

    #[test]
    fn test_exp_very_negative() {
        assert_eq!(integer_exp(-10 * ONE), 0);
    }

    #[test]
    fn test_exp_monotonic() {
        let mut prev = 0i64;
        for i in (-8 * ONE as i64)..=0 {
            let val = integer_exp(i);
            assert!(val >= prev, "exp not monotonic at {}: {} < {}", i, val, prev);
            prev = val;
        }
    }

    #[test]
    fn test_softmax_sums_to_one() {
        let input = vec![ONE, 2 * ONE, 3 * ONE];
        let output = softmax_i64(&input);
        let sum: i64 = output.iter().sum();
        // Should be within 1% of ONE
        assert!((sum - ONE).abs() < ONE / 100, "softmax sum {} not close to {}", sum, ONE);
    }

    #[test]
    fn test_softmax_argmax_preserved() {
        // The largest input should produce the largest softmax output
        let input = vec![ONE, 5 * ONE, 2 * ONE, -ONE];
        let output = softmax_i64(&input);
        assert_eq!(argmax_i64(&output), 1);
    }

    #[test]
    fn test_argmax_tiebreak() {
        let input = vec![ONE, 2 * ONE, 2 * ONE, ONE];
        assert_eq!(argmax_i64(&input), 1); // lowest index wins
    }

    #[test]
    fn test_isqrt_one() {
        // isqrt(ONE) should be ONE (1/sqrt(1) = 1)
        let result = integer_isqrt(ONE);
        let error = (result - ONE).abs();
        assert!(error < ONE / 50, "isqrt(ONE) = {} (error {})", result, error);
    }

    #[test]
    fn test_isqrt_four() {
        // isqrt(4*ONE) should be ONE/2 (1/sqrt(4) = 0.5)
        let result = integer_isqrt(4 * ONE);
        let expected = ONE / 2;
        let error = (result - expected).abs();
        assert!(error < ONE / 50, "isqrt(4*ONE) = {} (expected {}, error {})", result, expected, error);
    }

    #[test]
    fn test_determinism_softmax_1000() {
        let input = vec![ONE, 2 * ONE, -ONE, 3 * ONE, ONE / 2];
        let first = softmax_i64(&input);
        for _ in 0..1000 {
            let result = softmax_i64(&input);
            assert_eq!(result, first, "softmax not deterministic");
        }
    }
}
