//! The exact v0.8 release this bridge installs, fixed at compile time.
//!
//! `pins/active.json` is generated by `scripts/legacy-bridge/pin-release.py`
//! from an immutable, bot-published, signature-verified release. The unit
//! tests below cross-check every pinned digest against the real signed
//! `SHA256SUMS` fixture, so a hand edit that drifts from the release fails CI.

use std::collections::BTreeMap;

use anyhow::{Context, Result, anyhow, ensure};
use serde::Deserialize;

use crate::sshsig;

/// The reviewed pin set compiled into this bridge.
///
/// It pins arc-node v0.8.11, whose community registration publishes a
/// privacy-safe public name (PR #134), so a bridged node registers as a
/// stake-0 community observer and computes only after the operator opts in.
/// Regenerate with `pin-release.py --tag <tag> --write` together with that
/// tag's `fixtures/<tag>` manifest; the tests below that name the tag move
/// with it.
pub const EMBEDDED_PINS: &str = include_str!("../pins/active.json");

pub const PINS_SCHEMA: &str = "arc.legacy-bridge.pins.v1";
pub const REPOSITORY: &str = "FerrumVir/arc-chain";
pub const MANIFEST_NAME: &str = "SHA256SUMS";
pub const MANIFEST_SIGNATURE_NAME: &str = "SHA256SUMS.sig";
pub const GENESIS_NAME: &str = "genesis.toml";
pub const SEEDS_NAME: &str = "testnet-seeds.txt";
pub const SIGNER_PRINCIPAL: &str = "arc-release";
pub const SIGNER_NAMESPACE: &str = "arc-release-manifest-v1";

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PinnedFile {
    pub sha256: String,
    pub size: u64,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NamedPinnedFile {
    pub name: String,
    pub sha256: String,
    pub size: u64,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NodeRelease {
    pub tag: String,
    pub version: String,
    pub commit: String,
    pub manifest: NamedPinnedFile,
    pub manifest_signature: NamedPinnedFile,
    /// True only for node builds that register under a privacy-safe public
    /// name (PR #134). Older builds publish `name (hostname)` on the public
    /// scoreboard, so the bridge keeps them out of community registration.
    pub worker_names_privacy_safe: bool,
    pub assets: BTreeMap<String, PinnedFile>,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ManifestSigner {
    pub principal: String,
    pub namespace: String,
    pub public_key: String,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ModelPin {
    pub file_name: String,
    pub sha256: String,
    pub size: u64,
    pub url: String,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Pins {
    pub schema: String,
    pub bridge_version: String,
    pub repository: String,
    pub node_release: NodeRelease,
    pub manifest_signer: ManifestSigner,
    pub community_rpc_origins: Vec<String>,
    pub model: ModelPin,
}

impl Pins {
    pub fn embedded() -> Result<Pins> {
        Pins::parse(EMBEDDED_PINS)
    }

    pub fn parse(text: &str) -> Result<Pins> {
        let pins: Pins = serde_json::from_str(text).context("bridge pin set is not valid JSON")?;
        pins.validate()?;
        Ok(pins)
    }

    fn validate(&self) -> Result<()> {
        ensure!(
            self.schema == PINS_SCHEMA,
            "unsupported bridge pin schema {:?}",
            self.schema
        );
        ensure!(
            is_strict_version(&self.bridge_version),
            "bridge_version must be MAJOR.MINOR.PATCH"
        );
        ensure!(
            self.repository == REPOSITORY,
            "bridge pins target an unexpected repository"
        );

        let release = &self.node_release;
        ensure!(
            is_strict_version(&release.version),
            "node release version must be MAJOR.MINOR.PATCH"
        );
        ensure!(
            release.tag == format!("v{}", release.version),
            "node release tag must be exactly v<version>"
        );
        ensure!(
            version_at_least(&release.version, (0, 8, 0)),
            "the bridge only installs v0.8.0 or newer nodes"
        );
        ensure!(
            is_lower_hex(&release.commit, 40),
            "node release commit must be 40 lowercase hex characters"
        );
        ensure!(
            release.manifest.name == MANIFEST_NAME,
            "manifest pin must name SHA256SUMS"
        );
        ensure!(
            release.manifest_signature.name == MANIFEST_SIGNATURE_NAME,
            "manifest signature pin must name SHA256SUMS.sig"
        );
        for file in [&release.manifest, &release.manifest_signature] {
            check_digest_and_size(&file.name, &file.sha256, file.size)?;
        }
        for (name, file) in &release.assets {
            ensure!(
                is_asset_name(name),
                "pinned asset name is not a plain release asset name"
            );
            check_digest_and_size(name, &file.sha256, file.size)?;
        }
        for platform in Platform::ALL {
            for name in [platform.node_asset(), platform.cli_asset()] {
                ensure!(
                    release.assets.contains_key(name),
                    "pins are missing the {name} asset"
                );
            }
        }
        for name in [GENESIS_NAME, SEEDS_NAME] {
            ensure!(release.assets.contains_key(name), "pins are missing {name}");
        }

        ensure!(
            self.manifest_signer.principal == SIGNER_PRINCIPAL,
            "unexpected manifest signer principal"
        );
        ensure!(
            self.manifest_signer.namespace == SIGNER_NAMESPACE,
            "unexpected manifest signature namespace"
        );
        sshsig::parse_ed25519_public_key(&self.manifest_signer.public_key)
            .context("pinned release public key is invalid")?;

        ensure!(
            !self.community_rpc_origins.is_empty(),
            "pins must list the community RPC origins"
        );
        let mut seen = std::collections::BTreeSet::new();
        for origin in &self.community_rpc_origins {
            ensure!(
                origin.starts_with("https://") && !origin.ends_with('/') && origin.len() > 8,
                "community RPC origins must be https:// origins without a path"
            );
            ensure!(
                seen.insert(origin.as_str()),
                "community RPC origins must be unique"
            );
        }

        check_digest_and_size(&self.model.file_name, &self.model.sha256, self.model.size)?;
        ensure!(
            self.model.url.starts_with("https://"),
            "the model URL must use https"
        );
        Ok(())
    }

    pub fn asset(&self, name: &str) -> Result<&PinnedFile> {
        self.node_release
            .assets
            .get(name)
            .ok_or_else(|| anyhow!("{name} is not pinned"))
    }

    pub fn signer_key(&self) -> Result<[u8; 32]> {
        sshsig::parse_ed25519_public_key(&self.manifest_signer.public_key)
    }
}

fn check_digest_and_size(name: &str, sha256: &str, size: u64) -> Result<()> {
    ensure!(
        is_lower_hex(sha256, 64),
        "{name} must be pinned by a lowercase SHA-256"
    );
    ensure!(size > 0, "{name} must be pinned with a positive size");
    Ok(())
}

pub fn is_asset_name(name: &str) -> bool {
    !name.is_empty()
        && !name.starts_with('.')
        && name
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'.' | b'-'))
}

pub fn is_lower_hex(value: &str, len: usize) -> bool {
    value.len() == len
        && value
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
}

/// Strict `MAJOR.MINOR.PATCH` with no sign, prefix, or leading zeros.
pub fn parse_version(value: &str) -> Option<(u64, u64, u64)> {
    let mut parts = value.split('.');
    let major = parse_component(parts.next()?)?;
    let minor = parse_component(parts.next()?)?;
    let patch = parse_component(parts.next()?)?;
    if parts.next().is_some() {
        return None;
    }
    Some((major, minor, patch))
}

fn parse_component(part: &str) -> Option<u64> {
    if part.is_empty() || part.len() > 9 || !part.bytes().all(|byte| byte.is_ascii_digit()) {
        return None;
    }
    if part.len() > 1 && part.starts_with('0') {
        return None;
    }
    part.parse().ok()
}

pub fn is_strict_version(value: &str) -> bool {
    parse_version(value).is_some()
}

pub fn version_at_least(value: &str, minimum: (u64, u64, u64)) -> bool {
    parse_version(value).is_some_and(|version| version >= minimum)
}

/// A platform the v0.8 release publishes headless binaries for.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Platform {
    MacosArm64,
    MacosX86_64,
    LinuxX86_64,
    LinuxArm64,
    WindowsX86_64,
}

impl Platform {
    pub const ALL: [Platform; 5] = [
        Platform::MacosArm64,
        Platform::MacosX86_64,
        Platform::LinuxX86_64,
        Platform::LinuxArm64,
        Platform::WindowsX86_64,
    ];

    pub fn current() -> Option<Platform> {
        if cfg!(all(target_os = "macos", target_arch = "aarch64")) {
            Some(Platform::MacosArm64)
        } else if cfg!(all(target_os = "macos", target_arch = "x86_64")) {
            Some(Platform::MacosX86_64)
        } else if cfg!(all(target_os = "linux", target_arch = "x86_64")) {
            Some(Platform::LinuxX86_64)
        } else if cfg!(all(target_os = "linux", target_arch = "aarch64")) {
            Some(Platform::LinuxArm64)
        } else if cfg!(all(target_os = "windows", target_arch = "x86_64")) {
            Some(Platform::WindowsX86_64)
        } else {
            None
        }
    }

    /// The v0.8 node asset the bridge downloads and runs.
    pub fn node_asset(self) -> &'static str {
        match self {
            Platform::MacosArm64 => "arc-node-macos-arm64",
            Platform::MacosX86_64 => "arc-node-macos-x86_64",
            Platform::LinuxX86_64 => "arc-node-linux-x86_64",
            Platform::LinuxArm64 => "arc-node-linux-arm64",
            Platform::WindowsX86_64 => "arc-node-windows-x86_64.exe",
        }
    }

    /// The v0.8 CLI asset, used only to create and check the node keyfile.
    pub fn cli_asset(self) -> &'static str {
        match self {
            Platform::MacosArm64 => "arc-cli-macos-arm64",
            Platform::MacosX86_64 => "arc-cli-macos-x86_64",
            Platform::LinuxX86_64 => "arc-cli-linux-x86_64",
            Platform::LinuxArm64 => "arc-cli-linux-arm64",
            Platform::WindowsX86_64 => "arc-cli-windows-x86_64.exe",
        }
    }

    /// The legacy v0.7 asset name this platform's bridge launcher ships under.
    /// v0.7 headless installers called 64-bit ARM Linux `linux-aarch64`.
    pub fn legacy_launcher_asset(self) -> &'static str {
        match self {
            Platform::MacosArm64 => "arc-node-macos-arm64",
            Platform::MacosX86_64 => "arc-node-macos-x86_64",
            Platform::LinuxX86_64 => "arc-node-linux-x86_64",
            Platform::LinuxArm64 => "arc-node-linux-aarch64",
            Platform::WindowsX86_64 => "arc-node-windows-x86_64.exe",
        }
    }

    pub fn is_windows(self) -> bool {
        self == Platform::WindowsX86_64
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::manifest;

    const FIXTURE_MANIFEST: &[u8] = include_bytes!("../fixtures/v0.8.11/SHA256SUMS");
    const FIXTURE_SIGNATURE: &[u8] = include_bytes!("../fixtures/v0.8.11/SHA256SUMS.sig");

    #[test]
    fn embedded_pins_parse_and_validate() {
        let pins = Pins::embedded().unwrap();
        assert_eq!(pins.node_release.tag, "v0.8.11");
        assert!(pins.node_release.worker_names_privacy_safe);
        assert_eq!(pins.community_rpc_origins.len(), 6);
    }

    #[test]
    fn bridge_version_matches_crate_version() {
        let pins = Pins::embedded().unwrap();
        assert_eq!(pins.bridge_version, env!("CARGO_PKG_VERSION"));
        // The bridge must stay on the v0.7 line: every v0.8 consumer ignores
        // releases below 0.8.0, which is what keeps it out of their channel.
        assert!(!version_at_least(&pins.bridge_version, (0, 8, 0)));
        assert!(version_at_least(&pins.bridge_version, (0, 7, 12)));
    }

    #[test]
    fn every_pinned_digest_matches_the_signed_release_manifest() {
        let pins = Pins::embedded().unwrap();
        assert_eq!(
            crate::hashing::sha256_bytes(FIXTURE_MANIFEST),
            pins.node_release.manifest.sha256
        );
        assert_eq!(
            FIXTURE_MANIFEST.len() as u64,
            pins.node_release.manifest.size
        );
        assert_eq!(
            crate::hashing::sha256_bytes(FIXTURE_SIGNATURE),
            pins.node_release.manifest_signature.sha256
        );
        assert_eq!(
            FIXTURE_SIGNATURE.len() as u64,
            pins.node_release.manifest_signature.size
        );
        let signature = std::str::from_utf8(FIXTURE_SIGNATURE).unwrap();
        sshsig::verify(
            signature,
            FIXTURE_MANIFEST,
            SIGNER_NAMESPACE,
            &pins.signer_key().unwrap(),
        )
        .unwrap();
        let parsed = manifest::parse(FIXTURE_MANIFEST).unwrap();
        parsed.check_pins(&pins).unwrap();
    }

    #[test]
    fn pins_reject_tampering() {
        let text = EMBEDDED_PINS.replace("\"v0.8.11\"", "\"v0.8.9\"");
        assert!(
            Pins::parse(&text).is_err(),
            "tag/version mismatch must fail"
        );
        let text = EMBEDDED_PINS.replace("\"0.7.12\"", "\"0.7.x\"");
        assert!(
            Pins::parse(&text).is_err(),
            "non-strict bridge version must fail"
        );
        let text = EMBEDDED_PINS.replace("https://149.28.32.76", "http://149.28.32.76");
        assert!(Pins::parse(&text).is_err(), "plain-http origin must fail");
        let text = EMBEDDED_PINS.replacen("\"schema\"", "\"unexpected\": 1, \"schema\"", 1);
        assert!(Pins::parse(&text).is_err(), "unknown fields must fail");
    }

    #[test]
    fn strict_versions() {
        assert_eq!(parse_version("0.8.10"), Some((0, 8, 10)));
        assert_eq!(parse_version("0.7.12"), Some((0, 7, 12)));
        for bad in [
            "",
            "0.8",
            "0.8.10.1",
            "v0.8.10",
            "0.08.1",
            "0.8.-1",
            "0.8.1-rc1",
            "a.b.c",
        ] {
            assert_eq!(parse_version(bad), None, "{bad}");
        }
        assert!(version_at_least("0.8.0", (0, 8, 0)));
        assert!(!version_at_least("0.7.99", (0, 8, 0)));
    }

    #[test]
    fn platform_asset_names_match_v07_and_v08_conventions() {
        assert_eq!(
            Platform::LinuxArm64.legacy_launcher_asset(),
            "arc-node-linux-aarch64"
        );
        assert_eq!(Platform::LinuxArm64.node_asset(), "arc-node-linux-arm64");
        for platform in Platform::ALL {
            assert!(platform.node_asset().starts_with("arc-node-"));
            assert!(platform.cli_asset().starts_with("arc-cli-"));
            assert_eq!(
                platform.is_windows(),
                platform.node_asset().ends_with(".exe")
            );
        }
    }
}
